### ISSUE TITLE
Can't build solution without adding reference to System.Xml and F# 4.0.0

### ISSUE THREAD

**Issue by jamesholwell** [StackExchange/dapper-dot-net#138]
From a clean build, I have to add a reference to System.Xml to Dapper NET35, 40 and 45 for the solution to build.

To run DapperTests NET40 I also needed FSharp.Core 4.0.0 (I have 4.3, apparently) so I had to add a reference to the 4.0.0 nuget package.

Is this just me, or would this be useful to submit a PR for?

**Comment by NickCraver** [comment]
@jamesholwell are you still having issues building? I couldn't repro any trouble here either - but I am on the latest tooling, etc. so it's not the best of test cases.
