### ISSUE TITLE
Infinite Cycle of Hyperlinks

### ISSUE THREAD

**Issue by Ceyword** [StackExchange/dapper-dot-net#146]
The Page on the URL http://code.google.com/p/dapper-dot-net/ point to this Project at the URL https://github.com/StackExchange/dapper-dot-net (Dapper has moved to github. See you there). Maybe the page on the latter URL should not have a prominent link that points back to the former URL. Thanks

**Comment by johandanforth** [comment]
@mgravell Can you edit the project description from "Dapper 
http://code.google.com/p/dapper-dot-net/" to something more relevant?

**Comment by NickCraver** [comment]
It took me a while to figure out what the hell this was asking for...but then I figured it out :) 

I just changed the description to "Dapper - a simple object mapper for .Net" and removed the Google code link (which GitHub started displaying differently at some point).
