### ISSUE TITLE
Table Valued parameters to Stored procedure fails

### ISSUE THREAD

**Issue by hskarachiwala** [StackExchange/dapper-dot-net#155]
Upgraded Dapper from 1.26 to 1.34. Am getting this error wherever I pass Table Valued parameters to a stored procedure (using SQL Azure)

The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 7 : Data type 0x62 (sql_variant) has an invalid type for type-specific metadata.

What have I missed out on??

**Comment by NickCraver** [comment]
Are you seeing this on the latest Dapper?

**Comment by KishorMakwana** [comment]
yes i have user latest Dapper 2.0.123

**Comment by dinilthomas** [comment]
Inside the add function of parameter object pass argument DbType.Object
eg:- DynamicParameters parameterObject = new DynamicParameters();
parameterObject.Add("@Table", dtTable, DbType.Object);
