### ISSUE TITLE
Update Dapper.Contrib NuGet distribution to a version that works without Transactions

### ISSUE THREAD

**Issue by derekgreer** [StackExchange/dapper-dot-net#161]
The current version of Dapper.Contrib published to NuGet (1.0) requires a transaction which doesn't match the documentation.  When used normally, you will get the following error on insert:

System.InvalidOperationExceptionExecuteNonQuery requires the command to have a transaction when the connection assigned to the command is in a pending local transaction.  The Transaction property of the command has not been initialized.

Please update NuGet with the latest version which fixes this issue.

**Comment by johandanforth** [comment]
The nuget package Dapper.Contrib is now updated.
