### ISSUE TITLE
In the same vein of TypeHandlers, how about a QueryProcessor?

### ISSUE THREAD

**Issue by JulianRooze** [StackExchange/dapper-dot-net#176]
I'm currently trying to decide whether or not to fork and modify Dapper to accomplish something that isn't really possible now and that is to be able to modify the command text of a query.

The situation: we have a fairly large existing code base that uses Dapper and we need to have the ability to modify our queries to be context dependent. That is, if a query is currently `select * from Products where ID = @id` we want to be able to have that (depending on the current context) get transformed into `select * from Products_en where ID = @id` when the current user's language is set to English. First of, no that can't be accomplished by adding a language filter in the where-clause since the context I'm using here is greatly simplified, they really are physically different tables :) I think we really need a dynamic query in our case.

It's inevitable that we'll have to modify each and every query that currently touches the Products table; we'll have to replace every instance of `from Products` with something like `from [[PRODUCTS]]`. However, while we could do the actual context dependent replace inside something like `connection.Query<int>(QueryProcessor.Process("select count(*) from [[PRODUCTS]]"))` I prefer not having to do this for each query as it's something that can be easily forgotten when writing a query and it would be a maintenance nightmare if we ever to decide to change the method signature, having to modify 300 references to that method. 

So that's where modifying Dapper comes in: would it be a good idea to add a `SqlMapper.AddCommandTextProcessor(ICommandTextProcessor processor)`? With `ICommandTextProcessor` being defined as:

```C#
public interface ICommandTextProcessor
{
  string Process(string commandText);
}
```

If one has been defined, it would then be used inside the CommandDefinition type's constructor to do *something* with the query. In our case, it would be replacing the placeholders with a proper implementation.

Of course, if I make this modification it would be preferable if it was one that could be merged back to the mainline :) So I'm open to any suggestions here.

**Comment by NickCraver** [comment]
@JulianRooze any update on success or fail here? I don't want to close this on you, or leave it forever forgotten :)
