### ISSUE TITLE
Object of type 'System.Int32' cannot be converted to type 'System.Int16' when using insert

### ISSUE THREAD

**Issue by yaronlevi** [StackExchange/dapper-dot-net#196]
The bug is detailed in s StackOverflow question I posted: 
http://stackoverflow.com/questions/26561451/dapper-extensions-object-of-type-system-int32-cannot-be-converted-to-type-s/26563263#26563263

**Comment by johandanforth** [comment]
Fixed now

**Comment by yaronlevi** [comment]
Great! Thank you

On Sun, Jun 7, 2015 at 9:57 PM, Johan Danforth <notifications@github.com>
wrote:

> Closed #196 <https://github.com/StackExchange/dapper-dot-net/issues/196>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/196#event-324731911>
> .
>



-- 
ירון.
