### ISSUE TITLE
NullReferenceException in PackListParameters

### ISSUE THREAD

**Issue by ejball** [StackExchange/dapper-dot-net#203]
See comment in 3691fe138c68dd5ddf63ba4ec88525885cb93ea6.

https://github.com/StackExchange/dapper-dot-net/commit/3691fe138c68dd5ddf63ba4ec88525885cb93ea6#diff-c997551313ba729880a0f4bee9c963caR2406

**Comment by NickCraver** [comment]
Cleaning up - this is merged in, thanks!
