### ISSUE TITLE
TypeHandler<> can't override default typeMap for base types

### ISSUE THREAD

**Issue by maurodx** [StackExchange/dapper-dot-net#206]
Trying to solve an issue (losing milliseconds on DateTime in SQLite database) using a TypeHandler<DateTime> that do conversion between db string (in format "o") and DateTime doesn't pass test because typeMap[DateTime] is processed before custom type handlers.

Probably the solution is to invert the lookup sequence or add the chance for remove a default type map with a brother of 

public static void AddTypeMap(Type type, DbType dbType)

as

public static void RemoveTypeMap(Type type)

**Comment by NickCraver** [comment]
See #471 up for v2, closing out to consolidate.
