### ISSUE TITLE
Implicit cast not working on async calls

### ISSUE THREAD

**Issue by sergey-netdev** [StackExchange/dapper-dot-net#218]
The underlaying `IDbConnection` is `OracleConnection`. The query is typical aggregation that the .NET provider returns as `decimal` c# type. The following code works just fine:
```
int total = DB.Query<int>(sql, sqlParams).Single();
```
while async version throws `InvalidCastException`:
```
int total = (await DB.QueryAsync<int>(sql, sqlParams)).Single();
```

the following work-around fixes the issue:
```
int total = (int) (await DB.QueryAsync<decimal>(sql, sqlParams)).Single();
```
but looks just ugly. The problem line is https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper%20NET45/SqlMapperAsync.cs#L98

**Comment by thomaslevesque** [comment]
I just stumbled upon this issue as well, using SQLite.

This works:

    int freelistCount = cnx.Query<int>("PRAGMA freelist_count").Single();

But this throws an `InvalidCastException`:

    int freelistCount = (await cnx.QueryAsync<int>("PRAGMA freelist_count")).Single();

**Comment by thomaslevesque** [comment]
Apparently this has been fixed in 2ead242828fe61599c40a0daf143ff3dccede3d5, but it's not in the latest stable NuGet package

**Comment by mgravell** [comment]
We have been using 1.50 in production for a while now. It is IMO stable, if
you want to use it.

**Comment by thomaslevesque** [comment]
OK, thanks Marc! (by "we", I assume you mean Stackoverflow?)

**Comment by NickCraver** [comment]
Closing this out since a fix is in place and available.
