### ISSUE TITLE
Dapper and Expression Trees

### ISSUE THREAD

**Issue by bhaidar** [StackExchange/dapper-dot-net#223]
Hello,
Is Dapper going to support Expression Trees and IQueryable interfaces? If no, are there workarounds to be able to prepare filters on my queries before sending them for execution at SQL Server?
Thanks

**Comment by NickCraver** [comment]
Confirming this isn't the market Dapper (core) is after. It's slower and more expensive (by nature of doing more) and other ORM libraries provide that if needed. If the community wants to offer extensions as @jamesholwell indicated above, then it's a possibility as a separate/wrapping package.

Closing this out just to clean things up.
