### ISSUE TITLE
Pass parameters by index 

### ISSUE THREAD

**Issue by dimzon** [StackExchange/dapper-dot-net#231]
https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper%20NET40/SqlMapper.cs#L2144

why not just clone parameter (at least for primitive types)

**Comment by mgravell** [comment]
I guess it just feels more obvious to me this way, especially when we get
large values; passing them multiple times seems confusing and easy to get
wrong in subtle ways. The SQL can always use a local, no?

**Comment by dimzon** [comment]
I have a real butt-heart working with IBM DB2 via ODBC driver (for some reasons IBM DB2 .NET provider deployment  is  impossible). There are no way to pass parameters except by index...

**Comment by mgravell** [comment]
Yep, I acknowledge this need - hence why dapper supports index usage. The
tricky question is: is it always OK to duplicate. I need to re-check.

**Comment by dimzon** [comment]
I made (and use in production) my own OdbcConnection/OdbcCommand wrapper to make named to indexed substitution just into ExecuteXXXX. It's ok to create a copy for all ```Direction=Input``` parameters :)

btw there are other .NET ODBC driver problems (in case DB2 it can't work well with XML and NCLOB in OdbcDataReader) so I'm really  bored with workarounds (maybe better way is to fork Mono ODBC).

**Comment by NickCraver** [comment]
@dimzon Where are you on this today? It's been a while and several versions ago - as who-uses-what changes I wanted to gauge the current need/want level here.
