### ISSUE TITLE
Poor-man materialzer

### ISSUE THREAD

**Issue by dimzon** [StackExchange/dapper-dot-net#232]
I propose to add overloaded ```Query<T>``` method receiving ```Func<IDataRecord,T>``` argument:
```var tuples=cn.Query("select ...", new {name="jo"}, dr=>Tuple.Create(dr.GetInt32(0),dr.GetString(1))); ```

**Comment by mgravell** [comment]
In that scenario, why not use ExecuteReader? What would this add?

**Comment by dimzon** [comment]
this would add shorter/nicer syntax and functional style :)

**Comment by mburbea** [comment]
Couldn't you do this with the multimap api?
```
var tuples = cn.Query<int,string,Tuple<int,string>>("select ...",
new {name="jo"},Tuple.Create,splitOn="name");
```
