### ISSUE TITLE
Remove Google Code link

### ISSUE THREAD

**Issue by KoalaBear84** [StackExchange/dapper-dot-net#236]
On top of the repository (https://github.com/StackExchange/dapper-dot-net) is the following text / link:

"Dapper 
http://code.google.com/p/dapper-dot-net/"

Please remove. When you click the only thing to see is that it has moved to github.

**Comment by shrayasr** [comment]
:+1:

**Comment by NickCraver** [comment]
Fixed a while ago - didn't see there were multiple issues created for it, sorry!
