### ISSUE TITLE
ExecuteScalar doesn't cast correctly

### ISSUE THREAD

**Issue by xPaw** [StackExchange/dapper-dot-net#237]
I've been trying to use something like `ExecuteScalar<App>` and it appears to be casting incorrectly compared to `Query<App>`, which results in this exception: `Invalid cast from 'System.String' to 'xx.App'.`

I believe changing `Query` to `ExecuteScalar` in [this test](https://github.com/StackExchange/dapper-dot-net/blob/master/Tests/Tests.cs#L306) will reproduce the issue.

EDIT: It appears that `ExecuteScalar` is supposed to only return the first COLUMN of the first row, that's completely my fault.

**Comment by KoalaBear84** [comment]
Just a note! At my previous job we used only Stored Procedures with Scalar things. SP executes a task and returns -1, 0 or 1 for example. The exact definition of scalar for me was that it returns a single value, I didn't knew it could also be a result set which will take the first column of the first row.

http://stackoverflow.com/questions/20424966/what-is-a-scalar-query
