### ISSUE TITLE
Subtly broken results with bad query after Dapper upgrade

### ISSUE THREAD

**Issue by JulianRooze** [StackExchange/dapper-dot-net#239]
We recently updated from 1.13 to the latest version of Dapper. After updating, we encountered a bug in production where the query selected N tables (`select a.*, b.*, c.*`) whereas the result reader only read N-1 tables (`results.Read<A, B, A>()`). If you do this, the values of the the `c.*` get set on `B`. In 1.13, only `a.*` and `b.*` were read from the result set and whatever was incorrectly also included, `c.*` in this case, was discarded/ignored.

I've traced the problem to this commit: 5afba486fcc5627efce33632a2a78b0e17d2cffd

With specifically this section of code:

```csharp
// in this we go right to left through the data reader in order to cope with properties that are
// named the same as a subsequent primary key that we split on
int currentPos = reader.FieldCount;
int splitIdx = splits.Length - 1;
var currentSplit = splits[splitIdx];
for (var typeIdx = types.Length - 1; typeIdx >= 0; --typeIdx)
```

The relevant code currently:

https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper%20NET40/SqlMapper.cs#L2004

Because it now reads the result set from right to left, it starts by reading the results of `c.*` and projects those values onto `B`. 

Obviously, our query was broken but this results in a very subtle bug because it doesn't generate any kind of exception, merely incorrect data. In my view, it should either be resistant to these sorts of poorly written queries (like 1.13 was, because it simply read left to right) or an exception should be thrown so that your code cannot fail silently like it did for us.

I'm not sure how to fix this (and if you agree that this needs fixing). Perhaps it could throw an exception if the last type to be mapped (`typeIdx == 0`) contains multiple columns with the same name and equal to `splitOn` (we use the default `"ID"`). In our case, `reader.FieldCount` was 30 and indexes 11-29 (where 11 was `ID`) were projected to type `B` and indexes 0-10 were projected to type `A` (where both 0 and 7 were `ID` so it could potentially throw an exception on that). However, I don't know what kind of hell that would unleash on existing codebases.

**Comment by NickCraver** [comment]
I'm not sure we can actually reliably tell that something is wrong here. You are permitted to have any columns you want to be serialized at the end, including repetition, etc. For example some people will do:
```SQL
Select a.*, b.*, 'Override String' as bColumn
```
...which is perfectly valid.

I think it's a choice between the best behaviors here (as in there is no 100% correct solution). IMO, the way it currently behaves is the best and most flexible. I'm open to arguments for what would be a **breaking** change here, but they would have to be pretty strong for such a thing - and slated for a 2.0 release at a minimum.
