### ISSUE TITLE
Remove link to Google Code from project description

### ISSUE THREAD

**Issue by BrainCrumbz** [StackExchange/dapper-dot-net#242]
Project home page at Google code now says that project itself has moved here, to Github. 

Project home page here at Github still shows on the very first description a link to Google code, which I guess it should be removed by now.

![image](https://cloud.githubusercontent.com/assets/3185573/6108084/7efa34aa-b070-11e4-8b91-5db6eb2aab92.png)

**Comment by NickCraver** [comment]
There were a few dupes for this I missed - fixed a while ago!
