### ISSUE TITLE
Genereted query 

### ISSUE THREAD

**Issue by valza** [StackExchange/dapper-dot-net#244]
How can i see genereated dapper query?
e.g. I have problem with insert query. I use OracleDynamicParameters and my query calls stored procedure.

**Comment by mgravell** [comment]
We usually use mini-profiler (aka mvc-mini-profiler) for this. Any use?

**Comment by valza** [comment]
I use dapper in wcf service. Also via integration tests.

**Comment by sergey-litvinov** [comment]
You can use MiniProfiler in both cases. MiniProfiler has integration for WCF, and also you can use it in integration tests, and then access gathered data via `MiniProfiler.Current` property and get generated SQL query
