### ISSUE TITLE
Under Mono, Query call fails with NullReferenceException due to SequentialAccess modifier on DataReader

### ISSUE THREAD

**Issue by lusid** [StackExchange/dapper-dot-net#249]
I'm using Mono 3.12 and SQL Server 2008 R2 SP3.

When attempting to run a simple dynamic Query statement, it fails on the r.GetValues call in GetDapperRowDeserializer with a NullReferenceException. I've found that I've been able to get it to work by removing the CommandBehavior.SequentialAccess flag from the ExecuteReader call in QueryImpl<T>.

At the moment, I'm unsure whether the issue is with Dapper or the underlying Mono TDS libraries, but I thought I would post this in the hopes someone else might know how to go about solving this without having to modify Dapper itself?

I've filed a bug in Mono's Bugzilla here as well: https://bugzilla.xamarin.com/show_bug.cgi?id=27628

Thanks,
Marc

**Comment by wickedsheep** [comment]
I'm having the same issue. Any luck with this?

**Comment by wickedsheep** [comment]
I'm having the same issue.

Code:
```CSharp
...
var items = connection.Query<dynamic>("select 1 as A, 2 as B from dual").ToList();
foreach (var item in items)
    Console.WriteLine(string.Format("{0} -> {1}", item.A, item.B));
...
```

Stack trace:
```
System.NullReferenceException: Object reference not set to an instance of an object
  at System.Data.SqlClient.SqlDataReader.GetValues (System.Object[] values) [0x00000] in <filename unknown>:0
  at Dapper.SqlMapper+<>c__DisplayClass5d.<GetDapperRowDeserializer>b__5c (IDataReader r) [0x00000] in <filename unknown>:0
  at Dapper.SqlMapper+<QueryImpl>d__11`1[System.Object].MoveNext () [0x00000] in <filename unknown>:0
  at System.Collections.Generic.List`1[T].AddEnumerable (IEnumerable`1 enumerable) [0x00000] in <filename unknown>:0
  at System.Collections.Generic.List`1[T]..ctor (IEnumerable`1 collection) [0x00000] in <filename unknown>:0
  at System.Linq.Enumerable.ToList[Object] (IEnumerable`1 source) [0x00000] in <filename unknown>:0
  at Dapper.SqlMapper.Query[Object] (IDbConnection cnn, System.String sql, System.Object param, IDbTransaction transaction, Boolean buffered, Nullable`1 commandTimeout, Nullable`1 commandType) [0x00000] in <filename unknown>:0
```

I'm running Mono 3.10. Could be Dapper related, since I could get the same query to run with PetaPoco.

**Comment by lusid** [comment]
Removing the SequentialAccess flag from the ExecuteReader call in the SqlMapper.cs file solved it for me, but I'm unsure what other potential issues in Dapper such a change can cause, so I'm waiting for someone that knows what they are talking about to chime in.

**Comment by wickedsheep** [comment]
SqlDataReader GetValues has trouble with null values (ODP.NET works) in Mono. Not exactly sure why, but changing the line 2587 in SqlMapper.cs from:
```
r.GetValues(values);
```
to:
```
//r.GetValues(values);
for (int i = 0; i < values.Length; i++)
{
  if (values[i] is DBNull)
    values[i] = null;
  else
    values[i] = r.GetValue(i);
}
```
seems to work.

I don't have a local SQL Server installed to run all the tests, so if someone else doesn't already commit this back, I will try to get this in next week.

**Comment by mgravell** [comment]
Wow; that's a really bad bug in Mono's SqlDataReader implementation. That
workaround (the for loop) looks good, but I want to take a look into
reflector first to see  what the .NET GetValues does (to see what the
impact would be of using the for loop all the time). Thanks for looking,
people.

**Comment by mgravell** [comment]
K; I've pushed that to the repo and deploying 1.40 to nuget currently. I'm *assuming* this to be fixed, but please let me know if I'm wrong.

**Comment by wickedsheep** [comment]
It works, perfect. Thank you Marc.

**Comment by Slukad** [comment]
Worked for me as well. Thanks.
