### ISSUE TITLE
Would you consider having cache invalidation?

### ISSUE THREAD

**Issue by PureKrome** [StackExchange/dapper-dot-net#250]
The docs state:

>this [cached] data is never flushed

Would you consider having an _option_ to invalidate some of this caching data? By default, it's not flushed (so backward compat, etc). But if we decide to flush after an hour, then woot!

> If you are generating SQL strings on the fly without using parameters it is possible you will hit memory issues.

I totally understand the rational of parametized queries (both for unique caching and security purposes) .. so I'm not questioning that.

Just asking if it's a thought? or it's too hard? or _really_ causes perf issues, etc.

**Comment by DarekDan** [comment]
Would this work for you?
http://stackoverflow.com/questions/9612213/reset-cache-for-dapper

**Comment by mgravell** [comment]
Nothing new is needed here; firstly, for the brutal level there is already `PurgeQueryCache()`. For the ultra-granular level, there is `CommandFlags.NoCache`. But there's also an inbuilt `CollectCacheGarbage()`; this currently only looks at things that haven't been re-used, and could be improved to be more LRU or similar. For many non-parameterized queries, you *might* be able to use literal injection instead; i.e.

    where region = {=region}

which does a local replace *after* the cache level, so that the issued SQL is like:

    where region = 12345

(very useful in some scenarios)

Finally, my last question would be: why not parameterized?

**Comment by PureKrome** [comment]
> But there's also an inbuilt CollectCacheGarbage(); this currently only looks at things that haven't been re-used,

Hmm. I would have guessed that some of our _really crap_ queries (that I'm pretty sure are old and not using the parameterized way) are very unique and therefore ... should get purged? hmm.

> Finally, my last question would be: why not parameterized?

We dynamically create queries basic on search filters. If a user wants to filter by colour and gender .. then we add those dynamically.

(pseduo code)

`if (colour) then whereClause += " AND colour = {color}"` 

and finally ... lots of old code which I don't think is using parameterized stuff AND is dynamically generated - which 10000% needs to be refactored and tested. 

I was hoping to have a shorter term solution before we tackle _that_ beast.

So sum up - I really really do understand and fully agree that if _all_ our queries were paramatized, then we wouldn't be having an issue because we only have .. what .... lets say 50 queries at most.

this is a screenie of a live server mem dump ... (ignore the higlighted line - that was a random click at the time of screen grabbing).

![urgh](http://i.stack.imgur.com/Ajz6u.png)


so yeah -- with 50 or so queries, I feel that we shouldn't be doing THAT much ram .

**Comment by DarekDan** [comment]
You can still parameterize such statement:

> if (colour) then whereClause += " AND colour = {color}"

> if (colour) then whereClause += " AND colour = @color"
>                         //add color to SqlParameters list

**Comment by PureKrome** [comment]
yep! completely agree and not doing that has hurt us - look at the image above :cry: 

(above, I also ment `{colour}` should be `@color` .. bad typo)

We just need to spend some energy testing fixing up bad code and rewriting the queries, yadda yadda yadda ... but in the short term we might be able to leverage `CommandFlags.NoCache` as a quick fix _until_ we can get around to refactoring. (also, our integration tests should highlight if this quick change hurts us or not).

So yep - you guys have been really helpful!

Side Note: is `CommandFlags.NoCache` mentioned in some docs, somewhere?

**Comment by mgravell** [comment]
NoCache is probably only mentioned via the intellisense.

Re the {color} example - you can actually do some pretty fun things here - for example:

    var sb = new StringBuilder(...base query...);
    if(foo != null) sb.Append(" and x.Foo=@foo");
    if(bar != null) sb.Append(" and x.Bar=@bar");
    if(blap != null) sb.Append(" and x.Blap=@blap");
   ...
   conn.Execute(sb.ToString(), new { foo, bar, blap });

And note that it *only adds parameters that it knows appear in the sql*. If `foo` is null, it won't add the `@foo` parameter, *even though* it is in the parameter object.

**Comment by PureKrome** [comment]
>If foo is null, it won't add the @foo parameter, even though it is in the parameter object.

oh wow! now _that_ i didn't know ... and that's _very_ helpful actually :)

For the tiny-short term, we figured out that we had to create an `CommandDefinition` instance .. set the `NoCache` in that and it's still working as before.

then in a few days time, we'll refactor the queries where we accidently hardcoded and/or using string builder poorly and copy the idea, above.

Thank you heaps @mgravell for helping - :heart: Dapper since it was first released.

**Comment by mgravell** [comment]
I should emphasize: the reason it isn't added isn't because it is `null` - it is because we don't invoke the `sb.Append(...)` line, so the SQL doesn't include `@foo`

**Comment by RPM1984** [comment]
Hey @mgravell , i'm trying to implement the `CommandFlags.NoCache` technique as described here, but it still seems to be caching my query.

Here's my code:

```
var cmdDef = new CommandDefinition(query, new
{
	params
}, commandType: CommandType.Text, flags: CommandFlags.NoCache);

using (var multi = sqlConnection.QueryMultiple(cmdDef))
{
	one = multi.Read().ToList();
	two = multi.Read().ToList();
}                    
```

Upon checking the memory dump, my query is still in the Dapper cache. Am i doing something wrong with the above code?

**Comment by mgravell** [comment]
Good question; that would be a bug with `GridReader` (only impacts `QueryMultiple`); now resolved - see https://github.com/StackExchange/dapper-dot-net/commit/4997b17650e101dc0a78504813f3968e7f3d5a71

**Comment by RPM1984** [comment]
Thanks @mgravell. Any ETA on when this will be pulled into a nuget release, or should i manually build from your fix?

**Comment by mgravell** [comment]
I'll check the queue tomorrow.

**Comment by RPM1984** [comment]
@mgravell sorry to bug you mate. :smile: are you planning a NuGet release soon? Really need this in ASAP, otherwise might have to manually build a Dapper release :cry:

**Comment by mgravell** [comment]
K; I'll deploy dapper and se.redis tomorrow

**Comment by RPM1984** [comment]
Thanks so much!! :)

**Comment by RPM1984** [comment]
Ps love se redis too :)
