### ISSUE TITLE
Insert statement not working with custom TypeHandler

### ISSUE THREAD

**Issue by danwnuk** [StackExchange/dapper-dot-net#253]
I'm trying to create a custom TypeHandler to handle the following:

* Convert text[] fields from Postgres into List<string> in my object.
* Convert json fields from Postgres into JObject field in my object.

Here is my test class, and the two basic TypeHandler's I've created:

```c#
public class Test
    {
        public List<string> test_array { get; set; }
        public JObject test_json { get; set; }
    }

public class StringListHandler : SqlMapper.TypeHandler<List<string>>
    {
        public override void SetValue(IDbDataParameter parameter, List<string> value)
        {
            string stringValue = "{";

            int i = 0;
            foreach (string s in value)
            {
                if (i > 0) stringValue += ",";

                stringValue += s;
                i++;
            }
           stringValue += "}";

            parameter.Value = stringValue;
        }

        public override List<string> Parse(object value)
        {
            List<String> strings = new List<String>();
            string stringValue = (string)value;
            stringValue = stringValue.Substring(1, stringValue.Length - 2);
            char[] delim = { ',' };
            string[] words = stringValue.Split(delim);

            foreach (string word in words) {
                strings.Add(word);
            }

            return strings;
        }
}

public class JObjectHandler : SqlMapper.TypeHandler<JObject>
    {
        public override void SetValue(IDbDataParameter parameter, JObject value)
        {
            parameter.Value = value.ToString();
        }

        public override JObject Parse(object value)
        {
            string stringValue = (string)value;
            JObject obj = JObject.Parse(stringValue);

            return obj;
        }
}
```

I register the TypeHandlers in by WebApiConfig:

```c#
SqlMapper.AddTypeHandler(typeof(List<string>), new StringListHandler());
SqlMapper.AddTypeHandler(typeof(JObject), new JObjectHandler());
```

When I do the SELECT statement, the Parse method is getting called from my type handlers correctly and I am able to get a List<Test> objects back using below:

```c#
PgSqlConnection connection = ConnectionFactory.GetOpenConnection();

PgSqlCommand cmd = new PgSqlCommand();
cmd.Connection = connection;
cmd.CommandText = "SELECT test_array FROM test";

var tests = connection.Query<Test>("select * from test").ToList();
```

But when I try to do an INSERT, the SetValue method is never called, and I get an error back (a1 is not a column):

```c#
Test t = new Test();
t.test_array = new List<string>();
t.test_array.Add("hello");

t.test_json = new JObject();
t.test_json.Add(new JProperty("hi", "bye"));

var operation = "insert into test (test_array, test_json) VALUES (@a,@b)";

PgSqlConnection conn = ConnectionFactory.GetOpenConnection();
conn.Execute(operation, new { a=t.test_array, b=t.test_json });
```

I saw similar questions being asked on StackOverflow: http://stackoverflow.com/questions/25568657/dapper-typehandler-setvalue-not-being-called with no resolution, so I figured I would check here if it was an issue in Dapper or with the way I am using it.

**Comment by danwnuk** [comment]
I found another StackOverflow post that seems to have at least part of the solution:

http://stackoverflow.com/questions/28727962/dapper-custom-typehandler-setvalue-not-being-called

> Update: I've done lots of digging and think I may have found a bug - though would like someone more knowledgeable to say so. I have a List<string> param called Foo with two string values, and SetupCommand is trying to bind Foo1 and Foo2 to the underlying cmd. I assume this is the internal handling of enumerable, but shouldn't my custom data type have higher priority?

> After stepping through: here's the problem - a simple swapping of the trygetvalue below this code, and all works as expected - my handling of the list supersedes the default enumerable handling. Fix?

Can someone comment? It looks like he has reduced it down to precedence - enumerables are attempted before looking for a custom type handler, which is causing the problem. I confirmed that swapping those two blocks at least gets the SetValue method to be called, but I am still getting a failure.

```c#
 var operation = "insert into test (test_array) VALUES ('{abcd,efgh}')";
PgSqlConnection conn = ConnectionFactory.GetOpenConnection();
conn.Execute(operation);
```

This works, whereas

```c#
parameter.Value = "'{abcd,efg}'";
```

in the TypeHandler.setValue() method, paired with:

```c#
var operation = "insert into test (test_array) VALUES (@test_array)";
PgSqlConnection conn = ConnectionFactory.GetOpenConnection();
conn.Execute(operation, new { test_array=t.test_array });
```

throws the error: "PgSqlException: Column "test_array" does not exist

**Comment by danwnuk** [comment]
Thanks for getting this in johandanforth. Do you know when the next package will be published to NuGet with this fix? We've been using a custom build of Dapper in our project with a few fixes instead and would like to switch over to the main NuGet dependency.

**Comment by johandanforth** [comment]
Sorry I don't know. I don't have admin access to the nuget package. I've asked @mgravell about it though.
