### ISSUE TITLE
using decimal type

### ISSUE THREAD

**Issue by clintonvb** [StackExchange/dapper-dot-net#261]
When using a stored procedure in MS-SQL as below, I am unable to get the output as a decimal value using Dapper.

Below are some snippets of the code from my solution
```sql
CREATE PROCEDURE dbo.Proc @c decimal(10,5) OUTPUT
```

```C#
var parameters = new DynamicParameters();
parameters.Add("c", dbType: DbType.Decimal, direction: ParameterDirection.Output);

con.Execute("dbo.Proc", parameters, commandType: CommandType.StoredProcedure);
Console.WriteLine("@c \t{0}", (decimal)parameters.Get<Decimal>("c"));
```

It gets returned as 12, when my proc is hard coded to return 11.884

When I change the DbType from Decimal to Single it returns 11.884. Is there something I am doing wrong with the Decimal implementation?

**Comment by mgravell** [comment]
That doesn't sound good. I will investigate.

**Comment by mgravell** [comment]
This is precision and scale defaulting to bad values (thanks SqlClient); new controls will be available next build. The following now passes:

        public void Issue261_Decimals()
        {
            var parameters = new DynamicParameters();
            parameters.Add("c", dbType: DbType.Decimal, direction: ParameterDirection.Output, precision: 10, scale: 5);
            connection.Execute("create proc #Issue261 @c decimal(10,5) OUTPUT as begin set @c=11.884 end");
            connection.Execute("#Issue261", parameters, commandType: CommandType.StoredProcedure);
            var c = parameters.Get<Decimal>("c");
            c.IsEqualTo(11.884M);
        }

**Comment by clintonvb** [comment]
Thank you for the quick turnaround.
