### ISSUE TITLE
CommandTimeout not being honored in version 1.39

### ISSUE THREAD

**Issue by rhvarona** [StackExchange/dapper-dot-net#263]
I have a long running query where I set command timeout to 300 seconds (5 minutes).  When I run the query with version 1.38, it starts returning rows after a few minutes.  When I run the same query against the same database with version 1.39 it times out in much less than 300 seconds.

**Comment by mgravell** [comment]
Any particular method? (So I can out together a repro)

**Comment by rhvarona** [comment]
conn.Query<MyDetailClass>(myLongRunningSql, commandTimeout: 300, buffered: false)

**Comment by mgravell** [comment]
This test passes (it fails if I remove the commandTimeout parameter):

        public void Issue263_Timeout()
        {
            var watch = Stopwatch.StartNew();
            var i = connection.Query<int>("waitfor delay '00:01:00'; select 42;", commandTimeout: 300, buffered: false).Single();
            watch.Stop();
            i.IsEqualTo(42);
            var minutes = watch.ElapsedMilliseconds / 1000 / 60;
            Assert.IsTrue(minutes >= 0.95 && minutes <= 1.05);
        }

Which *strongly suggests* it is working fine. Do you have a concrete repro?

**Comment by rhvarona** [comment]
I am unable to repo on that same database, I think this can be closed.

**Comment by mgravell** [comment]
Ok; and I'm **more than happy** to look again if you find the problem recurring
