### ISSUE TITLE
Unable to read return value if multiple tables are returned

### ISSUE THREAD

**Issue by dsosunov** [StackExchange/dapper-dot-net#268]
Guys,

The following does not work:
                connection.Execute(@"create proc #TestProc (@a int, @b int, @c int)as 
                                    begin
                                        select @a;			
                                        select @b
            
                                        return @c; 
                                    end");

                var p = new DynamicParameters(new { a = 1, b = 2, c = 3 });                
                p.Add("RetVal", dbType: DbType.Int32, direction: ParameterDirection.ReturnValue);

                using (var reader = connection.QueryMultiple("#TestProc", p, commandType: CommandType.StoredProcedure))
                {
                    reader.Read();
                    var retVal = p.Get<int>("RetVal");                   
                }

Expected: 3
Actual: ApplicationException "Attempting to cast a DBNull to a non nullable type!"

if returns the single table it works fine.

**Comment by mgravell** [comment]
This is a feature of TDS, the underlying protocol; "out" and "return" come
at the *end* of the stream, and will not be reliably available until the
end of the reader. You should not attempt to access them until *after* you
have consumed all the tables. Please retry with the return-parameter access
**after** the "using" statement.

**Comment by mgravell** [comment]
Updated error message in next build:

> Attempting to cast a DBNull to a non nullable type! Note that out/return parameters will not have updated values until the data stream completes (after the 'foreach' for Query(..., buffered: false), or after the GridReader has been disposed for QueryMultiple)

I have confirmed this works fine:

            using (var reader = connection.QueryMultiple("#TestProc", p, commandType: CommandType.StoredProcedure))
            {
                reader.Read();
            }
            var retVal = p.Get<int>("RetVal");
            retVal.IsEqualTo(3);

**Comment by xebitstudios** [comment]
we have a situation that seems to be occuring intermittently throwing the 'Attempting to cast a DBNull to a non nullable type!' error in our implementation below,

public int UpdateJob(JobItem item)
{
      itemvalues.Add("@item1Count", item.StartTime);
      itemvalues.Add("@item2Count", item.EndTime);
      itemvalues.Add("@RowsAffected", dbType: DbType.Int32, direction: ParameterDirection.Output);

     _db.Execute(StoredProcedures.UPDATE_TABLE, param: itemvalues, commandType.StoredProcedure);

      return itemvalues.Get<int>("@RowsAffected");
}

I seems this is a reliability issue because we are getting this errors about 15 times out of 1000 jobs processed.
