### ISSUE TITLE
Query method with IDbCommand parameter

### ISSUE THREAD

**Issue by alexeyfadeev** [StackExchange/dapper-dot-net#270]
We have to support legacy project using DbCommand and manual mapping. We are thinking start using Dapper-dot-net for mapping instead. But how to pass IDbCommand parameter to Query method?

I have tried to add these methods to SqlMapper class, and it works! Is it possible to add such methods to project?

public static IEnumerable<T> Query<T>(this IDbConnection cnn, IDbCommand cmd)
{
    var data = QueryImpl<T>(cnn, cmd, typeof(T));
    return data.ToList();
}

private static IEnumerable<T> QueryImpl<T>(this IDbConnection cnn, IDbCommand cmd, Type effectiveType)
{
    var command = new CommandDefinition(cmd.CommandText);
    var identity = new Identity(command.CommandText, command.CommandType, cnn, effectiveType, null, null);
    var info = GetCacheInfo(identity, cmd.Parameters, command.AddToCache);

    IDataReader reader = null;

    bool wasClosed = cnn.State == ConnectionState.Closed;
    try
    {
        if (wasClosed) cnn.Open();
        reader = cmd.ExecuteReader(wasClosed ? CommandBehavior.CloseConnection | CommandBehavior.SequentialAccess : CommandBehavior.SequentialAccess);
        wasClosed = false; // *if* the connection was closed and we got this far, then we now have a reader
        // with the CloseConnection flag, so the reader will deal with the connection; we
        // still need something in the "finally" to ensure that broken SQL still results
        // in the connection closing itself
        var tuple = info.Deserializer;
        int hash = GetColumnHash(reader);
        if (tuple.Func == null || tuple.Hash != hash)
        {
            if (reader.FieldCount == 0) //https://code.google.com/p/dapper-dot-net/issues/detail?id=57
                yield break;
            tuple = info.Deserializer = new DeserializerState(hash, GetDeserializer(effectiveType, reader, 0, -1, false));
            if (command.AddToCache) SetQueryCache(identity, info);
        }

        var func = tuple.Func;
        var convertToType = Nullable.GetUnderlyingType(effectiveType) ?? effectiveType;
        while (reader.Read())
        {
            object val = func(reader);
            if (val == null || val is T)
            {
                yield return (T)val;
            }
            else
            {
                yield return (T)Convert.ChangeType(val, convertToType, CultureInfo.InvariantCulture);
            }
        }
        while (reader.NextResult()) { }
        // happy path; close the reader cleanly - no
        // need for "Cancel" etc
        reader.Dispose();
        reader = null;

        command.OnCompleted();
    }
    finally
    {
        if (reader != null)
        {
            if (!reader.IsClosed) try { cmd.Cancel(); }
                catch { /* don't spoil the existing exception */ }
            reader.Dispose();
        }
        if (wasClosed) cnn.Close();
        if (cmd != null) cmd.Dispose();
    }
}

**Comment by tomexou** [comment]
That's a great thinking. 

Current the dapper always rebind the DbParameter from DynamicParameter List each time when call Execute(sql, params), it's not efficient for heavy loop execution.

Your work resolves the problem in loop rebind DbParameter collection.

**Comment by mgravell** [comment]
After https://github.com/StackExchange/dapper-dot-net/commit/874731600e01a9dbf271c09f93a238bf7979ac6c, there is a separate API that allows you to use Dapper to parse rows (either as an `IEnumerable<T>`, or row-by-row by fetching the row parser). I think this alternative solves the same problem.

**Comment by alexeyfadeev** [comment]
Of course solves. Thank you very much!
