### ISSUE TITLE
SQL Server Guid conversion to .NET Guid type is failing

### ISSUE THREAD

**Issue by lusid** [StackExchange/dapper-dot-net#273]
I am using Mono v3.12.1 and Dapper v1.40.

My ID field is a Guid in the database. With a version of Dapper from a few weeks ago, I had no problem using a .NET Guid type in my model to retrieve the values in the ID field. Now, I'm getting the following error:

Unhandled Exception:
System.Data.DataException: Error parsing column 0 (ID=976 - Int64) ---> System.InvalidCastException: Value is not a convertible object: System.Int64 to System.Guid
at System.Convert.ToType (object,System.Type,System.IFormatProvider,bool) <0x007ae>
at long.System.IConvertible.ToType (System.Type,System.IFormatProvider) <0x0006a>
at System.Convert.ToType (object,System.Type,System.IFormatProvider,bool) <0x00737>
at System.Convert.ChangeType (object,System.Type) <0x0007a>
at (wrapper dynamic-method) object.Deserialize4a0fdc3a-9f10-4353-98c2-0a35b7fefc63 (System.Data.IDataReader) <0x000af>

**Comment by mgravell** [comment]
Interesting - I'm not sure I would have ever expected that conversion to
succeed (they are very different sizes), but I can investigate.

**Comment by mgravell** [comment]
Can you confirm the data types at the database and your model?

**Comment by lusid** [comment]
After thinking about it for awhile, I believe this is related to #272 in my case and probably not an actual bug. One of my result sets includes a UNIQUEIDENTIFIER column for the ID while the others are BIGINT. The confusion comes from it improperly pulling data from the 3rd result set (which has a BIGINT field for ID) in the 2nd Read command (which is serializing to an object that uses Guid for ID).

I'm going to close this since I believe it is a symptom of the bug.
