### ISSUE TITLE
entity-relationship to Dapper

### ISSUE THREAD

**Issue by s-ueno** [StackExchange/dapper-dot-net#278]
Hello
Micro-ORM Dapper is just good! I want to play in various directions.

Aggregator(Entity-Relationship), Criteria Pattern , etc...

https://github.com/s-ueno/Dapper.Aggregater.git

If can easily express the aggregator in poco, I thought it would be fun.
Thanks

**Comment by NickCraver** [comment]
I'm not sure what's being asked here, can you clarify?

**Comment by s-ueno** [comment]
I'm sorry.Never mind plz iggin' Me
