### ISSUE TITLE
Invalid attempt to read from column ordinal n.  With CommandBehavior.SequentialAccess, you may only read from column ordinal x or greater

### ISSUE THREAD

**Issue by pranavmehta** [StackExchange/dapper-dot-net#281]
It seems like this issue was fixed in r1.31 [Issue #148] (https://github.com/StackExchange/dapper-dot-net/issues/148) but I'm still seeing this error in Dapper 1.4, though in a slightly different context. I'm trying to read off a datareader obtained via ExecuteReaderAsync.

Reading the column values in correct order, works fine, and does not generate this exception.

Apologies if this is a dupe or I misunderstood something. 
Thanks! 
PS: Big fan of Dapper

**Comment by dotnetchris** [comment]
I just encountered this with ExecuteReaderAsync. The code in question worked fine with ExecuteReader but switching to async/await directly results in this exception. 

The sole changes were changing the original:

```c#
   using (var reader = connection.ExecuteReader(
```
to 

```c#
   using (var reader = await connection.ExecuteReaderAsync(
```

**Comment by NickCraver** [comment]
PR #416 opened to resolve this, want @mgravell eyes on it in case there's some ancient reason I'm unaware of for the current behavior.

**Comment by NickCraver** [comment]
This one's fixed, it'll be in the next release.

**Comment by dotnetchris** [comment]
thanks @NickCraver !
