### ISSUE TITLE
Dapper-level global/default CommandTimeout

### ISSUE THREAD

**Issue by Irrational86** [StackExchange/dapper-dot-net#282]
Hello all,

I've searched a bit, but haven't found anything on the subject.

Is there any opposition to implementing a global (or default) `CommandTimeout` property within Dapper? I am opening this Issue in hopes someone can provide positive or negative feedback on the suggestion.

The way this new property would work is by looking at the nullable `commandTimeout` parameter passed to the `CommandDefinition` class, and if null, use the new CommandTimeout property.

I realize that Dapper works via Extension Methods, which are static, and therefore are not instantiated, which in turn helps in maintaining differing property values (if necessary). I find that this is OK, given that the option to specify the Command Timeout is provided on each call to `Execute`, `ExecuteReader`, `Query`, and `QueryMultiple`.

The alternative, which I currently use, but do not like the additional layer is as follows:
- Create a new class which inherits from `DbConnection`
- Act as pass-thru on all of the overridable methods, except `CreateDbCommand` (which is the more involved one)
- In `CreateDbCommand`, hold the return value in a variable, modify the `CommandTimeout` property as desired, and return
- *See sample class here: [DB Connection Class with default CommandTimeout](https://gist.github.com/176f853a25e00e9abc37.git)*

I would initially take a stab at implementing it, and I am fairly confident I can. Any feedback would be greatly appreciated.

Thanks,
Jesse

**Comment by mgravell** [comment]
I don't have any fundamental objections to that, as long as it defaults to
the existing "don't explicitly set the timeout" behavior - the main change
would be a trivial tweak to the `CommandDefinition.SetupCommand` method.
I'm sure a PR would be accepted with this.

On 12 May 2015 at 03:06, Jesse <notifications@github.com> wrote:

> Hello all,
>
> I've searched a bit, but haven't found anything on the subject.
>
> Is there any opposition to implementing a global (or default)
> CommandTimeout property within Dapper? I am opening this Issue in hopes
> someone can provide positive or negative feedback on the suggestion.
>
> The way this new property would work is by looking at the nullable
> commandTimeout parameter passed to the CommandDefinition class, and if
> null, use the new CommandTimeout property.
>
> I realize that Dapper works via Extension Methods, which are static, and
> therefore are not instantiated, which in turn helps in maintaining
> differing property values (if necessary). I find that this is OK, given
> that the option to specify the Command Timeout is provided on each call to
> Execute, ExecuteReader, Query, and QueryMultiple.
>
> The alternative, which I currently use, but do not like the additional
> layer is as follows:
>
>    - Create a new class which inherits from DbConnection
>    - Act as pass-thru on all of the overridable methods, except
>    CreateDbCommand (which is the more involved one)
>    - In CreateDbCommand, hold the return value in a variable, modify the
>    CommandTimeout property as desired, and return
>    - *See sample class here: DB Connection Class with default
>    CommandTimeout <https://gist.github.com/176f853a25e00e9abc37.git>*
>
> I would initially take a stab at implementing it, and I am fairly
> confident I can. Any feedback would be greatly appreciated.
>
> Thanks,
> Jesse
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/282>.
>



-- 
Regards,

Marc

**Comment by Irrational86** [comment]
Excellent! Thanks Marc.

I will get working on it right away, and submit a PR.

**Comment by Irrational86** [comment]
@mgravell PR created.

**Comment by Irrational86** [comment]
@mgravell /*nudge*/ Is there any chance that PR #284 will get accepted?

**Comment by NickCraver** [comment]
Closing this out just to cleanup, PR was merge in.
