### ISSUE TITLE
Dapper Contrib relies only on the *Connection class name to determine the database type

### ISSUE THREAD

**Issue by ha11owed** [StackExchange/dapper-dot-net#289]
The Insert method from SqlMapperExtensions.cs needs a database type dependent adapter, but the method that selects the implementation of ISqlAdapter relies only on the DbConnection class name. 

This means using something like miniprofiler will cause the method to always default to SqlServerAdapter because it cannot determine the real database type.

The problem is in the method:

private static ISqlAdapter GetFormatter(IDbConnection connection)
{
                var name = connection.GetType().Name.ToLower();
                return !AdapterDictionary.ContainsKey(name) ?
                                new SqlServerAdapter() :
                                AdapterDictionary[name];
}

My proposal is to allow the user to specify an implementation for the method that gets the DbConnection type as a string and to use "connection.GetType().Name" as the default

**Comment by mgravell** [comment]
That would make a lot of sense; there are no *awesome* ways of doing this in ado.net, but this is better than most other options, and certainly better than GetType()

**Comment by johandanforth** [comment]
I agree. Something simple like this perhaps? Just adding a parameter:

    connection.Insert(new Car { Name = "Volvo" },sqlAdapter: new MyAdapter());

**Comment by johandanforth** [comment]
Checked in a new version with support for specifying sqladapter in Insert() and insertAsync(). Feel free to look at and test out.

**Comment by mgravell** [comment]
Note that as-implemented this is a breaking change that requires all
consumers to recompile. I'm not saying that is *necessarily* a blocker
(although I usually try to avoid it whenever possible), but it should be a
consideration - and certainly in release notes.

**Comment by johandanforth** [comment]
Is it really? I just added an optional parameter at the end of the method signature. All old tests ran fine.

**Comment by programcsharp** [comment]
Adding an optional parameter changes the method signature. To avoid
requiring consumers recompile, you'd have to make another overload instead.

**Comment by ha11owed** [comment]
Another option beside the extra parameter might be a global callback, like here (I created a branch):

https://github.com/ha11owed/dapper-dot-net

I don't know what you guys find better, the extra parameter or this. Having a new method with an extra parameter method seems more explicit, but I think the parameter should rather be of enum type:
enum DatabaseType {
 Default,
 SQLite,
 Postgres,
 MSSql,
 ...
}

**Comment by mgravell** [comment]
The old tests ran fine because they were recompiled :) optional parameters
are a compiler thing, not an IL thing. At the IL level, even when calling a
method with optional parameters, values are loaded onto the stack etc. If
you don't recompile, the caller will get MissingMethodException every time.
There are ways to add additional overloads in ways that have the same
effect (using optional parameters on the preferred overload, etc), but ...

**Comment by johandanforth** [comment]
Arhhhhg... Of course! Me..so..tired :) sorry and thanks for you patient of an old tired man...

**Comment by johandanforth** [comment]
I like the global callback approach. What do you say @mgravell ? That shouldn't break anything, should it?

**Comment by johandanforth** [comment]
@ha11owed I'm going to go with your code suggestion. I like it.

**Comment by johandanforth** [comment]
So, checked in new version of Contrib with support for a delegate to get database type, like this:

SqlMapperExtensions.GetDatabaseType = conn => "SQLiteConnection";
