### ISSUE TITLE
Dapper Contrib - table name pluralization

### ISSUE THREAD

**Issue by lyphtec** [StackExchange/dapper-dot-net#290]
The current default implementation (`GetTableName()`) just appends an "s" to the type name when mapping POCO entities to database table names when the `TableAttribute` is not specified.

I propose that this default implementation be removed for the following reasons:

- The implementation is too simplistic and doesn't cover all cases. For example:
      * It doesn't make sense for these: Equipment, Information, Rice, Species, Money, Fish, Sheep
      * Person --> People, Child -> Children, Foot -> Feet 
      * Wife, Matrix, Index ?
- People who want full control over the naming schemes of their database tables have to litter their POCOs with the TableAttribute to override this default behaviour.  When these POCOs live in a separate assembly, you are forced to take a dependency on Dapper.Contrib.
- It doesn't support usage in a non-English context - and again forces you to litter your POCOs with TableAttribute

Maybe abstract this out to an interface and provide a default implementation that can be overridden similar to how DapperExtensions does it with their [PluralizedAutoClassMapper](https://github.com/tmsmith/Dapper-Extensions/wiki/AutoClassMapper#pluralizedautoclassmapper) ?

**Comment by johandanforth** [comment]
I agree, the current pluralization is quite crude and I think I can look into that part a bit :)

**Comment by johandanforth** [comment]
@lyphtec I submitted code with a custom table name mapper delegate. Please test it out if you can. 

Example:

    public void InsertWithCustomTableNameMapper()
    {
        SqlMapperExtensions.TableNameMapper = (type) =>
        {
            switch (type.Name)
            {
                case "Person":
                    return "People";
                default:
                    var name = type.Name + "s";
                    if (type.IsInterface && name.StartsWith("I"))
                        name = name.Substring(1);
                    return name;
            }
        };

        using (var connection = GetOpenConnection())
        {
            var id = connection.Insert(new Person() { Name = "Mr Mapper" });
            id.IsEqualTo(1);
            var people = connection.GetAll<Person>();
        }
    }

**Comment by lyphtec** [comment]
Looks good.  Thanks Johan.
