### ISSUE TITLE
Dapper will not throw when a param is missing but has the same name as a column.

### ISSUE THREAD

**Issue by ofirgeller** [StackExchange/dapper-dot-net#291]
When a query has a param that shares the name of one of the columns, even when the param is missing the query runs without throwing, I think this is a dangerous thing to do.

example: 

          var args = new List<ParamClass> { new ParamClass { bad_name_id = 1, name = "mono" } };

           conn.Execute("DELETE FROM test WHERE id = @id AND name = @name",args);

Here records that match the second predict will be deleted because the first predicate ends up being
 " id = id "and not " id =  And  " (bad syntax exception, correct thing to do IMHO).

Is there a use case I am missing here for indicating a column name this way?

**Comment by juliomurta** [comment]
Hello!

I tested your case using the following source:

       public class Test
       {
            public int BadName { get; set; }
            public string Name { get; set; }
       }

        public void TestMissingParam()
        {
            var args = new List<Test> { new Test { BadName = 1, Name = "mono" } }   ;

            int i = connection.Execute("DELETE FROM test WHERE id = @id AND name = @name", args);
        }

And I got the following exception:

         "Must declare the scalar variable \"@id\"."

Are you sure is there no validation to this case?

Cheers

**Comment by ofirgeller** [comment]
I am sure that it happens yes. I have a piece of running code where the name of the column is item_id and the correct name for the parameter is ItemId, if I write 
" update table_name where item_id = @item_id " i get no exceptions and the query works. it updates all the records. meaning that the query ends up being item_id = item_id.

**Comment by mgravell** [comment]
What is your ADO.NET provider here? I *strongly suspect* this is an issue in your chosen provider (and backend).

**Comment by ofirgeller** [comment]
You might be right, I am using npgsql.

**Comment by mgravell** [comment]
I'm not sure I can do much about this in the general case; I can't parse every variant of SQL, and even if I could, things like:

    declare @foo int = 42;

is not a parameter (it is a local variable, although it could also represent a table-variable), and

    where table.Bar = 42 -- @bar - note: now hard coded, see v1.2 release notes

exists (kind of) in the SQL, but does not need to be added to the parameters (because it is in a comment)

I'm open to ideas, but I can't see how dapper could do anything different here.

**Comment by NickCraver** [comment]
@ofirgeller Did you have any luck here on the current version? I'd like to close this out since it's not a dapper side issue, but wanted to get an update for anyone else stumbling upon this and using npgsql.

**Comment by ofirgeller** [comment]
haven't upgraded dapper in a while and I moved on by making sure never to use the same name for a param as one of the columns.

**Comment by NickCraver** [comment]
@ofirgeller I'll go ahead and close this out, but I'm happy to re-open if someone else can repro with details. I was unable to repro the break on my end so not an awesome use of time to track something down which *may* have been fixed in the many changes since this was opened.

**Comment by ofirgeller** [comment]
@NickCraver Makes perfect sense to me.

**Comment by mgravell** [comment]
Are you sure you have `customerid = @CustomerId` and not `customerid = CustomerId` ? because ... if not, that sounds like a broken SQL engine; what is the backend database here?

**Comment by HarveyTaylor** [comment]
Im sure, and [Postgresql](postgres:14.2).

**Comment by mgravell** [comment]
Something sounds very weird here; do you have a runnable repro?

**Comment by sergeiakopov-wellsky** [comment]
This is indeed still an issue at least when using Postgres. When parameters don't match column names, Dapper DOES throw an error when required parameters are missing. When parameters do match column names, Dapper silently ignores the missing parameter.

```sql
-- Setup test data
CREATE TABLE TestTable (
    UserId INT NOT NULL,
    ItemId INT NOT NULL
);

INSERT INTO TestTable VALUES (1, 100), (1, 200), (2, 100);

-- This query SHOULD fail because @UserId parameter is missing
-- But Dapper silently treats @UserId as NULL instead of throwing an error
DELETE FROM TestTable WHERE UserId = @UserId AND ItemId = @ItemId;

-- When executed with only { ItemId = 100 } parameter:
-- Expected: Exception for missing @UserId parameter  
-- Actual: Query becomes "WHERE UserId = NULL AND ItemId = 100"
-- Result: Deletes 0 rows (because NULL = anything is never true)

-- Compare with this query using different parameter names:
DELETE FROM TestTable WHERE UserId = @UserIdParam AND ItemId = @ItemIdParam;

-- When executed with only { ItemIdParam = 100 } parameter:
-- Expected: Exception for missing @UserIdParam parameter
-- Actual: Exception thrown correctly: "column 'useridparam' does not exist"
```
