### ISSUE TITLE
Dapper.Contrib `Insert` throws when trying to select `@@identity` on SQL Server 2008R2

### ISSUE THREAD

**Issue by Crisfole** [StackExchange/dapper-dot-net#293]
I've just realized my issue:

The Dapper.Contrib documentation says: "As with dapper, all extension methods assume the connection is already open, they will fail if the connection is closed. "

Since the first half of that statement was false, I assumed the full statement was false. (Dapper can and will open a closed connection on your behalf).  *However* they're independent statements.  I recommend the documentation be updated to "Unlike Dapper, these methods assume the connection is already open, and they wlil fail if the connection is closed." it will make people pay attention to the statement.

**-------- EDIT -------**

I just started playing with Dapper.Contrib for some of my simpler CRUD needs.  Everything seems to be working *except* inserts, which throw the following exception. (Stack Trace starts in Dapper.Contrib). The insert *does* successfully happen, but the returning of the identity value fails.

```
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException: Cannot convert null to 'int' because it is a non-nullable value type
   at CallSite.Target(Closure , CallSite , Object )
   at SqlServerAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert) in ~\DapperContrib.cs:line 549
   at Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout, ISqlAdapter sqlAdapter) in ~\DapperContrib.cs:line 252
```

My class looks like this:

```csharp
using LocalCopyOf.Dapper.Contrib.Extensions;
using Newtonsoft.Json;

namespace MySite.Models {
    [Table("section_header")]
    public class SectionHeader {
        [Key]
        public int? my_pk { get; set; }

        public string description { get; set; }

        public int? sort_key { get; set; }

        public string url { get; set; }

        public string role_needed { get; set; }

        [Computed]
        [JsonProperty("link_lines")]
        public Link[] Links { get; set; }

        public LinkHeader WithLinks(Link[] lines) {
            var header = (Link) this.MemberwiseClone();
            header.Links = lines;
            return header;
        }
    }
}
```

The table itself is defined as such:

```sql
CREATE TABLE [dbo].[section_header](
	[my_pk] [int] IDENTITY(1,1) NOT NULL,
	[description] [varchar](100) NULL,
	[sort_key] [int] NULL,
	[access_fk] [int] NULL,
	[url] [varchar](2000) NULL,
	[image_url] [varchar](2000) NULL,
	[internal] [bit] NULL,
	[role_needed] [varchar](50) NULL
) ON [PRIMARY]
```

There are various and sundry unneeded fields.

**Comment by johandanforth** [comment]
Contrib should actually handle connections just like dapper. Was the closed connection the issue? The error looks different.

**Comment by anton89** [comment]
I think it is because you use nullable property in key
public int? my_pk { get; set; }

when it is actually not nullable in database
[my_pk] [int] IDENTITY(1,1) NOT NULL,

**Comment by johandanforth** [comment]
That is what I think also

**Comment by Crisfole** [comment]
We have zero pks in the database, so i used `null` to distinguish between 'has been saved' and 'has not been saved'.  The closed connection *was* the issue.  Opening it before I tried `Insert` fixed the problem.

You can easily test that the nullability isn't a problem by doing this (Linqpad Code, swap out the Dump line for the commented out section if you need to):
```csharp
public void Main() {
	PropertyInfo p = typeof (Test).GetProperty("Pk");
	var test = new Test();
	p.SetValue(test, 3, null);
	test.Dump(); // Console.Write(test);
}

// Define other methods and classes here
public class Test {
     public int? Pk { get; set; }
}
```

I remember seeing code in the Dapper-dot-net repo that checks a connections openness and saves it before running code, then restores the connection to that state before returning.  If something like that were done in Dapper.Contrib this wouldn't be an issue...I'll have to see if I have time to issue a PR

**Comment by johandanforth** [comment]
Ok, I see what mean, The statement about connections having to be open is old, and dapper behaviour has changed since then I believe. The Insert() method in Contrib failes on a closed sqlserver-connection when it tries to get the new id of the inserted row. I'll fix this.

**Comment by johandanforth** [comment]
Ok, contrib insert now handles closed connection. I pretty much used the code from you @Crisfole , thanks for the report.

**Comment by tugbayatilla** [comment]
i just started playing dapper and i faced the issue you mentioned. i did not use identity column on table and tried to insert then i get "Cannot convert null to 'int' because it is a non-nullable value type" error. I traced the isue and found that dapper tried to return @@Identity Id as a result of Insert operation but it returns null because there is no identity insertion! 

the question is that do i have to use identity field? no. i don't. what is the solution then? 
thanks guys.

**Comment by Crisfole** [comment]
Hi @tugbayatilla this problem is not the same. I suggest you open a new complain. My code *did* have an identity field.

**Comment by tugbayatilla** [comment]
Hi @Crisfole , you are right, it is not the same. what i want to say that i was getting same errror message. yes i will open a new issue.
