### ISSUE TITLE
Tag published versions

### ISSUE THREAD

**Issue by diegobfernandez** [StackExchange/dapper-dot-net#297]
To easy finding the respective source for a published version.

**Comment by jorrit** [comment]
+1

**Comment by NickCraver** [comment]
This is certainly a reasonable request - I'm going to try and find time to look at Appveyor for builds when I'm with Marc next week. We may be able to do a little something here mostly automatically, and similar with changelogs.

**Comment by NickCraver** [comment]
@mgravell took care of this one - closing out.
