### ISSUE TITLE
Dapper.Contrib Update clashes with SQLite Update

### ISSUE THREAD

**Issue by shrayasr** [StackExchange/dapper-dot-net#300]
`SQLiteConnection` exposes an `Update` event to handle the update events. This clashes with Dapper.Contrib's `Update`. 

Here is the smallest piece of code with which I was able to reproduce the error

```Csharp
using System;
using Dapper;
using Dapper.Contrib.Extensions;
using System.Data.SQLite;

namespace LearningDapper
{
    [Table ("employee")]
    public class Employee
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }

    class Program
    {
        static void Main(string[] args)
        {
            SQLiteConnection _conn = new SQLiteConnection(@"Data Source=learningdapper.db");
            _conn.Open();

            _conn.Insert<Employee>(new Employee {  Name = "foo" });
            _conn.Update(new Employee { Id = 13, Name = "foobar" });

            _conn.Close();
            Console.ReadKey();
        }
    }
}
```

The error during build is: `The event 'System.Data.SQLite.SQLiteConnection.Update' can only appear on the left hand side of += or -=`

And it doesn't complain if I change the line and be explicit like so: 

```Csharp
_conn.Update<Employee>(new Employee { Id = 13, Name = "foobar" });
```

At the least, we should probably add this in the README for clarity sakes.

**Comment by johandanforth** [comment]
True, feel free to add a note in the readme if you like and make a PR. Maybe add something about how to work around it, like ``SqlMapperExtensions.Update(_conn, new Employee { Id = 13, Name = "foobar" });``
