### ISSUE TITLE
breakdown when it tris to 'select @@IDENTITY id' that primary key is Guid

### ISSUE THREAD

**Issue by jihewei** [StackExchange/dapper-dot-net#307]
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException was unhandled
  HResult=-2146233088
  Message=无法将 null 转换为“int”，因为后者是不可以为 null 的值类型
  Source=Anonymously Hosted DynamicMethods Assembly
  StackTrace:
       在 CallSite.Target(Closure , CallSite , Object )
       在 System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
       在 SqlServerAdapter.Insert(IDbConnection connection, IDbTransaction transaction, Nullable`1 commandTimeout, String tableName, String columnList, String parameterList, IEnumerable`1 keyProperties, Object entityToInsert) 位置 d:\egna projekt\dapper-dot-net\Dapper.Contrib\SqlMapperExtensions.cs:行号 655
       在 Dapper.Contrib.Extensions.SqlMapperExtensions.Insert[T](IDbConnection connection, T entityToInsert, IDbTransaction transaction, Nullable`1 commandTimeout) 位置 d:\egna projekt\dapper-dot-net\Dapper.Contrib\SqlMapperExtensions.cs:行号 299

**Comment by johandanforth** [comment]
The Contrib extensions does not support guid/uniqeidentifier as primary id, but I'm looking at it. The id has to be an integer now.

**Comment by jihewei** [comment]
Thx, any plan for it? why not?

**Comment by johandanforth** [comment]
I'm looking at it but it's not that easy because different databases doesn't handle guid id the same way. No promises, but I will investigate :)
