### ISSUE TITLE
How to make fuzzy query using dapper.net?

### ISSUE THREAD

**Issue by leee66** [StackExchange/dapper-dot-net#309]
Dear, 
I need to do fuzzy query using dapper.net. Please see the following code. After I executed the following code, I got the 0 record. But in fact, there are many records in the database. How should I revise the following code for receiving the correct result? 
Look forward to your soon reply. Thanks in advance.
using (var conn = new SqlConnection(ConnectionString.DB_SELECT))
            {
                conn.Open();
                DynamicParameters p = new DynamicParameters(new { PassengerName = "Han" });
                return conn.Query<string>("select orderno from tblorders WHERE PassengerName LIKE '%@PassengerName%'", p).ToList();
            }

**Comment by mgravell** [comment]
Dapper simply wraps ADO.NET and TSQL; in ADO.NET and TSQL the way to do
that is:

    WHERE PassengerName LIKE '%' + @PassengerName + '%'

and this remains the case in dapper. This isn't a dapper concern.

On 3 July 2015 at 03:04, leee66 <notifications@github.com> wrote:

> Dear,
> I need to do fuzzy query using dapper.net. Please see the following code.
> After I executed the following code, I got the 0 record. But in fact, there
> are many records in the database. How should I revise the following code
> for receiving the correct result?
> Look forward to your soon reply. Thanks in advance.
> using (var conn = new SqlConnection(ConnectionString.DB_SELECT))
> {
> conn.Open();
> DynamicParameters p = new DynamicParameters(new { PassengerName = "Han" });
> return conn.Query("select orderno from tblorders WHERE PassengerName LIKE
> '%@PassengerName%'", p).ToList();
> }
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/309>.
>



-- 
Regards,

Marc
