### ISSUE TITLE
Query<dynamic>(...) returns 'ID' property/column as 'id'

### ISSUE THREAD

**Issue by itslittlejohn** [StackExchange/dapper-dot-net#318]
I have a simple query that I'm performing:

`var result = conn.Query("MY_StoredProc", new { param1 = myVal }, commandType: CommandType.StoredProcedure);`

When the SP is executed in SSMS, it returns a few columns `ID, Col1, MyVal, Etc`. 

Looping over the result, I can access each property as `item.Col1` or `item.MyVal`, but when I try to read the `ID` property, dapper downcases it to `id`, so this works: `item.id`, but not this: `item.ID`. This seems like a bug to me. Has anyone else reproduced this against .NET 4.5.1?

**Comment by NickCraver** [comment]
I can't reproduce this on 4.5.2 or .Net 4.6...but I'm also unaware of why this would be broken on either. I think it's more likely a previous Dapper bug that's since been resolved was the likely culprit. Can you please try and see if you can still reproduce?

**Comment by itslittlejohn** [comment]
@NickCraver Thanks for checking in on this! Perhaps oddly, using the latest, I am also not able to reproduce this, so consider it closed. :)
