### ISSUE TITLE
"No columns were selected" when there is no result returned by a query

### ISSUE THREAD

**Issue by Asken** [StackExchange/dapper-dot-net#327]
There is no way of telling how many results or it's missing a "TryRead". The below code fails with "No columns were selected" if nothing is returned from the procedure.

    var results = conn.QueryMultiple(this.Procedure, param: p, commandType: CommandType.StoredProcedure);

    // Procedure should return the record so we should set Data
    var recordSet = results.Read<object>();
    ...

**Comment by NickCraver** [comment]
Do you have a more complete repro case? I can't really follow exactly what's failing here. It's a stored procedure that had no return? Is it returning parameters or result sets? Are there no result sets? A complete example I can setup and work-around would be very helpful.

**Comment by c5racing** [comment]
I am having the same issue.  My test sproc looks like this:

CREATE PROCEDURE [dbo].[Test]
AS 
SELECT TOP 0 * FROM TEST TABLE
SELECT TOP 0 * FROM TEST2 TABLE
GO

My Dapper code looks like this:

var query = connection.QueryMultiple("Test", commandType: CommandType.StoredProcedure);
var tests = query.Read<TestResponseModel>();

As soon as I do the query.Read, Dapper throws a "No columns were selected" execption.

**Comment by NickCraver** [comment]
@c5racing I have to ask...what's the goal of that procedure? I'm trying to understand the actual use case here to make sure any fix is appropriate.

**Comment by Asken** [comment]
The use case is when you have an sp that returns 0 or more results. The
application code has no way of knowing.

It should allow for the same code to be used to both execute-only and
resultset queries.

**Comment by NickCraver** [comment]
@Asken Okay thanks, that makes perfect sense - taking a look now.

**Comment by NickCraver** [comment]
@Asken  which version of Dapper are you running? I'm unable to repro on current code. Test case:

```C#
[Fact]
public void Issue327_ReadEmptyProcedureResults()
{
    // Actually testing for not erroring here on the mapping having no rows to map on in Read<T>();
    connection.Execute(@"
CREATE PROCEDURE #TestEmptyResults
AS
SELECT Top 0 1 Id, 'Bob' Name;
SELECT Top 0 'Billy Goat' Creature, 'Unicorn' SpiritAnimal, 'Rainbow' Location;");
    var query = connection.QueryMultiple("#TestEmptyResults", commandType: CommandType.StoredProcedure);
    var result1 = query.Read<Issue327_Person>();
    var result2 = query.Read<Issue327_Magic>();
    result1.Any().IsFalse();
    result2.Any().IsFalse();
}

public class Issue327_Person
{
    public int Id { get; set; }
    public string Name { get; set; }
}

public class Issue327_Magic
{
    public string Creature { get; set; }
    public string SpiritAnimal { get; set; }
    public string Location { get; set; }
}
```

**Comment by NickCraver** [comment]
Closing this out due to inactivity - if you can still repro on the current version please ping here for a re-open so we can dig deeper.

**Comment by codenaked** [comment]
I'm not sure if my issue is related to the original posters, but this would result in the given error:

```
CREATE PROCEDURE #TestEmptyResults
AS
BEGIN
    IF 1=0
        RETURN
    SELECT Top 0 1 Id, 'Bob' Name;
    SELECT Top 0 'Billy Goat' Creature, 'Unicorn' SpiritAnimal, 'Rainbow' Location;
END
```

My use case is that we validate some parameters before performing the select. If they are invalid then we simply return out of the stored proc. On the client side Dapper is not getting back *any* information about the potential recordset; no data rows and no schema information. Because the latter is missing, it's understandable that it would throw the given error.

I was hoping to be able to do something like this:

```
var query = connection.QueryMultiple("#TestEmptyResults", commandType: CommandType.StoredProcedure);
if (query.ResultCount < 2)
    return null;
var result1 = query.Read<Issue327_Person>();
var result2 = query.Read<Issue327_Magic>();
//... return something that uses result1 and result2;
```

My work around right now is to alter my stored procs to select empty rows of the same type using `TOP 0` like:

```
IF 1=0
BEGIN
   SELECT TOP (0) 0 AS MyInt, '' AS MyVarchar
   RETURN
END

SELECT MyInt, MyVarchar
FROM -- Complex query
```

I'd prefer to not have to do this, since I have to make sure both SELECTs have the same columns, but I understand/accept the reason it throws.

**Comment by mgravell** [comment]
I don't think you can ever query something like `ResultCount` - you can
just ask "is there data?". We *could* try to expose that - it is already
supported for the end scenario, but; this isn't a common / intended usage.
I kinda agree it should at least work, though.

On 1 February 2016 at 22:43, Tom Goff <notifications@github.com> wrote:

> I'm not sure if my issue is related to the original posters, but this
> would result in the given error:
>
> CREATE PROCEDURE #TestEmptyResults
> AS
> BEGIN
>     IF 1=0
>         RETURN
>     SELECT Top 0 1 Id, 'Bob' Name;
>     SELECT Top 0 'Billy Goat' Creature, 'Unicorn' SpiritAnimal, 'Rainbow' Location;
> END
>
> My use case is that we validate some parameters before performing the
> select. If they are invalid then we simply return out of the stored proc.
> On the client side Dapper is not getting back *any* information about the
> potential recordset; no data rows and no schema information. Because the
> latter is missing, it's understandable that it would throw the given error.
>
> I was hoping to be able to do something like this:
>
> var query = connection.QueryMultiple("#TestEmptyResults", commandType: CommandType.StoredProcedure);
> if (query.ResultCount < 2)
>     return null;
> var result1 = query.Read<Issue327_Person>();
> var result2 = query.Read<Issue327_Magic>();
> //... return something that uses result1 and result2;
>
> My work around right now is to alter my stored procs to select empty rows
> of the same type using TOP 0 like:
>
> IF 1=0
> BEGIN
>    SELECT TOP (0) 0 AS MyInt, '' AS MyVarchar
>    RETURN
> END
>
> SELECT MyInt, MyVarchar
> FROM -- Complex query
>
> I'd prefer to not have to do this, since I have to make sure both SELECTs
> have the same columns, but I understand/accept the reason it throws.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/327#issuecomment-178237062>
> .
>



-- 
Regards,

Marc

**Comment by Mithrandire** [comment]
Hello, All.

I've just bumped into the same issue. So is altering SP to not return empty result sets the only way to deal with `[InvalidOperationException: No columns were selected]` when using Read<T> especially with QueryMultiple?

Thank you and sorry for bringing up old topics.

**Comment by hopetechnologies** [comment]
Hello All,
If the SP returns variable result sets then this issue is really bothering, especially in the QueryMultiple case.
Request: A property like 'HasResult' to check if it has result will be helpful to avoid getting "The reader has been disposed; .... " error.

**Work around**: Instead of returning empty value from SP I chose to handle the error and ignore if it is the System.ObjectDisposedException with Source as 'Dapper' in my code.

Thanks.

**Comment by FotisMylonas** [comment]
I'm also facing the same issue. I would like to be able to check if stored procedure returned any results at all, before trying to do SqlMapper.GridReader.Read in the "QueryMultiple" scenario
Perhaps it would help if the existing property SqlMapper.GridReader.IsConsumed would be set to true, if no results exist at all.
Using Dapper 1.50.7

**Comment by engineer-andrew** [comment]
I've run up against this same problem. We have a stored procedure that only executes under certain conditions. The first part checks whether those conditions are met and if they aren't a simple return statement ends execution. When that happens, Dapper is throwing the same "No columns were selected" exception. I don't care for the way the stored procedure is designed, but I don't have much control over that. Is there any option to make some option to check whether records exist available in the future?

Using Dapper 1.60.6

**Comment by AndiKleini** [comment]
I had the same issue and for a Hotfix, which I don't want to remain too long in the system because of performance considerations, I accessed the HasRows field via reflection:
 private bool HasRows(GridReader reader)
        {
            SqlDataReader internalReader = (SqlDataReader)typeof(GridReader).
                GetField
                ("reader",
                System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
                .GetValue(reader);
            return internalReader.HasRows;
        }
This solved the issue but is not acceptable for a long term solution.
I think it would be great if this HasRows Property of the underlying SQLDataReader could be exposed.

**Comment by KamranShahid** [comment]
> I had the same issue and for a Hotfix, which I don't want to remain too long in the system because of performance considerations, I accessed the HasRows field via reflection:
> 
> ```
>     private bool HasRows(GridReader reader)
>     {
>         SqlDataReader internalReader = (SqlDataReader)typeof(GridReader).
>             GetField
>             ("reader",
>             System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
>             .GetValue(reader);
>         return internalReader.HasRows;
>     }
> ```
> 
> This solved the issue but is not acceptable for a long term solution.
> I think it would be great if this HasRows Property of the underlying SQLDataReader could be exposed.

I agreed with this that has rows should be there in dapper as well

**Comment by knight1219** [comment]
> I had the same issue and for a Hotfix, which I don't want to remain too long in the system because of performance considerations, I accessed the HasRows field via reflection:
> 
> ```
>     private bool HasRows(GridReader reader)
>     {
>         SqlDataReader internalReader = (SqlDataReader)typeof(GridReader).
>             GetField
>             ("reader",
>             System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
>             .GetValue(reader);
>         return internalReader.HasRows;
>     }
> ```
> 
> This solved the issue but is not acceptable for a long term solution. I think it would be great if this HasRows Property of the underlying SQLDataReader could be exposed.

Its 2022 and this 9 lines of code saved me from having to change a 30 year old COBAL stored procedure in DB2 (and every app that's been built in the past 20 that uses it). This should really be exposed via Dapper.

**Comment by szymonpiekny** [comment]
The issue still exists in 2.0.123 version. Could you add some field to check the fetched result is null ex. NullFetched?

**Comment by KamranShahid** [comment]
> > I had the same issue and for a Hotfix, which I don't want to remain too long in the system because of performance considerations, I accessed the HasRows field via reflection:
> > ```
> >     private bool HasRows(GridReader reader)
> >     {
> >         SqlDataReader internalReader = (SqlDataReader)typeof(GridReader).
> >             GetField
> >             ("reader",
> >             System.Reflection.BindingFlags.NonPublic | System.Reflection.BindingFlags.Instance)
> >             .GetValue(reader);
> >         return internalReader.HasRows;
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > This solved the issue but is not acceptable for a long term solution. I think it would be great if this HasRows Property of the underlying SQLDataReader could be exposed.
> 
> Its 2022 and this 9 lines of code saved me from having to change a 30 year old COBAL stored procedure in DB2 (and every app that's been built in the past 20 that uses it). This should really be exposed via Dapper.
Weldon,
Maintaining legacy codes is an artwork. doing this since last 15+ years on different places :)
