### ISSUE TITLE
Assembly not signed in nuget package

### ISSUE THREAD

**Issue by roji** [StackExchange/dapper-dot-net#331]
It seems that the Dapper.dll distributed in the 1.42 nuget package (net45) isn't signed. This is obviously  problematic for consuming the dapper nuget from signed projects.

**Comment by mgravell** [comment]
This is intentional. You may want to use Dapper.StrongName instead

**Comment by roji** [comment]
Ah, many thanks.

You may want to update your github README.md to let people know about the different nuget packages.

Out of curiosity, any specific reason for to have two packages, for signed and unsigned assemblies? Any disadvantage in always distributing signed assemblies?

**Comment by probel-software** [comment]
@roji, the answer lies [here](http://stackoverflow.com/questions/25059356/dapper-tvp-assembly-is-does-not-have-a-strong-name)
