### ISSUE TITLE
support in Monotouch

### ISSUE THREAD

**Issue by micuentadecasa** [StackExchange/dapper-dot-net#334]
I need your dapper to work in mono touch, but it seems that there is some problem with ILGeneration or similar, anyone of you know how to make it work in an Xamarin IOS app?

**Comment by mgravell** [comment]
iOS doesn't like IL generation at all, IIRC. What exactly is the error /
behaviour? Something about AOT? If so: it could need significant work to
make it work on iOS. So: what happens? What are you seeing?

Marc

**Comment by micuentadecasa** [comment]
Hi Marc, I have tested in different kind of projects that I summarize:
- Xamarin Gtk - it Works great
- Xamarin IOS7 classic + IOS8 Unified API -> I can add the package - compile without errors after adding the package but I can't not write "using Dapper", it seems that the package is not in the Project, in addition I can't use any of the extenders of Dapper, so no error appears but I can't use Dapper.

**Comment by NickCraver** [comment]
@micuentadecasa Any update on this? I know that ecosystem is changing a lot and some metaprogramming may land in the next few releases I'm curious how everyone is approaching the issue.

**Comment by micuentadecasa** [comment]
Hi @NickCraver , I got no news from this issue. What do you mean with metaprogramming?

**Comment by mgravell** [comment]
Metaprogramming in this context (it has other meanings) is apps that write
themselves at runtime - in this case, by IL generation. Mobile platforms
often don't like that. Pre-generation is an alternative strategy, but is a
significant code departure.

Marc

**Comment by micuentadecasa** [comment]
Hi @mgravell  and @NickCraver , can I expect some help from Stack Exchange in this issue ? I don't have enough knowledge to solve it.

**Comment by NickCraver** [comment]
@micuentadecasa honestly we're lacking on time but more-so expertise on Mono here. That being said, Dapper supports DNX/CoreCLR in 1.41-beta5 and will in the next version as well (it's missing from the 1.42 build). That's where Microsoft is headed on Mono support - but I'm not sure where the rest of the ecosystem there stands.

**Comment by micuentadecasa** [comment]
Thanks Nick, I will try in next versión.

**Comment by gentledepp** [comment]
Hi guys! Any update on this? Has anyone got dapper to work on Mono Touch yet?
