### ISSUE TITLE
SqlGeometry query fails

### ISSUE THREAD

**Issue by steveoh** [StackExchange/dapper-dot-net#342]
I have a `SqlGeometry` and the following query

``` sql
SELECT SUM(CONVERT(INT, p.Shape.STIntersects(@geometry))) 
FROM [POLY] p 
WHERE p.TypeDescription = @category AND p.Project_Id = @id
```

using dapper in this way

``` csharp
await connection.QueryAsync<int>(query, new {id, geometry, category = model.Category});
```

I get this error. 

``` csharp
System.NullReferenceException: Object reference not set to an instance of an object.
   at Dapper.SqlMapper.d__147`1.MoveNext() in D:\Dev\dapper-dot-net\Dapper NET45\SqlMapperAsync.cs:line 112
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by mrinalkamboj** [comment]
Is the issue only with Async call or the standard `Query<int>` lead to similar error

**Comment by steveoh** [comment]
It's a sql server 2014 db and yes it was happing with non asyc queries also. Recently I added an assembly binding 

```xml
<dependentAssembly>
        <assemblyIdentity name="Microsoft.SqlServer.Types" publicKeyToken="89845dcd8080cc91" culture="neutral" />
        <bindingRedirect oldVersion="10.0.0.0" newVersion="11.0.0.0" />
      </dependentAssembly>
```

which solved a different issue. They might be related?

**Comment by mrinalkamboj** [comment]
This is known issue then, I have encountered it using SqlGeography, that's why I was keen for exception using Query instead of Async call, as that provide much more relevant information than above mentioned Task related wrapper exception, where Inner exception is much more valid

**Comment by steveoh** [comment]
Is there another issue to reference then?

**Comment by NickCraver** [comment]
@steveoh which version of Dapper were you running here? Can you repro on the latest 1.50? If so I'd really appreciate a current stacktrace.
