### ISSUE TITLE
Dapper.Contrib Should use OUTPUT instead of SCOPE_IDENTITY

### ISSUE THREAD

**Issue by johandanforth** [StackExchange/dapper-dot-net#355]
Currently Dapper.Contrib uses `SCOPE_IDENTITY` for returning id of MsSql inserts, but should use `OUTPUT INSERTED` instead, according to this support statement from Microsoft https://support.microsoft.com/en-us/kb/2019779

I'm going to look at that.

**Comment by oreleraki** [comment]
Hi, I'm stumbling the same issue, after research i arrived to here. It appears neither v1.* nor v2.* versions has this fix, which is very important when using non Integer Keys. Are there any plans to put this fix into v1.* and v2.* ?
