### ISSUE TITLE
Unexpected singleton instances in ProxyGenerator.GetInterfaceProxy<T>()

### ISSUE THREAD

**Issue by longshine** [StackExchange/dapper-dot-net#361]
Hi~

I find that in the following line in `Tests.GetAll()` test in *Dapper.Contrib.Tests* project:

```csharp
var iusers = connection.GetAll<IUser>().ToList();
```

All of the queried items in `iusers` are the **same object**.
![singleton-in-proxy-generator-1](https://cloud.githubusercontent.com/assets/1046071/10637413/1c1d4f9e-7838-11e5-90ca-35ea527cd355.jpg)
![singleton-in-proxy-generator-2](https://cloud.githubusercontent.com/assets/1046071/10637449/5fc4cdc6-7838-11e5-9429-19aeedc45be5.jpg)
`Object.ReferenceEquals(iusers[0], iusers[9])` -> `true`

Then I notice that in `SqlMapperExtensions.ProxyGenerator` class, it stores a generated instance for each interface type only at the first time, and returns it afterwards, making it a singleton object for each type.

```csharp
public static T GetInterfaceProxy<T>()
{
    Type typeOfT = typeof(T);

    object k;
    if (TypeCache.TryGetValue(typeOfT, out k))
    {
        return (T)k;   // returns the instance created before
    }

    // generate proxy type and instance and store
}
```

 May it be a bug or a by design feature? As my suggestion, should it stores the generated types instead of the instance objects as the following code?

```csharp
static readonly Dictionary<Type, Type> TypeCache = new Dictionary<Type, Type>();

public static T GetInterfaceProxy<T>()
{
    Type proxyType = null;

    if (!TypeCache.TryGetValue(typeof(T), out proxyType))
    {
        // generate proxy type
    }

    // create a new proxy instance
    return Activator.CreateInstance(proxyType);
}
```

**Comment by johandanforth** [comment]
Ok @longshine I'll have to look at this a bit before I answer. I wrote the proxy way back, and the GetAll didn't exist back then. "Looks" a bit smelly though.

**Comment by johandanforth** [comment]
You were very right @longshine. Fixed in and created a new PR for this. Also added a small test.
commit: https://github.com/StackExchange/dapper-dot-net/commit/4752a21208be2cd165239c456258e81abf820718

**Comment by longshine** [comment]
Thanks~
