### ISSUE TITLE
TransactionScope not being honored

### ISSUE THREAD

**Issue by steveoh** [StackExchange/dapper-dot-net#366]
````csharp
var connectionString = ConfigurationManager.ConnectionStrings["db"].ConnectionString;
using (var connection = new SqlConnection(connectionString))
{
 try
 {
     await connection.OpenAsync();
 }
 catch (SqlException)
 {
     return Negotiate.WithReasonPhrase("Database Error")
         .WithStatusCode(HttpStatusCode.InternalServerError)
         .WithModel("Unable to connect to the database.");
 }
 
 using (var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled))
 {
  ...
 }
}
````

If I explicitly open the connection to the database, the transaction scope is ignored. If I let dapper open the connection the transaction is honored. Is this an ADO.NET thing or a dapper thing?

**Comment by NickCraver** [comment]
This is an ADO.Net thing, the transaction scope applies to connections (or transactions) opened inside it. So you can open the connection yourself, but you need to do it inside the `TransactionScope` using for it to do what you want here :)

**Comment by steveoh** [comment]
Ok, so the transactionscope should wrap the sqlconnection. Cool thanks! I assumed that the transaction would need to be inside of the connection.
