### ISSUE TITLE
Using Like Operator in Dapper SQL Query

### ISSUE THREAD

**Issue by mrinalkamboj** [StackExchange/dapper-dot-net#373]
A standard Sql query using `like` for the wild card comparison:

`Select * from Table where Column like '%Value%'`

Works using Dapper when supplied like this:

`"Select * from Table where Column like '%" + @Value + "%'"`

but it doesn't work when I supply it as one single string like:

`"Select * from Table where Column like '%@Value%'"`

Not sure regarding this behavior, since all other standard an operators like `= or <>` is used, work as a single query, as follows:

`"Select * from Table where Column = @Value"`

As expected Value is provided as an anonymous parameter

**Comment by programcsharp** [comment]
You need to put the % inside the var, like:

```sql
SELECT * FROM Table WHERE Column LIKE @value
```

```c#
string value = "%value%";
```

**Comment by mrinalkamboj** [comment]
@programcsharp I have tried the solution that you have suggested, it needs modification as follows:

 `new { value = "%"+value+"%" }`

Otherwise it will take `"%value%"` as a string replacement, will not fill values

**Comment by mgravell** [comment]
Basically, it works *exactly* like it would if you did in in SSMS, a stored procedure, or anything else that uses TSQL. The instruction:

    Select * from Table where Column like '%@Value%'

does not use the parameter - it looks for something contains the literal value `@Value`. You need to either this in the SQL, i.e.:

    Select * from Table where Column like '%' + @Value + '%'

or in the calling code, i.e.:

    var rows = conn.Query<Foo>(
        "Select * from Table where Column like @value",
        new { value = "%" + searchTerm  "%" }).ToList();

This isn't a dapper issue, and the same will occur in any ADO.NET / SQL usage. Parameters are not replaced in-place.

**Comment by mrinalkamboj** [comment]
@mgravell thanks for the explanation, it is clear now

**Comment by TopGuo** [comment]
# 👎 👎  I dot't find anything. when i use dapper "like" query.
eg:
![image](https://user-images.githubusercontent.com/30146744/44763189-a528a980-ab7c-11e8-8ed0-b787a864337b.png)
but the same sql, i can find when i use t-sql.

**Comment by mgravell** [comment]
@TopGuo  I think you should have created that as a new issue, but... Taking a look, that seems fine: you are using a parameter appropriately, etc. Are you saying that `rows` has zero rows when you expect more? And that the exact same query works fine via raw ADO.NET?

**Comment by v1adimirrr56** [comment]
Dapper doesn't work, if searchTerm = %

var rows = conn.Query<Foo>(
    "Select * from Table where Column like @value",
    new { value = "%" + searchTerm  "%" }).ToList();

How I can find Column with % charachter?

**Comment by mgravell** [comment]
@v1adimirrr56  that's not Dapper - that's simply how `LIKE` works - to look for the `%` character, you need to define an `ESCAPE` token, and then use that to tell it that which parts are literals. To put that more clearly with an example, if I want to use `'!'` as the escape character then `!%` means "the literal `%`", and the following returns one row only:

``` sql
-- dummy table
declare @foo table (val nvarchar(20) not null)
insert @foo values ('abc'),('d%f')

-- query using LIKE with ESCAPE
select val from @foo
where val  LIKE '%!%%' ESCAPE '!'
```

Here the leading and trailing `%` are wildcards, and the central `!%` is the literal `%`.

You can use a query with `ESCAPE` in it from Dapper just like normal, although you'd need to do something like:


``` c#
var rows = conn.Query(
"Select * from Table where Column like @value escape '!'",
new { value = "%" + searchTerm.Replace("%","!%") + "%" }).ToList();
```

Obviously pick your own escape character here - don't rely on `!` - it needs to be something that you don't want to search for.

**Comment by billytukija** [comment]
This works perfectly...
var rows = conn.Query<Foo>(
    "Select * from Table where Column like @value",
    new { value = "%" + searchTerm  "%" }).ToList();

**Comment by emrests** [comment]
> This way is too simple and works perfectly.
> 
> var store = await conn.QueryFirstOrDefaultAsync(@"Select * From Store Where code = @code And code Like @code ", new { code = code + "%" });

this is not:
like '%word%'
this is 
like 'word%'  

both are not the same

**Comment by rajkananirk** [comment]
Like simple query is : https://laratuto.com/how-do-you-do-a-like-statement-in-sql/
