### ISSUE TITLE
"Mapping" from single database table to class composed of distinct entities

### ISSUE THREAD

**Issue by adaam2** [StackExchange/dapper-dot-net#379]
This has already been discussed and a pull request had been lodged but I don't think it made it into the Dapper core: https://github.com/StackExchange/dapper-dot-net/pull/65

I know that this was a while ago, but is there way to acheive this using the most up to date version of Dapper? I am querying a single database table, however in my POCOs they follow a nested (composite) structure with some columns in the original table being represented by child classes (e.g. a single column "LanguageISO" is represented by the "Language" class)

Had a quick look around the documentation on mapping and couldn't find anything obvious relating to this and didn't know whether the mapping functionality was the right thing to be looking at.

Thanks

Adam

**Comment by jamesholwell** [comment]
A simple way to do this is to create a new object which mimics your database table exactly, and then do a little more mapping after Dapper has done its work: not ideal, but should work quickly.

**Comment by adaam2** [comment]
@jamesholwell Could you provide a code example of how to perform this mapping post-Dapper?

**Comment by NickCraver** [comment]
Can you give me the layout of your table and objects? I can likely show you how to do this with Multi-map using your exact use case.

**Comment by adaam2** [comment]
Not in the office at the moment, but the structure of one of the tables is roughly..

ID Keyword TranslatedText LanguageISO ProjectName 

Where the class looks something like 

```
public class Translation {
	public int ID { get;set; }
	public string Keyword { get;set; }
	public string TranslatedText { get;set; }
	public Language Language { get;set; }
	public Project Project { get;set; }
}
public class Language {
	public string LanguageCode { get;set; } // LanguageISO in original table
	public string LanguageName { get;set; } // this will be retrieved later
}
public class Project {
	public string ProjectName { get;set; } // ProjectName in original table
}
```

**Comment by NickCraver** [comment]
If you could show me what the structure of the other tables looks like - I can definitely show exactly you how to do this in a single query. Making some assumptions though, it'd look like this:

```C#
var translations = conn.Query<Translation, Language, Project, Translation>(@"
SELECT t.ID, t.Keyword, t.TranslatedText, l.*, p.*
  FROM Translations t
       JOIN Languages l On t.LanguageISO = l.ISO
       JOIN Projects p On t.ProjectName = p.Name
 WHERE t.ID = @Id", 
 (t, l, p) => { 
    t.Language = l; 
    t.Project = p; 
    return t; 
 }, new { Id = 5 }, splitOn: "ID,ISO,Name");
```

**Comment by adaam2** [comment]
Hi Nick,

The Languages table is actually on a different database server entirely so that's not going to be possible ha! But I get the idea and will try this out on Monday morning!

n.b. there is no Project table, it is just a nvarchar field.

Thanks for your help!

**Comment by jamesholwell** [comment]
I'm late to the party, but what I was going to suggest was:

```C#
public class TranslationDto {
    public int ID { get;set; }
    public string Keyword { get;set; }
    public string TranslatedText { get;set; }
    public string LanguageISO  { get;set; }
    public string ProjectName { get;set; }
}

var translations = 
  conn.Query<TranslationDto>(/* sql */)
      .Select(dto => new Translation {
        ID = dto.ID,
        Keyword = dto.Keyword,
        TranslatedText = dto.TranslatedText,
        Language = new Language { LanguageCode = dto.LanguageISO },
        Project = new Project { ProjectName = dto.ProjectName }
      });
```

Apologies in advance for typos - writing without VS open.

**Comment by adaam2** [comment]
That's also very helpful! Thank you very much
