### ISSUE TITLE
Support for dynamic typecasting for IDbConnection.Query at runtime

### ISSUE THREAD

**Issue by saleem-mirza** [StackExchange/dapper-dot-net#390]
Current implementation two flavor of Query.

1. `Query(....)`, returns collection of dynamic objects.
2. `Query<T>(...)`

I'ld like third option which is more like

3. `Query(string query, ..., Type T)`
This should retrieve objets of type `T`, when type of `T` is unknown at compile time. This is more runtime version of `Query<T>(..)`

I have a unique requirement where I get typename at runtime and I have to manipulate objects of this type at runtime. This includes retrieving data from database etc.

let's say, I have to retrieve all customers from database. I get a string parameter with content "Customer" so I have to invoke query and typecast it to Customer. I don't want to use if..else or switch statement.

**Comment by NickCraver** [comment]
I think you may have missed this overload which already exists:

```C#
public static IEnumerable<object> Query(
    this IDbConnection cnn, 
    Type type, 
    string sql, 
    object param = null, 
    IDbTransaction transaction = null, 
    bool buffered = true, 
    int? commandTimeout = null, 
    CommandType? commandType = null)
```

Are you looking for something different than this offers? If so, can you clarify? Another option is to get the `Query<T>` method and create the generic for the type you have via [`MethodInfo.MakeGenericMethod`](https://msdn.microsoft.com/en-us/library/system.reflection.methodinfo.makegenericmethod(v=vs.110).aspx).

**Comment by saleem-mirza** [comment]
Indeed I overlooked this overload. This is what I was looking exactly.

Thank you @NickCraver  :+1:
