### ISSUE TITLE
Not able to set DefaultTypeMap.MatchNamesWithUnderscores

### ISSUE THREAD

**Issue by FlorianRainer** [StackExchange/dapper-dot-net#396]
On Release 1.42 i was able to set Dapper.DefaultTypeMap.MatchNamesWithUnderscores = true;
Now with Release 1.50-beta1 DefaultTypeMap is private and i can't change MatchNamesWithUnderscores any more.

Is there a new way to set MatchNamesWithUnderscores , or is the public on DefaultTypeMap missing?

**Comment by NickCraver** [comment]
`DefaultTypeMap` being private was a conversion oops, fixed by #411. If you grab the latest beta, you should be all set. I'm closing this out since I'm very confident it's resolved - please comment if not and we'll take a closer look!

**Comment by FlorianRainer** [comment]
Thanks a lot, i will do some testing next week.
