### ISSUE TITLE
Dapper.Contrib Update Fails

### ISSUE THREAD

**Issue by adamfisher** [StackExchange/dapper-dot-net#398]
After trying version 1.40 and 1.42, I am still unable to do update a database table using the Dapper.Contrib Update extension method. 

My method acquires an IDbConnection successfully but when it tries to do the update, it complains **Incorrect syntax near the keyword 'User'**. I am able to successfully use this update syntax with my other models and there doesn't appear to be anything glaringly different. I also tried querying for a record successfully and then passing it back to update presents the same issue. I suspect maybe something weird with data types? Grasping at straw at this point.

```chsarp
public int Update(User model)
{
    using (var db = ConnectionFactory.Current.CreateConnection(new DbContext()))
    {
        return db.Update(model) ? 1 : 0;
    }
}
```

Here is my model:

```csharp
[Table("User")]
    public class User
    {
        [Key]
        public long UserId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string UserIdType { get; set; }
        public string UserIdValue { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public string ZipCode { get; set; }
        public DateTime? DateOfBirth { get; set; }
        public string EmailAddress { get; set; }
        public string PhoneNumber { get; set; }
        public int? ApplicationId { get; set; }
        public DateTime CreatedOn { get; set; }
        public DateTime? ModifiedOn { get; set; }
        public int? CredentialType { get; set; }
    }
```

**Comment by tms** [comment]
`User` is a reserved word, so the generated SQL is invalid. I guess the table names should be escaped like the column names were in #336, but that introduces the other problem mentioned there of [forcing case sensitivity](https://github.com/StackExchange/dapper-dot-net/issues/336#issuecomment-157009155). Hmm…

**Comment by adamfisher** [comment]
Thank you! You gave me the idea of updating the table attribute on the model to be `[Table("[User]")]`and that worked! Added the brackets escaped it.
