### ISSUE TITLE
Move to .NET Platform Standard monikers

### ISSUE THREAD

**Issue by sebastienros** [StackExchange/dapper-dot-net#400]
c.f. https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md

Since RC1 all libraries should use the new monikers for the targets. Concretely it means choosing the minimum API set required. This change is critical to let other dependent libraries do the migration too (I have that is blocked on that for instance).

Practically it means the `project.json` files need to target `net40`, `net45` and `dotnet5.2`, unless you want to ditch the `dnx451` support and then you can use `dotnet5.4` instead of `dotnet5.2`. The pre-processor directives will also need to be updated.

I will try to create a PR for this to happen.

**Comment by mgravell** [comment]
Have you started already? I can probably take a hack at it...

On 18 November 2015 at 23:00, Sébastien Ros <notifications@github.com>
wrote:

> c.f.
> https://github.com/dotnet/corefx/blob/master/Documentation/project-docs/standard-platform.md
>
> Since RC1 all libraries should use the new monikers for the targets.
> Concretely it means choosing the minimum API set required. This change is
> critical to let other dependent libraries do the migration too (I have that
> is blocked on that for instance).
>
> Practically it means the project.json files need to target net40, net45
> and dotnet5.2, unless you want to ditch the dnx451 support and then you
> can use dotnet5.4 instead of dotnet5.2. The pre-processor directives will
> also need to be updated.
>
> I will try to create a PR for this to happen.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/400>.
>



-- 
Regards,

Marc

**Comment by sebastienros** [comment]
Haven't started, let me know.

**Comment by mgravell** [comment]
Feel free; my initial attempt to  update the tooling let to a lot of fail like below :( It is gone midnight here - I'm going to call it a night... "revert! revert!"

    D:\Dev\dapper-dot-net\artifacts\bin\Dapper\Release\Publish\approot\src\Dapper\pr
oject.json(30,9): Error: Microsoft.Dnx.Runtime.FileFormatException: Illegal char
acter '/' (Unicode hexadecimal 002F). ---> Microsoft.Extensions.JsonParser.Sourc
es.JsonDeserializerException: Illegal character '/' (Unicode hexadecimal 002F).

**Comment by mgravell** [comment]
OK, I think `dnu restore` is somehow finding a long-dead `project.json` from ... nowhere I can find. I'll do a `rd /s` and `git clone`.... sometimes you just need to nuke it from orbit - just to be sure.

**Comment by sebastienros** [comment]
Trying in parallel then

**Comment by sebastienros** [comment]
Compiled on my box for all platforms ... creating a PR

**Comment by NickCraver** [comment]
Merged in #402, closing out.
