### ISSUE TITLE
Insert<T>() in MySQL always return 0

### ISSUE THREAD

**Issue by hoquangthaiholy** [StackExchange/dapper-dot-net#404]
I have a problem about Insert(). When I use MSSQL for my DB. I inserted a record, this method return a long value, it is ID of new record. But in MySQL, I alway receive 0 from Insert method.

**Comment by johandanforth** [comment]
Could you please give some more info? How is the table defined with the id column? Can you paste some sample code?

**Comment by hoquangthaiholy** [comment]
I defined my table:

```sh
[Table("BaoQuan")]
    public class BaoQuan
    {
        [Key]
        public int id { get; set; }
        public string tenthbq { get; set; }
        [Computed]
        public int cntHopSo { get; set; }
        [Computed]
        public int cntHoSo { get; set; }
        [Computed]
        public int cntVanBan { get; set; }
    }
```
and then using Insert method

```sh
using(MySqlConnection con = new MySqlConnection(connectionString)){
     long i = con.Insert(new BaoQuan() { 
            tenthbq = "Tên phông",
            cntHopSo = 0,
            cntHoSo = 0,
            cntVanBan = 0 
    });
     ...
}
```
record insert successfully but still return 0

**Comment by johandanforth** [comment]
Looks good. How is your table defined in MySQL? CREATE TABLE .... and such? Is the ID column set in the database properly? Which version of MySQL are you running?

**Comment by hoquangthaiholy** [comment]
This is my table defined inMYSQL
```sh
CREATE TABLE `baoquan` (
  `id` int(10) unsigned NOT NULL AUTO_INCREMENT,
  `tenthbq` varchar(50) DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;
```
This is my MySQL information:
```sh
Server: 127.0.0.1 via TCP/IP
Server type: MySQL
Server version: 5.6.24 - MySQL Community Server (GPL)
Protocol version: 10
User: root@localhost
Server charset:  UTF-8 Unicode (utf8)
```

**Comment by johandanforth** [comment]
Thanks ill try to investigate this weekend. Unless someone beats me to it.

**Comment by hoquangthaiholy** [comment]
Please update nuget packge. Thanks

**Comment by johandanforth** [comment]
Will do as soon as I figure out how to get things to compile. I'm completely new to the DNX stuff. /cc @NickCraver I got a fresh install of vs2015 but obviously I need to update the sdk or something because I get thousands of errors because of missing .NET Platform 5.4 references. Tried using dnvm to update to 1.0.0-rc1-final but things still fail in VS... help? :D

**Comment by hoquangthaiholy** [comment]
i'm trying to compile from new source code. I hope everything should work. :D

**Comment by johandanforth** [comment]
Heh, good luck mate, I'm down to 30.000 error messages right now... I *so* need to read up on the new .NET dnx stuff. I thought I could install VS2015, open a solution and rock... :/

**Comment by henkmollema** [comment]
@johandanforth did you install the ASP.NET 5 RC1 tooling? -> https://get.asp.net/

**Comment by johandanforth** [comment]
No I did not! Must be it. Jeez, I feel old... been deep into customer projects this year and missed alot of the new stuff. Who moved my cheese!!? :D

**Comment by mgravell** [comment]
@Johan if only somebody who has felt this pain took the time to walk
through the new tools ;p

http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-1.html
http://blog.marcgravell.com/2015/11/the-road-to-dnx-part-2.html
http://blog.marcgravell.com/2015/11/the-road-to-dnxpart-3.html

On 25 November 2015 at 08:53, Johan Danforth <notifications@github.com>
wrote:

> No I did not! Must be it. Jeez, I feel old... been deep into customer
> projects this year and missed alot of the new stuff. Who moved my cheese!!?
> :D
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/404#issuecomment-159537735>
> .
>



-- 
Regards,

Marc

**Comment by johandanforth** [comment]
Ahh, will you marry me @mgravell  :D

**Comment by hoquangthaiholy** [comment]
Why did we upgraded to VS 2015 too soon? This make compiling more harder? :P

**Comment by mgravell** [comment]
@hoquangthaiholy technically, we don't need VS 2015 to build; just:

    git clone https://github.com/StackExchange/dapper-dot-net.git
    cd dapper-dot-net
    dnu restore
    dnu build Dapper --configuration release

;p

**Comment by NickCraver** [comment]
#410 actually broke a few things - which supports my wanting to add automated tests against Postgres and MySQL on Contrib (and hopefully later, Core...but that's much more work).

MySQL tests are now here: https://github.com/StackExchange/dapper-dot-net/commit/6ed2f3baa97b475291dd16106199021e6a6adff0 and we're looking at how to have them not break everyone who isn't running MySQL for the test suite. That'll happen before a master merge (as will connection string cleanup across all tests). If you're not running that test suite, my desire if for them to "skip" in the runner - and Appveyor will do that sanity testing for us if you don't have the various database servers installed locally.

Hang on, we're working to improve the state of affairs here :) I'll take a look at the `Insert<T, TKey>` and such which will better support MySQL (e.g. `Insert<tableType, long>`) as well...I just wanted a healthy and automated test suite before we attack that.

**Comment by johandanforth** [comment]
Ok, I'm going to sit back and let you guys iron things out for a bit and read up on the "dnx stuff" for a while. Looking at Marcs articles now (super), trying out dnu, dnvm and managed to build dapper just fine... just to learn that these tools will be replaced :) moving targets here... :D @NickCraver  or @mgravell  feel free to build a beta-package of Dapper.Contrib if you like until I learn my ways around dnx. Marc is co-owner of the nuget package.

BTW. There's a "compile" reference in ? `Dapper.Contrib/Project.json` which references `../Dapper/TypeExtension.cs` that I'm not sure why it's there:

  "compile": [
    "**/*.cs",
    "../Dapper/TypeExtensions.cs"
  ],

**Comment by hoquangthaiholy** [comment]
I compiled without any error. But I'm check File version: 1.40.0.0. Product version: 1.50.0-beta3.
I'm using Windows 10. Visual Studio 2015 Community Edition. Thanks @mgravell for shell scripts.

**Comment by tvkhoa17** [comment]
i hope you will do it.
