### ISSUE TITLE
explicitKey bug

### ISSUE THREAD

**Issue by itlizhi** [StackExchange/dapper-dot-net#418]
table using [explicitKey],first [update] then [insert],  the [ExplicitKey] not insert.
guess： [update<T>]  keyProperties.AddRange(explicitKeyProperties);

**Comment by johandanforth** [comment]
Can you plese provide some more info @itlizhi ? What database platform? Can you give some sample code to reproduce the error?

**Comment by itlizhi** [comment]
using sqlserver 2008 r2
![20151201095158](https://cloud.githubusercontent.com/assets/10509513/11490193/43b7449e-9811-11e5-955a-10507656cd07.png)

**Comment by johandanforth** [comment]
Which version of Dapper and Dapper.Contrib? I actually got the same error as you with the current Nuget version 1.44. I'll see if I can find the same bug in the current source. Might be a bug actually.

**Comment by itlizhi** [comment]
<package id="Dapper" version="1.42" targetFramework="net45" />
 <package id="Dapper.Contrib" version="1.44" targetFramework="net45" />

**Comment by johandanforth** [comment]
Thanks @itlizhi I think I found the problem yesterday and I will look at a fix this weekend. For some reason the `ExplicitKey` property is cached as an ordinary key in the `Update` extension method, which is wrong. That is why it works if `Insert` is called first. But I just had a glance at it yesterday, I'll look at it on saturday or sunday, unless someone beats me to it. It's easy to test and reproduce.
