### ISSUE TITLE
Dapper.Contrib references Dapper 1.50.0.0

### ISSUE THREAD

**Issue by janzakrzewskipl** [StackExchange/dapper-dot-net#419]
It seems that Dapper.Contrib 1.44 references Dapper 1.50.0.0. 
You can check that in DotPeek.
![dotpeek](https://cloud.githubusercontent.com/assets/6554775/11530437/f3b54510-98f4-11e5-8611-36168e49f527.JPG)

For that reason we get "An unhandled exception of type 'System.IO.FileNotFoundException' occurred in DapperTest.dll. Additional information: Could not load file or assembly 'Dapper, Version=1.50.0.0, Culture=neutral, PublicKeyToken=null' or one of its dependencies. The system cannot find the file specified." after we updated to Dapper.Contrib 1.44. 

The interesting part is that when exe application directly references Dapper.Contrib (and Dapper) everything seems to be fine. On the other hand when exe application doesn't have references to those packages, but instead it references some additional project (which uses Dapper.Contrib and Dapper) above exception appears.

I can attach an example later if you want.

**Comment by johandanforth** [comment]
Hi @janzakrzewskipl  Are you talking about the nuget version of Dapper.Contrib? Because if you get Dapper.Contrib 1.44 from nuget, it requires 1.42 of Dapper. I just tried with a fresh console app and it works fine. Or perhaps I misunderstood?

**Comment by janzakrzewskipl** [comment]
Hi @johandanforth Try to run https://github.com/janzakrzewskipl/DapperContrib144Issue

**Comment by johandanforth** [comment]
@janzakrzewskipl I will try upload a new nuget package for contrib today that has proper dependencies in it. I obviously messed up the current one and I'm sorry for it.

**Comment by janzakrzewskipl** [comment]
Great, don't worry. It is not a problem :)

**Comment by johandanforth** [comment]
Thanks :)

**Comment by johandanforth** [comment]
I just published a new nuget package for contrib, using the `dnu pack` tool and referencing the new project.json file, and it looks good with references and all. I unlisted the previous package. Feel free to try the new package if you got time for it @janzakrzewskipl  located at https://www.nuget.org/packages/Dapper.Contrib/1.50.0-beta3

**Comment by janzakrzewskipl** [comment]
@johandanforth I gave it a try. All our tests related to data access pass, but don't consider that as a full test of dapper :) We use only small part of its functionality.

**Comment by NickCraver** [comment]
Making this one resolved, thanks for the package fix @johandanforth!
