### ISSUE TITLE
Nuget package issue

### ISSUE THREAD

**Issue by JoeSchmoeDev** [StackExchange/dapper-dot-net#423]
When adding the latest stable release (1.42) through nuget, the actual assembly version that's added is 1.40. This doesn't pose a problem when building locally in VS2015, but the build server barfs since I don't check in my packages and rely on nuget restore.

This is the dapper line in my packages.config:
package id="Dapper" version="1.42" targetFramework="net45"

These are the details of Dapper.dll file in my packages folder:
![image](https://cloud.githubusercontent.com/assets/16327264/11854119/c90fb2ca-a40f-11e5-9f47-d49cbdedfbce.png)

**Comment by mgravell** [comment]
Yup, I forgot to update the metadata. Cannot be changed now: nuget doesn't
allow updates.

On 16 December 2015 at 21:31, JoeSchmoeDev <notifications@github.com> wrote:

> When adding the latest stable release (142) through nuget, the actual
> assembly version that's added is 140 This doesn't pose a problem when
> building locally in VS2015, but the build server barfs since I don't check
> in my packages and rely on nuget restore
>
> This is the dapper line in my packagesconfig:
> package id="Dapper" version="142" targetFramework="net45"
>
> These are the details of Dapperdll file in my packages folder:
> [image: image]
> <https://camo.githubusercontent.com/45a6ca019933433ed626b03fc6ea6cc0a7528f9e/68747470733a2f2f636c6f756467697468756275736572636f6e74656e74636f6d2f6173736574732f31363332373236342f31313835343131392f63393066623263612d613430662d313165352d396634372d643439636264656466626365706e67>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/423>.
>



-- 
Regards,

Marc

**Comment by mgravell** [comment]
Will fix in subsequent releases, but: nothing I can do about this one
