### ISSUE TITLE
TypeLoadException on mono 4.2.1

### ISSUE THREAD

**Issue by sklose** [StackExchange/dapper-dot-net#424]
I am getting this exception when I try to use Dapper on mono

```
System.TypeInitializationException: The type initializer for 'Dapper.SqlMapper' threw an exception. 
---> System.TypeLoadException: Failed for unknown reasons.
```

Looking at the type initializer code of SqlMapper and the mono documentation, it seems that 

```
AddTypeHandlerImpl(typeof(IEnumerable<Microsoft.SqlServer.Server.SqlDataRecord>), new SqlDataRecordHandler(), false);
```

is the culprit - Microsoft.SqlServer.Server.SqlDataRecord is listed nowhere in the mono docs, I guess it isn't implemented.

**Comment by mgravell** [comment]
K, that's fun. I will see if we can wrap that in some hackery to dodge
around that. Should have something in the next few days.

**Comment by mgravell** [comment]
Please can I ask you to verify via 1.50.0-beta6 (available on nuget)?

**Comment by sklose** [comment]
It's working for me, thanks for the quick fix!

**Comment by mgravell** [comment]
@sklose  thanks for a clear bug report that let me understand exactly what the problem was and what needed changing ;p (sadly, they're not always so clear)

**Comment by NilufarMakhmudova** [comment]
@mgravell, we are experiencing a similar problem with our Xamarin Android solution with SQLite database, where Dapper 1.50.5 NuGet package is installed.
 System.TypeInitializationException: The type initializer for 'Dapper.SqlMapper' threw an exception. ---> System.NullReferenceException: Object reference not set to an instance of an object.
 at Dapper.SqlMapper.AddTypeHandlerImpl (System.Type type, Dapper.SqlMapper+ITypeHandler handler, System.Boolean clone)
 at Dapper.SqlMapper.ResetTypeHandlers (System.Boolean clone)
 at Dapper.SqlMapper..cctor () 

Are there any clues on how to fix it?
