### ISSUE TITLE
Problem with Mysql and TimeStamp

### ISSUE THREAD

**Issue by bastiflew** [StackExchange/dapper-dot-net#426]
I have created a question on SO, but it seems to be an issue with dapper.
http://stackoverflow.com/questions/34439033/timespan-ticks-get-1-after-save
I try to find what is causing this problem with dapper source code, but I wanted to notify you this issue.

**Comment by mgravell** [comment]
Dapper doesn't do anything here except cast. If you do the exact same thing
with raw ADO.NET: do you get the same result?

**Comment by bastiflew** [comment]
It works with ADO.NET, read the value with reader.GetTimeSpan(), update the row with the same timespan object, and read again, the TimeSpan Ticks are the same

**Comment by mgravell** [comment]
I'm trying to come up with a working repro, but: the example you give under "A timespan object before save" ... looks like a datetime, not a timespan. Can you clarify?

**Comment by mgravell** [comment]
Test passes ^^^

**Comment by bastiflew** [comment]
The problem was on my side, sorry for the loss of time.
