### ISSUE TITLE
Read data in transaction

### ISSUE THREAD

**Issue by okansarica** [StackExchange/dapper-dot-net#432]
This method doesn't read last inserted row in transaction:
```C#
Query("Select Max(FaturaNo) as FaturaNo from Fatura Where VeriTipi=1", transaction)
```

1. I insert a record has FaturaNo 0001
2. I run the query method and get null as result

I can get the result if i select the last inserted record with id:

```C#
Query<myPoco>("select * from ...")
```

**Comment by mgravell** [comment]
Try:

    Query("Select Max(FaturaNo) as FaturaNo from Fatura Where VeriTipi=1",transaction: transaction) 

At the moment, you are supplying `transaction` as the *parameters*.

**Comment by mgravell** [comment]
Assuming resolved due to lack of response; if there is still a problem, let me know.
