### ISSUE TITLE
SqlBuilder regex expression removes chars outside /** **/ clauses

### ISSUE THREAD

**Issue by feugen24** [StackExchange/dapper-dot-net#436]
The issue is on SqlBuilder line 67:

    private static readonly Regex _regex = new Regex(@"\/\*\*.+\*\*\/", RegexOptions.Compiled | RegexOptions.Multiline);

Given the following sql input:

     select table.* FROM SomeTable as table /**innerjoin**/  /**fulljoin**/  /**leftjoin**/  /**rightjoin**/ INNER          JOIN some join data /**where**/  /**orderby**/ OFFSET @skip ROWS FETCH NEXT @take ROWS    ONLY

it deletes "INNER JOIN some join data" if where/order by clause are not present.
It can be tested online on:
http://regexstorm.net/tester
with above sqlinput and `\/\*\*.+\*\*\/` expression.

If I change the expression to `/\*\*(.+?)\*\*/` seems to work fine.

**Comment by madagaga** [comment]
Same as #280 ?

**Comment by feugen24** [comment]
It's the same problem.

I tested input from here and #280 with both proposed regular expressions

    \/\*\*[^\*]*\*\*\/ 
    /\*\*(.+?)\*\*/
 on http://regexstorm.net/tester tester side by side and they give similar results except for the split-list tab(regex split function?) where the expression in #280 omits some results. 

I'm not sure what expression is better.

**Comment by RCGodward** [comment]
We started encountering this issue today.  Guess we've been lucky before.  Adding the question mark fixed it with no ill effects in our codebase.

`\/\*\*.+?\*\*\/`

**Comment by jods4** [comment]
This can be closed as a dup of #280.
