### ISSUE TITLE
NullableValues non set 

### ISSUE THREAD

**Issue by DGuidi** [StackExchange/dapper-dot-net#437]
Tested against Dapper 1.4.2, see code [here](https://dl.dropboxusercontent.com/u/2663849/TestNullableValueMapping.zip).

When I try to map a query from db with an object that has a nullable property initialized in constructor
```
public class TestModelWithDefaultValue
{
	public TestModelWithDefaultValue()
	{
		TestNullableDecimal = 1000;
	}

	public string TestString { get; set; }

	public decimal? TestNullableDecimal { get; set; }
}
```  
then value from constructor is maintained also when reader from db reads DbNull value.
this not happens when reader retrieve a not-null value, and even "null" value, instead of DbNull!

Sorry for the poor explaination, I hope UnitTest attached explain better my problem.
```  
using System;
using System.Collections.Generic;
using System.Data;
using System.Linq;
using NUnit.Framework;
using Dapper;
using Rhino.Mocks;

namespace TestNullableValueMapping
{
    [TestFixture]
    public class UnitTests
    {
        public class TestModelPlain
        {
            public string TestString { get; set; }

            public decimal? TestNullableDecimal { get; set; }
        }

        public class TestModelWithDefaultValue
        {
            public TestModelWithDefaultValue()
            {
                TestNullableDecimal = 1000;
            }

            public string TestString { get; set; }

            public decimal? TestNullableDecimal { get; set; }
        }

        private static void Configure(IDataReader rdr, IDbCommand cmd, IDbConnection conn, object defValue)
        {
            Expect.Call(rdr.IsClosed).Return(false).Repeat.Any();
            Expect.Call(rdr.Dispose).Repeat.Any();
            Expect.Call(cmd.Dispose).Repeat.Any();
            Expect.Call(conn.Dispose).Repeat.Any();

            Expect.Call(conn.ConnectionString).Return("a_connection_string");
            Expect.Call(conn.State).Return(ConnectionState.Open);
            Expect.Call(conn.CreateCommand()).Return(cmd);

            Expect.Call(cmd.CommandText).SetPropertyWithArgument(SqlStatement);
            Expect.Call(cmd.ExecuteReader(CommandBehavior.SequentialAccess)).Return(rdr);


            Expect.Call(rdr.FieldCount).Return(2).Repeat.Any();
            Expect.Call(rdr.GetName(0)).Return("TestString").Repeat.Any();
            Expect.Call(rdr.GetFieldType(0)).Return(typeof(string)).Repeat.Any();
            Expect.Call(rdr.GetName(1)).Return("TestNullableDecimal").Repeat.Any();
            Expect.Call(rdr.GetFieldType(1)).Return(typeof(decimal?)).Repeat.Any();

            Expect.Call(rdr.Read()).Return(true);
            Expect.Call(rdr[0]).Return(StringVal);
            Expect.Call(rdr[1]).Return(defValue);
            Expect.Call(rdr.Read()).Return(false);
            Expect.Call(rdr.NextResult()).Return(false);
        }

        private const string SqlStatement = "sql_mock_query";
        private const string StringVal = "StringVal";

        [Test]
        public void dapper_should_set_null_values()
        {
            MockRepository repo = new MockRepository();
            IDbConnection conn = repo.StrictMock<IDbConnection>();
            IDbCommand cmd = repo.StrictMock<IDbCommand>();
            IDataReader rdr = repo.StrictMock<IDataReader>();

            With.Mocks(repo)
                .Expecting(() => { Configure(rdr, cmd, conn, null); })
                .Verify(() =>
                {
                    using (conn)
                    {
                        IList<TestModelPlain> query = conn.Query<TestModelPlain>(SqlStatement).ToList();
                        Assert.That(query, Is.Not.Null);
                        Assert.That(query, Is.Not.Empty);
                        Assert.That(query.Count, Is.EqualTo(1));

                        TestModelPlain item = query.Single();
                        Assert.That(item.TestString, Is.EqualTo(StringVal));
                        Assert.That(item.TestNullableDecimal, Is.Null);
                    }
                });
        }

        [Test]
        public void dapper_should_set_dbnull_values()
        {
            MockRepository repo = new MockRepository();
            IDbConnection conn = repo.StrictMock<IDbConnection>();
            IDbCommand cmd = repo.StrictMock<IDbCommand>();
            IDataReader rdr = repo.StrictMock<IDataReader>();

            With.Mocks(repo)
                .Expecting(() => { Configure(rdr, cmd, conn, DBNull.Value); })
                .Verify(() =>
                {
                    using (conn)
                    {
                        IList<TestModelPlain> query = conn.Query<TestModelPlain>(SqlStatement).ToList();
                        Assert.That(query, Is.Not.Null);
                        Assert.That(query, Is.Not.Empty);
                        Assert.That(query.Count, Is.EqualTo(1));

                        TestModelPlain item = query.Single();
                        Assert.That(item.TestString, Is.EqualTo(StringVal));
                        Assert.That(item.TestNullableDecimal, Is.Null);
                    }
                });
        }

        [Test]
        public void dapper_should_set_null_values_also_if_default_value_is_not_null()
        {
            MockRepository repo = new MockRepository();
            IDbConnection conn = repo.StrictMock<IDbConnection>();
            IDbCommand cmd = repo.StrictMock<IDbCommand>();
            IDataReader rdr = repo.StrictMock<IDataReader>();

            With.Mocks(repo)
               .Expecting(() => { Configure(rdr, cmd, conn, null); })
                .Verify(() =>
                {
                    using (conn)
                    {
                        const string sql = "sql_mock_query";
                        IList<TestModelWithDefaultValue> query = conn.Query<TestModelWithDefaultValue>(sql).ToList();
                        Assert.That(query, Is.Not.Null);
                        Assert.That(query, Is.Not.Empty);
                        Assert.That(query.Count, Is.EqualTo(1));

                        TestModelWithDefaultValue item = query.Single();
                        Assert.That(item.TestString, Is.EqualTo("StringVal"));
                        Assert.That(item.TestNullableDecimal, Is.Null);
                    }
                });
        }

        [Test]
        public void dapper_should_set_dbnull_values_also_if_default_value_is_not_null()
        {
            MockRepository repo = new MockRepository();
            IDbConnection conn = repo.StrictMock<IDbConnection>();
            IDbCommand cmd = repo.StrictMock<IDbCommand>();
            IDataReader rdr = repo.StrictMock<IDataReader>();

            With.Mocks(repo)
               .Expecting(() => { Configure(rdr, cmd, conn, DBNull.Value); })
                .Verify(() =>
                {
                    using (conn)
                    {
                        const string sql = "sql_mock_query";
                        IList<TestModelWithDefaultValue> query = conn.Query<TestModelWithDefaultValue>(sql).ToList();
                        Assert.That(query, Is.Not.Null);
                        Assert.That(query, Is.Not.Empty);
                        Assert.That(query.Count, Is.EqualTo(1));

                        TestModelWithDefaultValue item = query.Single();
                        Assert.That(item.TestString, Is.EqualTo("StringVal"));
                        Assert.That(item.TestNullableDecimal, Is.Null);
                    }
                });
        }

        [Test]
        public void dapper_should_set_notnull_values_also_if_default_value_is_not_null()
        {
            MockRepository repo = new MockRepository();
            IDbConnection conn = repo.StrictMock<IDbConnection>();
            IDbCommand cmd = repo.StrictMock<IDbCommand>();
            IDataReader rdr = repo.StrictMock<IDataReader>();

            With.Mocks(repo)
               .Expecting(() => { Configure(rdr, cmd, conn, 1m); })
                .Verify(() =>
                {
                    using (conn)
                    {
                        const string sql = "sql_mock_query";
                        IList<TestModelWithDefaultValue> query = conn.Query<TestModelWithDefaultValue>(sql).ToList();
                        Assert.That(query, Is.Not.Null);
                        Assert.That(query, Is.Not.Empty);
                        Assert.That(query.Count, Is.EqualTo(1));

                        TestModelWithDefaultValue item = query.Single();
                        Assert.That(item.TestString, Is.EqualTo("StringVal"));
                        Assert.That(item.TestNullableDecimal, Is.EqualTo(1m));
                    }
                });
        }
    }
}
```  
Thanks

**Comment by mgravell** [comment]
Yes. The original design was: ignore columns that aren't set. Leave it to
initializers. However, I acknowledge there may be scenarios where you
prefer a non-null default that is explicitly nulled from the data.

I haven't done a full analysis, but it occurs that it would be pretty
simple to have a global setting (we already have a place for this) that
enables explicit nulls, which would then explicitly assign null to
properties/fields. It would only apply to nullable members, i.e. reference
types (string, byte[]) and Nullable-of-T.

I don't think it is a huge amount of work. Sound viable?

**Comment by DGuidi** [comment]
>I don't think it is a huge amount of work. Sound viable?
Absolutely! 
This setting (of course with a default that doesn't change expected dapper behavior) can be pretty useful to me.
Thanks for the fast response, too.

**Comment by NickCraver** [comment]
@mgravell where are you picturing the setting? Not against having it - sounds like a good solution, just curious.

**Comment by mgravell** [comment]
SqlMapper.Settings.cs

On 19 January 2016 at 23:53, Nick Craver <notifications@github.com> wrote:

> @mgravell <https://github.com/mgravell> where are you picturing the
> setting? Not against having it - sounds like a good solution, just curious.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/437#issuecomment-173027160>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
I wish SqlMapper.Settings wasn't the actual code, but that's a 2.x type change - since most people only use the extension methods the name SqlMapper never really appears in most projects.

Totally agree with implementing this as-is, just pondering about a better (more intuitive) path to settings for a 2.x release.

**Comment by DGuidi** [comment]
A "patch" for v1.42 actually can be useful, if possible or at least some hints about how to introduce new behavior. I'm not a good IL-programmer...

**Comment by mgravell** [comment]
The "where should they go in a perfect world" discussion is separate, and
isn't a barrier to this. I'm busy today and tonight, but I'll probably take
a look at this tomorrow evening. For a 1.* release, the existing Settings
object is fine IMO.

On 20 January 2016 at 13:39, Diego Guidi <notifications@github.com> wrote:

> A "patch" for v1.42 actually can be useful, if possible or at least some
> hints about how to introduce new behavior. I'm not a good IL-programmer...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/437#issuecomment-173207143>
> .
>



-- 
Regards,

Marc

**Comment by DGuidi** [comment]
no bad feelings, and absolutely I don't need a "fix" asap. thanks again.

----- Messaggio originale -----
Da: "Marc Gravell" <notifications@github.com>
Inviato: ‎20/‎01/‎2016 14:59
A: "StackExchange/dapper-dot-net" <dapper-dot-net@noreply.github.com>
Cc: "Diego Guidi" <diegoguidi@gmail.com>
Oggetto: Re: [dapper-dot-net] NullableValues non set  (#437)

The "where should they go in a perfect world" discussion is separate, and
isn't a barrier to this. I'm busy today and tonight, but I'll probably take
a look at this tomorrow evening. For a 1.* release, the existing Settings
object is fine IMO.

On 20 January 2016 at 13:39, Diego Guidi <notifications@github.com> wrote:

> A "patch" for v1.42 actually can be useful, if possible or at least some
> hints about how to introduce new behavior. I'm not a good IL-programmer...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/437#issuecomment-173207143>
> .
>



-- 
Regards,

Marc

**Comment by mgravell** [comment]
Addressed here: https://github.com/StackExchange/dapper-dot-net/commit/a46d339550f60e484dc45f840157dc9908c1e9dd

**Comment by DGuidi** [comment]
thanks :)

**Comment by DGuidi** [comment]
I hope to use this code as a __suggestion__ and create a patch for 1.42, that actually is the version I use.

**Comment by mgravell** [comment]
That's fine, of course. But I have to ask: are there reasons you are
avoiding the 1.50 releases? If it is the "beta" in the name, that is mainly
because the package also includes binaries for .net core, but: if you
aren't using that, it isn't a problem at all. We're using 1.50* at
stackoverflow in prod.

On 8 February 2016 at 07:56, Diego Guidi <notifications@github.com> wrote:

> I hope to use this code as a *suggestion* and create a patch for 1.42,
> that actually is the version I use.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/437#issuecomment-181246188>
> .
>



-- 
Regards,

Marc

**Comment by DGuidi** [comment]
> We're using 1.50* atstackoverflow in prod.

@mgravell actually, our project is FW.4.0 and VS2013 only, and we'd like to have source code directly included in our basecode. of course, doesn't make sense for you to patch older versions.

**Comment by mgravell** [comment]
Fair enough. I will note that the nuget package supports 4.0 and above, but
I totally understand that the nuget tooling support around VS2013 is not
great - and even if you got it working, it would of course be an assembly
reference, not inline code. Good luck with the patch!
