### ISSUE TITLE
Parameters and Oracle .NET ADO provider

### ISSUE THREAD

**Issue by pedrofialho** [StackExchange/dapper-dot-net#439]
Hi,

The latest Dapper NuGet (1.40.0.0) seems to hang when calling .Query() with the anonymous type parameter collection on an Oracle .NET ADO connection.

**Sample code**

This works:

```c#
connection.Query<MyPoco>("SELECT ID_MY_TABLE AS ID, NM_MY_TABLE AS Name
                            FROM MY_TABLE");
```

This does not (hangs forever):

```c#
connection.Query<MyPoco>("SELECT ID_MY_TABLE AS ID, NM_MY_TABLE AS Name
                            FROM MY_TABLE
                           WHERE NM_MY_TABLE = :Name", new { Name = name });
```

I ran both queries manually against the database and found no problems, so it is not a case of issues with slow indexes or anything. Also, to reinforce that, this, interestingly, does work:

```c#
var parameters = new DynamicParameters();
parameters.Add("Name", value: name, dbType: DbType.AnsiString);
connection.Query<MyPoco>("SELECT ID_MY_TABLE AS ID, NM_MY_TABLE AS Name
                            FROM MY_TABLE
                           WHERE NM_MY_TABLE = :Name", parameters);
```

... but shows the same behavior of the second example when `dbType` is ommited. Seems like it happens when the parameter type is not specified explicitly.

.NET runtime version is v4.0.30319 and System.Data.OracleClient version is 4.0.0.0

**Comment by mgravell** [comment]
In your case, it seems that the important difference is ansi vs unicode.

The fun thing when comparing manually against the database in this specific example is making sure your compare like with like.

If this was SQL Server, for example, I might do:

    declare @name nvarchar(100) = N'abc';
    -- ...
    where NM_MY_TABLE = @name

vs

    declare @name varchar(100) = 'abc';
    -- ...
    where NM_MY_TABLE = @name

and those two things can behave **very** differently. I don't know enough about Oracle to give the equivalent syntax.

There are a few things we can do to help here, though; the `DbString` type allows you to specify the string type without requiring something as overkill as `DynamicParameters`, for example:

    , new { Name = new DbString { Value = name, IsAnsi = true }) }

If *all* of your strings are ansi, you could also set `DbString.IsAnsiDefault = true;`, and just use

    , new { Name = new DbString { Value = name }) }

Any use?

**Comment by mgravell** [comment]
To be clear, though; I suspect strongly that any "hang" here is actually just it taking a long time when the parameter type doesn't match the index. Unfortunately, what tends to happen is that the optimizer decides to *widen* the *indexed data*, which means it can't use the index - so you get a table scan combined with a string conversion per row. Very bad for large tables.

**Comment by pedrofialho** [comment]
Indeed, it did not work when switching from DbType.AnsiString to DbType.String. The DbString syntax is a good suggestion, much better than always using DynamicParameters.

It is so weird, because this particular table I'm testing against isn't a large one (~500 rows only). Even when I limit the set before filtering (using ROWNUM, like a query with a TOP subquery in SQL Server), it goes on and on without a response, even with just 1 row.

**Comment by pedrofialho** [comment]
I think I got it. Tried to reproduce it with OracleCommand and it happened, though I had to force it; it "hangs" just as well when adding the parameter like this:

```c#
cmd.Parameters.Add(new OracleParameter("Name", name) { DbType = DbType.String });
```

Seems like it either defaults to ANSI or detects it, as it runs fine with the plain object construction. I haven't taken a look at the code yet, but I assume then Dapper uses DbType.String, right?

**Comment by mgravell** [comment]
Yes, dapper defaults to Unicode strings (DbType.String) because .NET
strings are Unicode.

**Comment by pedrofialho** [comment]
The newest stable NuGet doesn't have DbString.IsAnsiDefault, but I managed to get it with the prerelease package, and it worked like a charm. But there's no way to pass anonymous types and work with ANSI strings by default other than tweaking SqlMapper, it seems; it would be useful if SqlMapper had an option or something for a more flexible type mapping and less configuration and code in Query(); do you guys plan to include something like that in the future or think it would be possible to be available as a feature in some extension etc?

**Comment by mgravell** [comment]
It is a trade off; every feature adds complexity, which has a runtime cost
and a maintenance cost. But I can also see how this might be vexing for
people who deal exclusively in non-unicode. But the reality is: the world
is ever-increasingly unicode :)

It isn't on my list of things to do immediately, but...

**Comment by pedrofialho** [comment]
I understand, and totally agree, too bad that some people still have to support non-unicode stuff on a daily basis sometimes.
Anyway, if I come up with anything good I'll be sure to create a pull request.
Thanks Marc! (And sorry for the late reply!)
