### ISSUE TITLE
KeyNotFoundException when enumerating DynamicParameters.ParameterNames

### ISSUE THREAD

**Issue by osudude** [StackExchange/dapper-dot-net#442]
After a sqlexception occurs during dapper execution, in our exception handler, we attempt to bundle up the dapper param values for subsequent notification / logging.

In this particular case a SqlException / timeout occurred while executing a SQL sp. We tried to enumerate the dapper params in our exception handler. For some reason, this can result in KeyNotFoundException when enumerating the Dapper DynamicParameters.  

```C#
public SosMessage ConstructMessage(CommandType cmdType, string sql, DynamicParameters dapperParams, DateTime cmdStarted, SosConfiguration config)
{
    var cmd = new SqlCommand(sql) {CommandType = cmdType};
    if (dapperParams != null)
    {
        var pNames = dapperParams.ParameterNames;
        foreach (var pName in pNames) //KeyNotFoundException here
        {
            var param = new SqlParameter(pName, dapperParams.Get<object>("pName"));
            cmd.Parameters.Add(param);
        }
    }
    return ConstructMessage(cmd, config.SosProgramName, cmdStarted, config.SosWarnThreshold);
}
```

Please advise how to properly enumerate the dapper params without getting KeyNotFoundException.

thanks

Dapper 1.42
.NET 4.5
SQL 2014

**Comment by mgravell** [comment]
Sounds like a bug probably relating to post-command callbacks for out / ret
params. I will have to investigate.

**Comment by NickCraver** [comment]
In your code I see this:
```C#
var param = new SqlParameter(pName, dapperParams.Get<object>("pName"));
```
Did you mean this?
```C#
var param = new SqlParameter(pName, dapperParams.Get<object>(pName));
```
Side note: when you throw an exception in the iterator often you'll see the line appear to be the `for()` itself...but that's kinda playing tricks on you due to how iterators are implemented underneath.

**Comment by osudude** [comment]
Doh!  That was the issue.   Thanks Nick!
