### ISSUE TITLE
Creating VIEW?

### ISSUE THREAD

**Issue by MedoDome** [StackExchange/dapper-dot-net#446]
Hi, 
I made models and I want to create VIEW for one class but when I want to create I get error in visual 

There was an error running the selected code generator: ' Generating view without DbContext is still not supported'

How to fix this?

**Comment by mgravell** [comment]
As mentioned on stackoverflow, that message has nothing whatsoever to do
with dapper. I don't know what VS plugin is generating that - personally, I
just tend to set the @model manually.

**Comment by NickCraver** [comment]
Closing this out - not a Dapper issue and thread on SO is more appropriate.
