### ISSUE TITLE
Dapper method like Query does not have a deferred execution

### ISSUE THREAD

**Issue by mrinalkamboj** [StackExchange/dapper-dot-net#453]
Though in my understanding its not, but still want to confirm, does any of Dapper method like `Query` which results in `IEnumerable <T>`, cause the deferred execution.

Was wondering, since we have a `Connection` being closed post `Query` call, but `IEnumerable <T>` thus fetched is used post connection close / dispose, so like Linq, if it does deferred execution, then we might have an issue with the current code, as it tries to execute using closed / disposed connection

**Comment by mgravell** [comment]
By default dapper uses eager consumption into a List<T>. This can be
disabled by using the optional "buffered" parameter which defaults to true.
Even if you use buffered: false - the *command* is executed immediately,
and you are handed an iterator over the open data-reader. You will only be
able to iterate it once, and as you note: if you close / dispose the
connection before you consume the data, it won't work. When using buffered:
false, you also need to be cautious of executing two commands at once,
unless your provider supports "MARS" or similar. Dapper deliberately
defaults to the easy to use options.

Note: to avoid allocating a list on top of a list, prefer the AsList()
extension method (added by dapper) over the regular LINQ ToList() method.
The AsList() method checks whether the source *is* a list, and if so simply
casts it without allocating / copying. If the source is not a list,
Enumerable.ToList is invoked.

On 5 February 2016 at 20:06, mrinalkamboj <notifications@github.com> wrote:

> Though in my understanding its not, but still want to confirm, does any of
> Dapper method like Query which results in IEnumerable <T>, cause the
> deferred execution
>
> Was wondering, since we have a Connection being closed post Query call,
> but IEnumerable <T> thus fetched is used post connection close / dispose,
> so like Linq, if it does deferred execution, then we might have an issue
> with the current code, as it tries to execute using closed / disposed
> connection
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/453>.
>



-- 
Regards,

Marc
