### ISSUE TITLE
Access LookupDbType from other library

### ISSUE THREAD

**Issue by vdaron** [StackExchange/dapper-dot-net#455]
Hi,

I would like to be able to access the LookupDbType method from SimpleStack.Orm and it seems that it's not possible anymore in the 1.50 pre-release.

`internal static DbType LookupDbType(Type type, string name, bool demand, out ITypeHandler handler)`

I used to call that method to retrieve dbType and ITypeHandler to generate my CREATE TABLE statements.

Thanks for feedback

**Comment by mgravell** [comment]
I probably saw it and thought "there's no reason for that to be public, and
nobody should be using it". If I did remove it, it was probably a naughty
breaking change and I deserve a wrist slap. Probably the best option is if
I make it public, and add an [Obsolete("some message", false)] and you can
#pragma around it - that work?

On 9 February 2016 at 20:58, Vincent DARON <notifications@github.com> wrote:

> Hi,
>
> I would like to be able to access the LookupDbType method from
> SimpleStack.Orm and it seems that it's not possible anymore in the 1.50
> pre-release.
>
> internal static DbType LookupDbType(Type type, string name, bool demand,
> out ITypeHandler handler)
>
> I used to call that method to retrieve dbType and ITypeHandler to generate
> my CREATE TABLE statements.
>
> Thanks for feedback
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/455>.
>



-- 
Regards,

Marc

**Comment by vdaron** [comment]
Would be perfect, thanks
