### ISSUE TITLE
Support read only properties in c# 6

### ISSUE THREAD

**Issue by arootbeer** [StackExchange/dapper-dot-net#473]
Following up on http://stackoverflow.com/questions/35634434/does-dapper-support-c-sharp-6-read-only-properties-in-pocos. Related to bebe80b.

**Comment by mgravell** [comment]
Beat you to it ;p https://github.com/StackExchange/dapper-dot-net/commit/bebe80bcaff983433ea8043f3e432fd191915035

**Comment by arootbeer** [comment]
Hey...I said bebe80b first :D

**Comment by mgravell** [comment]
1.50-beta9
