### ISSUE TITLE
How to properly use SqlBuilder's AddParameters() method?

### ISSUE THREAD

**Issue by sstorie** [StackExchange/dapper-dot-net#476]
I've got a simple case where I'm trying to debug why a query doesn't return what I expect within an Azure web job. To do so I have the following code:

```        
var albumSqlTemplate = @"
    WITH OrderedAlbums AS (
        SELECT *, RowNumber = (ROW_NUMBER() OVER (ORDER BY ContainerName DESC))
        FROM [Photography].[AlbumModelView]
    )
    SELECT 
        oa.*
        ,'PhotoId' = p.Id  -- just to support the splitOn parameter
        ,p.*
    FROM 
        OrderedAlbums oa
        LEFT OUTER JOIN [Photography].[PhotoModelView] p ON p.Id = oa.HighlightPhotoId
    /**where**/
    /**--parameters**/
";


var builder = new SqlBuilder();
var template = builder.AddTemplate(albumSqlTemplate);

if (context != null)
{
    if (context.AlbumId.HasValue)
    {
        builder.Where("oa.Id = @AlbumId", new {context.AlbumId});
    }

    if (!string.IsNullOrEmpty(context.ContainerName))
    {
        builder.Where("oa.ContainerName = @ContainerName", new { context.ContainerName });
    }

    if (!string.IsNullOrEmpty(context.Slug))
    {
        builder.Where("oa.Slug = @Slug", new { context.Slug });
    }

    if (context.QueryPage != null)
    {
        builder.Where("RowNumber BETWEEN ((@Page - 1) * @PageSize + 1) AND (@Page * @PageSize)",
            new {context.QueryPage.Page, context.QueryPage.PageSize});
    }
}

builder.AddParameters(template.Parameters);

Logger.Verbose("SQL: {RawSql}", template.RawSql);
Logger.Verbose("SQL parameters: {@Parameters}", template.Parameters);
```

So I'm using SqlBuilder to update the query, and it all appears to work okay in most cases (the azure web job problem aside), but I never see the parameters actually written to the query statement.

If I provide a `Slug` and the `QueryPage` values I see the following SQL logged for me:

```
WITH OrderedAlbums AS (
    SELECT *, RowNumber = (ROW_NUMBER() OVER (ORDER BY ContainerName DESC))
    FROM [Photography].[AlbumModelView]
)
SELECT 
    oa.*
    ,'PhotoId' = p.Id  -- just to support the splitOn parameter
    ,p.*
FROM 
    OrderedAlbums oa
    LEFT OUTER JOIN [Photography].[PhotoModelView] p ON p.Id = oa.HighlightPhotoId
WHERE oa.Slug = @Slug AND RowNumber BETWEEN ((@Page - 1) * @PageSize + 1) AND (@Page * @PageSize)
```

I can see the appropriate where clause was generated, and my `/**--parameters**/` statement was "replaced", but with nothing.

So I don't think I'm far off in understanding how to use this, but am I doing something really dumb here, or misunderstanding how exactly `builder.AddParameters()` is designed to work?

**Comment by sstorie** [comment]
Ok, I think I'm misunderstanding the purpose of that method. It's not designed to let you include the parameter values within the query statement (even as a comment) is it?

**Comment by NickCraver** [comment]
@sstorie Correct - it's for adding additional parameters that are passed into the SQL. The `--` prefix is so it's not hit by mistake :)

You can literally replace some values (not strings, for injection reasons) in the query, but you should only do this to debug or if it's a not-changing or very small finite set of values for which there is a benefit. The syntax for that is `{=parameterName}`, rather than `@parameterName`.

Alternatively, I'd just log or append this separately at the top of the query in a comment.

**Comment by sstorie** [comment]
Ok, good to know I'm not misunderstanding things now. Thanks for the information...I'll close this since it's not really an issue.
