### ISSUE TITLE
Confirmed solution for Specified Cast Not Valid issue

### ISSUE THREAD

**Issue by mrinalkamboj** [StackExchange/dapper-dot-net#477]
Dealing with the issue mentioned in the [277](https://github.com/StackExchange/dapper-dot-net/issues/277), strangely few machines reproduce it others don't. In my case database can fetch a value which is either int or byte internally, I am consuming everything in the int?, now on machines where it fails, it fails while type casting a byte not integer. On other machines, everything goes through.

System configuration, where it pass is : 
VS 2015 - .Net 4.6.1, Windows 10 Enterprise, Dapper - 1.42 via Nuget,

where it fails is:
VS 2015 - .Net 4.6.1, Microsoft Windows Server 2012 R2 Standard, Dapper - 1.42 via Nuget,

As I understand 1.50-beta8 shall resolve the issue, but does this has anything to do with the Windows flavour, .Net version, Visual studio version, so that I can try to make it work with dapper 1.42 itself.

Also 1.50-beta8 is not yet on Nuget, when is it planned, meanwhile I need to use the stand alone binary, please confirm.

**Comment by mgravell** [comment]
Ooh, that's intriguing. I guess it is possible that something funky is
different between them. Can I assume they're both x64? I will do a new
build on nuget tomorrow if I remember.

**Comment by mgravell** [comment]
1.50 beta 8 is most certainly on nuget and has been for some time:
https://www.nuget.org/packages/Dapper/1.50.0-beta8

**Comment by mrinalkamboj** [comment]
@mgravell  A mistake from my end, though both the systems are X64, but as the re-analysis suggest, there's issue on same machine with configuration:

VS 2015 - .Net 4.5.2, Windows 10 Enterprise, Dapper - 1.42 via Nuget

between two different SVN branches, one branch it works, other doesn't both connect to same database, both use the same dapper 1.42, so just wondering what could be different, there has to some incompatibility for it to fail on same machine, not sure it becomes more intriguing now :).

Yes 1.50.0-beta8, is available on Nuget and lists in VS, just that it suggest 1.42 as stable version, apology for that omission. As per your update, that's already production, correct.

Will run few more test cases and update

**Comment by NickCraver** [comment]
Closing out to cleanup
