### ISSUE TITLE
Dapper.Contrib fails to INSERT asynchronously with "Cannot convert zero to 'int' error(...)"

### ISSUE THREAD

**Issue by kamil-mrzyglod** [StackExchange/dapper-dot-net#483]
Dapper version: 1.42
Dapper.Contrib version: 1.43 

After switching all my helpers to async, I cannot insert any new entity. All entities are correctly mapped to proper tables using `[Table]` attribute and have `Id` with `IDENTITY(1,1)`..

One example:

```
[Table("SoftwareVersion")]
public class SoftwareVersion
{
        public int Id { get; set; }
        public string Version { get; set; } 
        public string Description { get; set; }
}
```

```
public async Task<OutEnvelope<SoftwareVersionId>> Handle(InEnvelope<Requests.Create> message)
{
            var softwareVersion = message.Request;

            var id = await 
                _connection.InsertAsync(
                    new SoftwareVersion { Description = softwareVersion.Description, Version = softwareVersion.Version });

            return new SoftwareVersionId().From(id);
}
```

Such action always fails with "Cannot convert zero to 'int' error(...)" error. I believe it is caused by Dapper.Contrib `SqlServerAdaper.InsertAsync` method and the following part of it:

```
string cmd = string.Format("insert into {0} ({1}) values ({2})", (object) tableName, (object) columnList, (object) parameterList);
int num = await SqlMapper.ExecuteAsync(connection, cmd, entityToInsert, transaction, commandTimeout, new CommandType?()).ConfigureAwait(false);
IEnumerable<object> r = await SqlMapper.QueryAsync<object>(connection, "select @@IDENTITY id", (object) null, transaction, commandTimeout, new CommandType?()).ConfigureAwait(false); 
```

I see that in newest Contrib version it was fixed with:
`var cmd = String.Format("insert into {0} ({1}) values ({2});select SCOPE_IDENTITY() id", tableName, columnList, parameterList);`
and using `QueryMultipleAsync` method.

I can confirm that writing such statement on my own enables me to continue with asynchronous insert. Is there any possibility to introduce those changes into 1.4X version of Dapper.Contrib?

**Comment by NickCraver** [comment]
Is this an issue in the latest version?
