### ISSUE TITLE
Cannot read results of a MultiExec

### ISSUE THREAD

**Issue by twhitbeck** [StackExchange/dapper-dot-net#485]
I often use the `OUTPUT` clause to get a generated Id upon inserting a record.

``` sql
INSERT INTO Table (A, B, C)
OUTPUT inserted.Id
VALUES (@A, @B, @C)
```

This works well with `ExecuteScalar`

``` cs
var newId = connection.ExecuteScalar<int>(sql, thing);
```

However, if I want to insert multiple records at once, I can't find a way to read the results of a MultiExec to get the ids. `Query` doesn't interpret `IEnumerable` params like `Execute` does, and when I use `ExecuteReader` I get an error "MultiExec is not supported by ExecuteReader".

Is there a way to do what I want?

**Comment by mgravell** [comment]
How about:

    var results = yourData.SelectMany(x => conn.Query<Foo>(sql, X));

? Would that work?

The other option might be a table valued parameter, but they are a bit of a
faff and require setup at the server.

**Comment by twhitbeck** [comment]
That would work or something like it

```cs
var newIds = thingsToInsert.Select(thing => conn.ExecuteScalar<int>(sql, thing));
```

But that will perform an Insert for each thing. I was under the assumption that `Execute(string sql, IEnumerable<T> params)` was more efficient by performing only *one* INSERT. Is that the case?

**Comment by mgravell** [comment]
> was more efficient by performing only one INSERT. Is that the case?

No, that is not the case. Dapper can't rewrite your query to that extent (although that would be nice, right?). When using the `*Async` API with MARS enabled, what it *can* do is run all the operations utilizing MARS, so you don't pay n*latency, but: other than that, this is purely a convenience unroll.

**Comment by NickCraver** [comment]
Closing out to cleanup
