### ISSUE TITLE
Dapper throws exception second time you run a query if different results schema

### ISSUE THREAD

**Issue by mgimeno** [StackExchange/dapper-dot-net#488]
I just raised the same issue on Stackoverflow:
http://stackoverflow.com/questions/36250047/dapper-throws-exception-second-time-you-run-a-query-if-different-results-schema

I'm using Dapper, Sqlite on c# coreclr.

```C#
public async Task<UserPoco> GetFromEmail(string email)
{
    email = email.ToLower();

    using (var connection = new SqliteConnection(_configSettings.ConnectionString))
    {
        connection.Open();
        var query = $"SELECT * FROM users WHERE EmailAddress = '{email}';";
        var result = await connection.QueryAsync<UserPoco>(query);
        return result.FirstOrDefault();
    }
}
```

That simple method throws an exception if at some point the SQL query find no results and next time it runs it does find results. It throws: Unable to cast object of type 'System.Int64' to type 'System.Int32'. Error parsing column 0 (UserId=86 - Int64)

I'm pretty sure it's not related to the Datatypes. The UserPoco has a long UserId property and the DB table users has a UserId of type INTEGER which is the recommended one to store bigint (long). Moreover, for example if the method always finds data it will work like a charm. I do think is related to the fact that Dapper caches the result schema of every query it runs and throws an exception when this schema changes for the same query as they point out on: https://github.com/janjosephlim/dapper-dot-net/issues/124

What I don't understand is how come I can't find more info about this or more people is complaining about such a common scenario: I'm just running a very simple query multiple times which can bring back or not results.

What am I missing?

**Comment by NickCraver** [comment]
Does this happen with a correctly parameterized query? Sticking the email in like that is extremely dangerous, it's a problem called SQL injection. Your code should look like this instead:

```C#
public async Task<UserPoco> GetFromEmail(string email)
{
    email = email.ToLower();

    using (var connection = new SqliteConnection(_configSettings.ConnectionString))
    {
        const string query = "SELECT * FROM users WHERE EmailAddress = @email;";
        var result = await connection.QueryAsync<UserPoco>(query, new { email });
        return result.FirstOrDefault();
    }
}
```
Note: Dapper will already open the connection if needed.

Currently you're creating an entry in Dapper deserialization cache for every permutation of email, which is a side-effect of the injection issue. Let's solve that first and see where we stand.

**Comment by mgravell** [comment]
What is especially odd here: if you are using literal injection (which you
shouldn't do, as Nick notes), then the two operations have *nothing to do
with each other*...

Also: what changed in the schema? There is some checking in there, and the
checks have improved in recent (pre-rtm) builds.

**Comment by mgimeno** [comment]
I'm aware of SQL Injection, the email content is checked before that.
Anyway I also know about the issue creating an entry in the cache for every permutation if I don't use parameterized query, however for now I haven't been that (I postponed the fix) since  somehow I'm unable to do so.
If I use the code you suggested @NickCraver which I had been trying in different ways for a while, I always get the following exception from the Microsoft.Data.Sqlite library:
"Must add values for the following parameters: @email"
I've tried in different ways but can't manage to make it work which is becoming very annoying as once again I consider this as one of the simplest things you're going to do with Dapper+Sqlite. 
I must repeat that actually everything else I do with Dapper+Sqlite works just fine, it's only when I do a "SELECT" and result set is different from previous run, and when I say different I mean one time found 0 results and second time some results or vice versa.
Thank you for your help. Let's see if we can get to the bottom of this.

**Comment by NickCraver** [comment]
@mgimeno can you pleas paste your new code? Note the `new { email }` parameter I'm passing to `.QueryAsync()` in the example.

**Comment by mgimeno** [comment]
@NickCraver sure, I know about the parameter. I even tried just copy&pasted your code. Same issue: 
"Must add values for the following parameters: @email"

**Comment by NickCraver** [comment]
@mgimeno I'm simply unable to repro here (ot works as expected) - which version of the Dapper NuGet package are you using, and have you tried the latest 1.5x (pre-release) build?

**Comment by mgimeno** [comment]
Note that I'm using dnxcore50 (coreclr) framework.
Versions (from my project.json)
"Microsoft.Data.Sqlite": "1.0.0-rc1-final"
"Dapper": "1.50.0-beta4"
For Dapper I'm not using a version newer than that because funnily enough, if I do so, same simple queries like that one throw "The CommandBehavior 'SingleResult, SequentialAccess' is invalid."
As noted here: 
[](https://github.com/StackExchange/dapper-dot-net/issues/441)

**Comment by mgravell** [comment]
The SequentialAccess thing is actually a bug in the ADO.NET provider; it
has been fixed in their "unstable", and should work next deploy (of theirs).

**Comment by mgravell** [comment]
Re "I'm aware of SQL Injection, the email content is checked before that."
- it isn't my intention to be a jerk, but checking the contents - while a
great thing to do - is not the ideal solution re SQL injection. The right
way to solve that is: parameters. I realise there are other factors at play
here that you've mentioned (and that we can hopefully help with), but
please please don't ever think that value checking is a substitute for
parameters. That just puts you in an arms race.

**Comment by mgimeno** [comment]
@mgravell I appreciate the advise but first and as I said, I know about it and I'm not using parameters because basically is not working for me (throws an exception) and so I'm using a temporary solution.
And second, the issue I raised has nothing to do with that, actually my fault that I picked this example with the email when I could have picked and posted any other method that I'm using to "SELECT" data and has the exact same issue.

**Comment by NickCraver** [comment]
@mgimeno Are you in a position to try their pre-release package from the myget feed and our latest? .Net Core is a tricky situation at the moment, since you're fairly behind on both sets of rapidly moving libraries.

**Comment by mgravell** [comment]
For how to get rc2 for sqlite: see the nuget.config and project.json in
this commit: 096b4ac05c48dc9e5e4738b6aff51c02935cbb8b

**Comment by mgimeno** [comment]
@NickCraver yes, I'm still developing my project so I can do that.
@mgravell Thanks guys, I will give it a shot this evening and will let you know.

**Comment by mgimeno** [comment]
I tried updating:
"Microsoft.Data.Sqlite": "1.0.0-rc2-15948"
Doing that I can use parameters on my queries which I couldn't before, however I still need to use:
"Dapper": "1.50.0-beta4" to avoid getting "The CommandBehavior 'SingleResult, SequentialAccess' is invalid." with a newer versions.
With that setup, I still get the error stated on my first post.

The only newer version of Microsoft.Data.Sqlite I can use is "1.0.0-rc2-16099" as newer than that are not compatible with dnxcore50 and that version has a dependency on "System.Runtime": "4.1.0.0", so I updated all my projects in the solution with "System.Runtime": "4.1.0-rc2-23819" which also at some point made me update "Microsoft.CSharp" to "4.0.1-rc2-23819".

Now my project is building ok but I'm getting the following runtime error when I start the app:
System.IO.FileLoadException
Could not load file or assembly 'System.Runtime, Version=4.1.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The located assembly's manifest definition does not match the assembly reference. (Exception from HRESULT: 0x80131040)
.NET Framework CoreClr version 4.0.21.0   |   DNX x86 version 1.0.0-rc1-16231   |   Microsoft.AspNet.Hosting version 1.0.0-rc1-15988   |   Windows 10.0   |

Note: I also did dnvm update -u so when I do dnvm list I get:
*    1.0.0-rc2-20221   clr     x86          C:\Users\mgimeno\.dnx\runtimes default

I just got stuck with that error. Anyway I'm not very positive that even fixing that error, that new version of sqlite would make any difference regarding my original issue.

So, after spending way too much time in trying to make work such a simple scenario I've decided to move to another solution (not sure which yet) and maybe come back and try Dapper+Sqlite when new versions are released.

@NickCraver , @mgravell  Thank you anyway for your help,

**Comment by mgravell** [comment]
Fair enough. It is awkward and vexing that rc2 has been delayed - it is
creating much gnashing of teeth when there are things that are known to be
fixed but we can't get the bits easily :(

**Comment by mgravell** [comment]
Fun fact; I just realized that the code is already fixed (but not packaged
and deployed) to cope with this automagically. I thought I'd done it in a
local spike, but I did actually commit and push it. So: dapper actually
already handles this. I will be doing a new build soon.

https://github.com/StackExchange/dapper-dot-net/commit/df77f394f4723d0f8f4bcba6bb3cd555e931c86d

On 28 March 2016 at 23:18, Marc Gravell <marc.gravell@gmail.com> wrote:

> Fair enough. It is awkward and vexing that rc2 has been delayed - it is
> creating much gnashing of teeth when there are things that are known to be
> fixed but we can't get the bits easily :(
> On 28 Mar 2016 10:05 p.m., "Marcos" <notifications@github.com> wrote:
>
>> I tried updating:
>> "Microsoft.Data.Sqlite": "1.0.0-rc2-15948"
>> Doing that I can use parameters on my queries which I couldn't before,
>> however I still need to use:
>> "Dapper": "1.50.0-beta4" to avoid getting "The CommandBehavior
>> 'SingleResult, SequentialAccess' is invalid." with a newer versions.
>> With that setup, I still get the error stated on my first post.
>>
>> The only newer version of Microsoft.Data.Sqlite I can use is
>> "1.0.0-rc2-16099" as newer than that are not compatible with dnxcore50 and
>> that version has a dependency on "System.Runtime": "4.1.0.0", so I updated
>> all my projects in the solution with "System.Runtime": "4.1.0-rc2-23819"
>> which also at some point made me update "Microsoft.CSharp" to
>> "4.0.1-rc2-23819".
>>
>> Now my project is building ok but I'm getting the following runtime error
>> when I start the app:
>> System.IO.FileLoadException
>> Could not load file or assembly 'System.Runtime, Version=4.1.0.0,
>> Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its
>> dependencies. The located assembly's manifest definition does not match the
>> assembly reference. (Exception from HRESULT: 0x80131040)
>> .NET Framework CoreClr version 4.0.21.0 | DNX x86 version 1.0.0-rc1-16231
>> | Microsoft.AspNet.Hosting version 1.0.0-rc1-15988 | Windows 10.0 |
>>
>> Note: I also did dnvm update -u so when I do dnvm list I get:
>>
>>    - 1.0.0-rc2-20221 clr x86 C:\Users\mgimeno.dnx\runtimes default
>>
>> I just got stuck with that error. Anyway I'm not very positive that even
>> fixing that error, that new version of sqlite would make any difference
>> regarding my original issue.
>>
>> So, after spending way too much time in trying to make work such a simple
>> scenario I've decided to move to another solution (not sure which yet) and
>> maybe come back and try Dapper+Sqlite when new versions are released.
>>
>> @NickCraver <https://github.com/NickCraver> , @mgravell
>> <https://github.com/mgravell> Thank you anyway for your help,
>>
>> —
>> You are receiving this because you were mentioned.
>> Reply to this email directly or view it on GitHub
>> <https://github.com/StackExchange/dapper-dot-net/issues/488#issuecomment-202580895>
>>
>


-- 
Regards,

Marc

**Comment by mgimeno** [comment]
It seems to be working great, that solves both problems. Thank you!

**Comment by NickCraver** [comment]
@mgimeno Good to hear, thanks for working through this with us! Closing this out to cleanup :)
