### ISSUE TITLE
Multiple Results in Oracle

### ISSUE THREAD

**Issue by imman731** [StackExchange/dapper-dot-net#491]
Is dapper support Multiple Results in Oracle (via C# .net)?
I have an Error ORA:00933.

simple code as below, but it's still got error.
```c#
var sqlStr = @"
                             select sysdate from dual a
                             select sysdate from dual b";
                IDbConnection cnn = DBCnn;
                using (var multi = cnn.QueryMultiple(sqlStr, null))
                {
                     ....
                }
```

**Comment by mgravell** [comment]
ORA:00933 is, I believe "SQL command not properly ended" (
http://www.techonthenet.com/oracle/errors/ora00933.php). I cannot advise on
what you need to do *within oracle* to make that happy, but I'm not sure it
is anything to do with dapper. Is this perhaps a missing semicolon? Try:

    select sysdate from dual a;
    select sysdate from dual b;

(note the semicolons)

On 31 March 2016 at 08:59, imman731 <notifications@github.com> wrote:

> Is dapper support Multiple Results in Oracle (via C# .net)?
> I have an Error ORA:00933.
>
> simple code as below, but it's still got error.
> var sqlStr = @"
> select sysdate from dual a
> select sysdate from dual b";
> IDbConnection cnn = DBCnn;
> using (var multi = cnn.QueryMultiple(sqlStr, null))
> {
> ....
> }
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/491>
>



-- 
Regards,

Marc

**Comment by imman731** [comment]
I already to try it. As below,But it's still got an error..
select sysdate from dual a;
    select sysdate from dual b;

I will try to figure out. 
Thank you for your reply!

**Comment by mgravell** [comment]
The first thing to try is: exactly the same command via raw ADO.net
(command, etc). If it doesn't work in ADO.net, it *cannot* work in dapper.

**Comment by ducminh** [comment]
Use solution from this page
http://www.scriptscoop.site/t/1315f32d24ed/using-dapper-querymultiple-in-oracle.html

using Dapper;
using Oracle.ManagedDataAccess.Client;
using System.Data;

int selectedId = 1;
var sql = "BEGIN OPEN :rslt1 FOR SELECT * FROM customers WHERE customerid = :id; " +
                "OPEN :rslt2 FOR SELECT * FROM orders WHERE customerid = :id; " +
                "OPEN :rslt3 FOR SELECT * FROM returns Where customerid = :id; " +
          "END;";

OracleDynamicParameters dynParams = new OracleDynamicParameters();
dynParams.Add(":rslt1", OracleDbType.RefCursor, ParameterDirection.Output);
dynParams.Add(":rslt2", OracleDbType.RefCursor, ParameterDirection.Output);
dynParams.Add(":rslt3", OracleDbType.RefCursor, ParameterDirection.Output);
dynParams.Add(":id", OracleDbType.Int32, ParameterDirection.Input, selectedId);

using (IDbConnection dbConn = new OracleConnection("<conn string here>"))
{
    dbConn.Open();
    var multi = dbConn.QueryMultiple(sql, param: dynParams);

    var customer = multi.Read<Customer>().Single();
    var orders = multi.Read<Order>().ToList();
    var returns = multi.Read<Return>().ToList();
    ...
    dbConn.Close();
}

------------------------------------

using Dapper;
using Oracle.ManagedDataAccess.Client;
using System.Data;

public class OracleDynamicParameters : SqlMapper.IDynamicParameters
{
    private readonly DynamicParameters dynamicParameters = new DynamicParameters();

    private readonly List<OracleParameter> oracleParameters = new List<OracleParameter>();

    public void Add(string name, OracleDbType oracleDbType, ParameterDirection direction, object value = null, int? size = null)
    {
        OracleParameter oracleParameter;
        if (size.HasValue)
        {
            oracleParameter = new OracleParameter(name, oracleDbType, size.Value, value, direction);
        }
        else
        {
            oracleParameter = new OracleParameter(name, oracleDbType, value, direction);
        }

        oracleParameters.Add(oracleParameter);
    }

    public void Add(string name, OracleDbType oracleDbType, ParameterDirection direction)
    {
        var oracleParameter = new OracleParameter(name, oracleDbType, direction);
        oracleParameters.Add(oracleParameter);
    }

    public void AddParameters(IDbCommand command, SqlMapper.Identity identity)
    {
        ((SqlMapper.IDynamicParameters)dynamicParameters).AddParameters(command, identity);

        var oracleCommand = command as OracleCommand;

        if (oracleCommand != null)
        {
            oracleCommand.Parameters.AddRange(oracleParameters.ToArray());
        }
    }
}

**Comment by NickCraver** [comment]
Closing out to cleanup
