### ISSUE TITLE
1.50-beta9 lost StrongName

### ISSUE THREAD

**Issue by chrisxvin** [StackExchange/dapper-dot-net#498]
I get package from NuGet, and it doesn't have StrongName signed.

**Comment by mgravell** [comment]
Huh; that's odd - will check, thanks. I plan on re-deploying anyway, as
beta9 takes some rc2 deps that makes it very awkward to work with.

**Comment by chrisxvin** [comment]
1.50-rc2 from NuGet still have no StrongName....

**Comment by NickCraver** [comment]
@chrisxvin which package are you getting? https://www.nuget.org/packages/Dapper.StrongName/1.50.0-rc2a should be correctly signed, I double checked before the upload.

We will migrate to a single signed `Dapper` package and deprecate `Dapper.StrongName` in the v2 release, as that's a significant breaking change.

**Comment by chrisxvin** [comment]
I used Dapper package, just upgraded from 1.50-beta.
I'll wait for v2 release.
By the way, dapper is amazing :+1:

**Comment by NickCraver** [comment]
Just verified again: Dapper.StrongName is correctly signed, closing this out. Note: we'll simple strong name Dapper itself and eliminate .StrongName in v2.
