### ISSUE TITLE
SQLMapper: GenerateMapper Limitation of 6 additional navigation properties

### ISSUE THREAD

**Issue by Dryadwoods** [StackExchange/dapper-dot-net#500]
For example: the table "Post" has relations 1to1 to other tables by the fields: CreatorId, StatusId,  etc....

According to what I could find by looking at the source code, the method: 
`private static Func<IDataReader, TReturn> GenerateMapper<TFirst, TSecond, TThird, TFourth, TFifth, TSixth, TSeventh, TReturn>(Func<IDataReader, object> deserializer, Func<IDataReader, object>[] otherDeserializers, object map) `

shows me that the programmer can only use a maximum of 6 navigation properties, if somehow there is the need to load more than 6 the "query" will need to be splited..... I know that only few cases falls into this category, but it happens just like the case I am facing now.....

A quick solution would simply pass by adding more options like: TEighth, TNinth, TTenth........
However, there will be always a possibility that some extreme cases will have crazy number of relations.

**Comment by NickCraver** [comment]
There is another overload for the `n` types case that's often overlooked, here it is:
```C#
public static IEnumerable<TReturn> Query<TReturn>(this IDbConnection cnn, 
  string sql, 
  Type[] types, 
  Func<object[], TReturn> map, 
  object param = null, 
  IDbTransaction transaction = null, 
  bool buffered = true, 
  string splitOn = "Id", 
  int? commandTimeout = null, 
  CommandType? commandType = null)
```

**Comment by Dryadwoods** [comment]
You are correct :) I totally missed that one.
Thanks for the feedback.

**Comment by NickCraver** [comment]
@Dryadwoods okay awesome - re-open this if that still doesn't support your use case!

**Comment by Dryadwoods** [comment]
Well, there is a related issue where perhaps you could give me other approach/solution regarding "dynamic use" of generics on the Query. 
I created the question on: http://stackoverflow.com/questions/36495546/how-to-use-dapper-with-conditional-stringbuilder-query 
I really would appreciate the help.
Thank you very much.
