### ISSUE TITLE
QueryAsync<int> causes error "Specified cast is not valid." when sql return data of type numeric

### ISSUE THREAD

**Issue by toannguyen83** [StackExchange/dapper-dot-net#501]
Using Dapper version 1.42

For example, I have the following sql statement
`select (cast (1 as numeric))  -- simulating scenario when calling select scope_identity(), apparently scope_identity() return numeric type`

When I use the synchronous method "Query<int>", it works fine. However, when I use the async method "QueryAsync<int>", it throws an error Specified cast is not valid.

I believed the work around is making sure that the sql return is integer. So perhaps something in Query<int> code is helping me down casting numeric to int, but the code is not in QueryAsync<int>?

I attached the simple test program that replicate the issue. It requires visual studio 2015 and it's using microsoft localdb. I also have the screenshot of the end result of the console application.

[DapperBugReplication.zip](https://github.com/StackExchange/dapper-dot-net/files/211621/DapperBugReplication.zip)

![image](https://cloud.githubusercontent.com/assets/2815878/14408255/0c77eb52-feb2-11e5-90c2-75ec8fb21cfb.png)

**Comment by toannguyen83** [comment]
When I tested against the latest beta version "1.50.0-beta9", it's no longer happening.

**Comment by mgravell** [comment]
Awesome; procrastination wins again! No, seriously: I'm glad this is
already fixed.

**Comment by toannguyen83** [comment]
Haha. I'll go ahead and close the issue.
