### ISSUE TITLE
Performance Issues

### ISSUE THREAD

**Issue by andreujuanc** [StackExchange/dapper-dot-net#502]
Hello, 
Im curious about this project and got some test results.
It gets seriously slow when query has more and more columns.

Is this the expected behavior?

Thanks

Collected Data
1 Column Rows: 1442 = 112ms 
3 Column Rows: 1442 = 123ms 
5 Column Rows: 1442 = 126ms 
5 Column Rows: 1442 = 147ms 
10 Column Rows: 1142 = 238ms
13 Column Rows: 1442 = 239ms
16 Column Rows: 1442 = 241ms
21 Column Rows: 1442 = 321ms

**Comment by jamesholwell** [comment]
I don't want to step on the expert's toes here, but 21 columns is 21x times the amount of "data" to retrieve from the database and hydrate into the objects than your first test case, at only 3x the speed, that doesn't frighten me that much..?

Perhaps if you can provide some more detail about the shape of your query, your test rig, the objects you are hydrating and the code you are using?

**Comment by NickCraver** [comment]
@jamesholwell is correct here - we'll need to see what you're talking about and have more information to say what's wrong. We see performance numbers nowhere near that, but I have no idea what your bottleneck is without more information. The test rig and hardware setup/specs would be very helpful here...otherwise it's blind guessing.

**Comment by andreujuanc** [comment]
I did lots of different tests, and more or less it was the same result, when mapping with dapper it was slow.

I did set manually the data to compare:
Manual Casting WorkOrders Rows: 1442 = 57ms 
Using Dapper WorkOrders Rows: 1442 = 321ms 

I havent compare any other mapping library. I did some debugging, trying to find were the problem was.
Did with and without storeprocedures. With few and lots of properties on classes vs lots and few columns.

If this is the way it should be, then its ok. If not then maybe there is room for improvement? 
Ill download the project and check a bit closer.

I was not asking for help or anything , just reporting and just wondering if it was the current performance. 

BTW i used 1.4 and latest beta version. with same results.

**Comment by NickCraver** [comment]
@andreujuanc We can't help without your code and some information about the setup. To be blunt: there are *so many things* people do wrong with benchmarking or just straight up don't consider. We can't be of any further help without more information. I'd post your benchmark code here, the numbers you're posting aren't anything close to what would be expected.

**Comment by NickCraver** [comment]
Closing this out, since we can't help point out the issue without any code.
