### ISSUE TITLE
Dapper target netcoreapp1.0?

### ISSUE THREAD

**Issue by teilin** [StackExchange/dapper-dot-net#504]
Are there any plans of targeting netcoreapp1.0 for Dapper? I am using dnxcore50 and it works pretty well with Dapper, but I would love to be able to use the dotnetcli.

**Comment by mgravell** [comment]
Definitely plans. And if you look at the commit history, I think the last
commit+revert was updating (and reverting) the refs to handle that. The
problem is: rc2 is a mess right now, and there is no single configuration
that builds cleanly from any package feed. When that exists: we'll
absolutely want to re-package and re-publish.

Marc

**Comment by teilin** [comment]
Great.

**Comment by NickCraver** [comment]
Just an FYI: there's now a `netstandard` branch with a clean build if you want to try it out.

**Comment by la-yumba** [comment]
With RC2 now officially released, it would be good to merge the `netstandard` branch.

It just needs `netstandard1.3` to be changed to `netstandard1.5`

**Comment by NickCraver** [comment]
I'll get with Marc soon as kids are out the door here and get NuGet updated - I don't follow your `netstandard1.5` comment though, why would we need to change this?

**Comment by la-yumba** [comment]
this is what class libraries shoudl be written in according to the
documentation (as of today)
http://dotnet.github.io/docs/core-concepts/dnx-migration.html


Enrico Buonanno
---
email: enrico.buonanno@gmail.com
skype ID: enrico.buonanno
Tel: +34 632 333 865

**Comment by mgravell** [comment]
The 1.5 is the *minimum* for targeting *just* .NET core. If you *can* use a
lower netstandard level, that's fine - and your library can be used on a
wider set on consumers. Using a lower number is fine. No change is required
here. At very worst case, we could choose to add *both* as explicit, but I
don't think that is required.

On 19 May 2016 at 12:28, Enrico <notifications@github.com> wrote:

> this is what class libraries shoudl be written in according to the
> documentation (as of today)
> http://dotnet.github.io/docs/core-concepts/dnx-migration.html
>
>
> Enrico Buonanno
> ---
> email: enrico.buonanno@gmail.com
> skype ID: enrico.buonanno
> Tel: +34 632 333 865
>
>
> On Thu, May 19, 2016 at 12:04 PM, Nick Craver <notifications@github.com>
> wrote:
>
> > I'll get with Marc soon as kids are out the door here and get NuGet
> > updated - I don't follow your netstandard1.5 comment though, why would we
> > need to change this?
> >
> > —
> > You are receiving this because you commented.
> > Reply to this email directly or view it on GitHub
> > <
> https://github.com/StackExchange/dapper-dot-net/issues/504#issuecomment-220281433
> >
> >
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/504#issuecomment-220297803>
>



-- 
Regards,

Marc

**Comment by henkmollema** [comment]
You only need to target a higher .NETStandard if you need more API. Libraries should target the lowest as possible.

**Comment by la-yumba** [comment]
ok, I just migrated my own library to 1.5 as per docs, then in order to be
able to reference dapper I had to change it to 1.5 as well. (But I may well
be wrong, after all this is my 1st day grappling with this)


Enrico Buonanno
---
email: enrico.buonanno@gmail.com
skype ID: enrico.buonanno
Tel: +34 632 333 865

**Comment by NickCraver** [comment]
1.50-beta10 (supporting RC2) has been pushed to NuGet. Let us know if you have any issues!
https://www.nuget.org/packages/Dapper/1.50.0-beta10

**Comment by NickCraver** [comment]
1.50-rc3 supporting RTM is now on NuGet, and it will become the stable version tomorrow night if we find no issues. Closing this issue out.
