### ISSUE TITLE
Dapper DynamicParameters returning error

### ISSUE THREAD

**Issue by MrBananaGuard** [StackExchange/dapper-dot-net#509]
public class PersonDAL : OracleBase {

    public PersonDAL() : base() {
    }

    public PersonDAL(string connectionString) : base(connectionString) {
    }

    public const string ParamPersonID = ":personid";
    public const string ParamClassID = ":classid";
    private const string getPersonByClassAndID = "SELECT PERSON_ID AS PersonID, PERSON_DESCRIPTION AS PersonDescription, CLASS_ID AS ClassID FROM TABLE_PERSON WHERE PERSON_ID = " + ParamPersonID + "AND CLASS_ID = " + ParamClassID;

    public SystemModel GetModelByPersonID_ClassID(int classID, int personid) {
        DynamicParameter = new DynamicParameters();
        DynamicParameter.Add(ParamClassID, classID);
        DynamicParameter.Add(ParamPersonID, personid);
        return Connection.QuerySingle<SystemModel>(getPersonByClassAndID, DynamicParameter);
    }
}

Returns Error:

Invalid parameter binding
Parameter name: personidAND

**Comment by jamesholwell** [comment]
Please could you try adding an extra space before the AND 

 ```ID = " + ParamPersonID + " AND ```

**Comment by mgravell** [comment]
For reference:
http://stackoverflow.com/questions/36735189/dapper-dynamicparameters-returning-error

**Comment by claykaboom** [comment]
This issue can be closed as it is just malformed SQL.
