### ISSUE TITLE
when dapper support like petapoco column function

### ISSUE THREAD

**Issue by stalker2016** [StackExchange/dapper-dot-net#514]
Entity eg:
public class Person
{
   public long Id{get;set;}
}
Database ：
CREATE TABLE [dbo].[Person](
	[PID] [bigint] IDENTITY(1,1) NOT NULL,

this Entity Id how to mapper PID???

**Comment by afnpires** [comment]
Here you go:
http://stackoverflow.com/questions/8902674/manually-map-column-names-with-class-properties

**Comment by stalker2016** [comment]
thank you.I'm  try it
