### ISSUE TITLE
"Multiple assemblies with equivalent identity have been imported" when installing dapper into asp.net5 web application

### ISSUE THREAD

**Issue by bbsimonbb** [StackExchange/dapper-dot-net#517]
Installing dapper nuget into an empty asp.net5 Web Application gets me an error...

Error	CS1703	Multiple assemblies with equivalent identity have been imported: 'C:\Users\sby\.dnx\packages\System.Runtime\4.0.20-beta-22816\lib\net45\System.Runtime.dll' and 'C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\Facades\System.Runtime.dll'. Remove one of the duplicate references.

The error is the same whether I use dapper release or beta.

**Comment by NickCraver** [comment]
Which version of Dapper are you trying to use here? Those beta numbers look pretty far off.
