### ISSUE TITLE
Exception after first query in Postgresql

### ISSUE THREAD

**Issue by fishjimi** [StackExchange/dapper-dot-net#519]
Im using postgresql 9.4.1.The basic code below. Quering the first time is OK, but crashed when running twice. And Strangely,if I execute "INSERT" twice instead of "SELECT" ,The data has been inserted into database both,then crashed..
```
using (var conn = new NpgsqlConnection("Server=xxxxxxxxxxxx"))
{
    conn.Open();
    var foo = conn.Query("select * from test where id>=@id", new { id = 1 });
    conn.Close();
    conn.Dispose();
}

Message:"Exception while reading from stream"
And InnerException shows the connection looks like Server no response,

**Comment by BlackjacketMack** [comment]
What happens if you remove conn.Close() and conn.Dispose() (your 'using'
statement should account for both of those calls)?

**Comment by fishjimi** [comment]
@BlackjacketMack I have tried all the ways but nothing changed

**Comment by stevo-knievo** [comment]
I don't know that helps but should not look the connection string like this

`new NpgsqlConnection("Host=xxxxxxxxxxxx")`

instead of

> new NpgsqlConnection("Server=xxxxxxxxxxxx")

**Comment by fishjimi** [comment]
@stevo-knievo both "host" and "server" can be used,but still getting exception.
I hope you can try it ! please do me a favor

**Comment by fishjimi** [comment]
I have found the answer,
Im sorry ,It is Npgsql's problem with the latest stable version of 3.1.1 on 
http://www.nuget.org/packages/Npgsql/3.1.1
when I change to 3.1.0-alpha6	 or 3.0.7, it back to normal.....
