### ISSUE TITLE
For the NetStandard platform, Dapper isn't exposing the extensions on the IDbConnection

### ISSUE THREAD

**Issue by MoonStorm** [StackExchange/dapper-dot-net#520]
The extensions are not available on the lowest denominator, the IDbConnection, same as for the other platforms. ``IDbConnection`` is available in ``System.Data.Common`` package.

**Comment by mgravell** [comment]
Agreed, oh how I'm looking forward to getting rid of those using aliases
(the hack we used to make it work)

**Comment by NickCraver** [comment]
I'm working on this right now - XML comments are actually missing in the current NuGet package too. I need to add some to the new Parse methods. Expect a `-rc2.1` release on NuGet tonight or tomorrow. So far: `#if COREFX` occurrences are down from 54 to 26.

**Comment by NickCraver** [comment]
Still working on more updates, but relevant commit above: https://github.com/StackExchange/dapper-dot-net/commit/8e070ddca5dde5a3ffc94377c68ddd9cbccf68d0

**Comment by NickCraver** [comment]
@MoonStorm unfortunately NuGet doesn't support SemVer 2.0, so there's no `-rc2.1` release. Instead, there's a `-rc2a` up on NuGet which is back to interfaces: https://www.nuget.org/packages/Dapper/1.50.0-rc2a

**Comment by MoonStorm** [comment]
Awesome, thanks.

**Comment by mkeymolen** [comment]
@NickCraver 
> unfortunately NuGet doesn't support SemVer 2.0
i thought latest version of nuget (3.x) does support SemVer 2.0
