### ISSUE TITLE
Dapper.Contrib v1.50.0-beta8 not reading [Key] Attribute

### ISSUE THREAD

**Issue by CouchFrancois** [StackExchange/dapper-dot-net#522]
I'm getting the following exception when rewritting my app to .Net Core with Dapper.Contrib

> Get<T> only supports an entity with a [Key] or an [ExplicitKey] property

But as you can see below, the table has the [Key] attribute

```
public class tTestRuns
    {
        [Key]
        public int TestRunID { get; set; }
        public System.DateTime? TestRunDate { get; set; }
        ...
    }
```

**Comment by NickCraver** [comment]
What does your `project.json` look like? This will help me figure out what's up.

**Comment by CouchFrancois** [comment]
```
{
  "dependencies": {
    "Microsoft.NETCore.App": {
      "version": "1.0.0-rc2-3002702",
      "type": "platform"
    },
    "Microsoft.ApplicationInsights.AspNetCore": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Diagnostics": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "type": "build"
    },
    "Microsoft.AspNetCore.Server.IISIntegration": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.EnvironmentVariables": "1.0.0-rc2-final",
    "Microsoft.Extensions.Configuration.Json": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Console": "1.0.0-rc2-final",
    "Microsoft.Extensions.Logging.Debug": "1.0.0-rc2-final",
    "Microsoft.VisualStudio.Web.BrowserLink.Loader": "14.0.0-rc2-final",
    "Dapper": "1.50.0-rc2",
    "Microsoft.Extensions.Options.ConfigurationExtensions": "1.0.0-rc2-final",
    "Dapper.Contrib": "1.50.0-beta8",
    "Newtonsoft.Json": "8.0.4-beta1"
  },

  "tools": {
    "Microsoft.AspNetCore.Razor.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    },
    "Microsoft.AspNetCore.Server.IISIntegration.Tools": {
      "version": "1.0.0-preview1-final",
      "imports": "portable-net45+win8+dnxcore50"
    }
  },

  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dotnet5.6",
        "dnxcore50",
        "portable-net45+win8"
      ]
    }
  },

  "buildOptions": {
    "emitEntryPoint": true,
    "preserveCompilationContext": true
  },

  "runtimeOptions": {
    "gcServer": true
  },

  "publishOptions": {
    "include": [
      "wwwroot",
      "Views",
      "appsettings.json",
      "web.config"
    ]
  },

  "scripts": {
    "prepublish": [ "npm install", "bower install", "gulp clean", "gulp min" ],
    "postpublish": [ "dotnet publish-iis --publish-folder %publish:OutputPath% --framework %publish:FullTargetFramework%" ]
  }
}

```

**Comment by NickCraver** [comment]
I'm honestly not sure how beta8 would behave here at all across-platforms. It's working because of imports at the moment. I've uploaded a netstandard 1.3 build of `Dapper.Contrib` to NuGet, can you please give it a try? It's the rc2a release, here: https://www.nuget.org/packages/Dapper.Contrib/1.50.0-rc2a

I'm not saying this will necessarily fix it - it's possible the attribute enumeration isn't correct in core, but let's get on current code as a sanity check then make core adjustments as needed.

**Comment by CouchFrancois** [comment]
Installed but still getting the same error
![error](https://cloud.githubusercontent.com/assets/1000466/15687322/bac6ee06-2739-11e6-9a74-53d4f1fc08f3.png)

![image](https://cloud.githubusercontent.com/assets/1000466/15687364/eb7ab7bc-2739-11e6-903e-11eae158b463.png)

**Comment by joncloud** [comment]
I was able to reproduce this too, but I had to use `System.ComponentModel.DataAnnotations.KeyAttribute` instead of `Dapper.Contrib.Extensions.KeyAttribute`.  It looks like `SqlMapperExtensions` is looking explicitly for Dapper `KeyAttribute`.

@NickCraver Wasn't there a point in time that it looked for the name `"Key"` instead of the specific type?
@CouchFrancois which `KeyAttribute` are you using?

**Comment by hey-red** [comment]
Same problem.

**Comment by CouchFrancois** [comment]
Makes sense, the code I was porting used a different CRUD (SimpleCrud) that uses System.ComponentModel.DataAnnotations.KeyAttribute.  Somehow I always knew it was my issue

**Comment by rhubley** [comment]
> I was able to reproduce this too, but I had to use System.ComponentModel.DataAnnotations.KeyAttribute instead of Dapper.Contrib.Extensions.KeyAttribute. It looks like SqlMapperExtensions is looking explicitly for Dapper KeyAttribute.

This used to be the case, I think the "ExplicitKey" work changed that behaviour.
