### ISSUE TITLE
Sql Server 2014 Stored Proc with Try Catch Throw doesn't throw exception in c#

### ISSUE THREAD

**Issue by SeeWhat** [StackExchange/dapper-dot-net#525]
We had an issue where a stored proc wasn't working as expected, it was being called but not giving the results as expected. When executing it directly we saw a SQL error however that error wasn't appearing within the code.

The below is a simple way to reproduce the issue which occurred, resulting is no exception being raised within the application.

The stored proc as below will raise a SqlException in C# when called with Dapper via 
connection.Query

```SQL
CREATE PROCEDURE [dbo].[TestException] AS
	SELECT 'test', convert(nvarchar(2),123)
GO
```

however if the stored proc contains a try catch, then no exception is throw.

```SQL
CREATE PROCEDURE [dbo].[TestException]
AS
BEGIN
	BEGIN TRY
		SELECT 'test', convert(nvarchar(2),123)
	END TRY
	BEGIN CATCH
		THROW;
	END CATCH
END
GO
```

A quick investigation shows that within QueryImpl, removing CommandBehavior.SingleResult from the call to ExecuteReaderWithFlagsFallback will result in an exception when reader.NextResult() is called.

Calling it via QuerySingle or QueryFirst results in "InvalidOperationException: Sequence contains no elements" rather than a SqlException

**Comment by mgravell** [comment]
Closing as addressed by #563; I realise #525 was earlier, but all the comments / details etc are over there.
