### ISSUE TITLE
Dapper.Contrib Insert Fails identity column

### ISSUE THREAD

**Issue by ishamfazal** [StackExchange/dapper-dot-net#526]
### Cannot insert the value NULL into column 'Id', table 'Infusion.dbo.StockReference'; column does not allow nulls. INSERT fails.The statement has been terminated.
check the below images 

![2](https://cloud.githubusercontent.com/assets/11960696/15714898/1444684a-283a-11e6-996a-ed8693d4e2e6.jpg)
![3](https://cloud.githubusercontent.com/assets/11960696/15714899/144659de-283a-11e6-820d-5e6050573a7e.jpg)
![1](https://cloud.githubusercontent.com/assets/11960696/15714900/144e1d40-283a-11e6-9fa9-1b1ef9eaead1.jpg)
![4](https://cloud.githubusercontent.com/assets/11960696/15715057/aff24ac8-283a-11e6-9fe1-ee30ee317270.jpg)
![5](https://cloud.githubusercontent.com/assets/11960696/15715056/afe8415e-283a-11e6-9028-826d10f0c596.jpg)

The id column is an identity column but i keep getting the above error, i tried both ways assigning a value for Id and not assigning a value for the Id but still it doesn't work any thoughts? or am i missing something.

**Comment by ishamfazal** [comment]
@mgravell

**Comment by joncloud** [comment]
@ishamfazal how is `StockReference` defined exactly in the database?  Does `StockReference.Id` have an Identity Specification?

**Comment by ishamfazal** [comment]
@joncloud Thanks for your reply. i fixed the error

**Comment by JohnnyFun** [comment]
For posterity, the issue (for me anyway) was that I had specified `[Key]`, instead of `[ExplicitKey]`. I had a one-to-one relationship table. 

Thanks to joncloud for pointing me in the right direction.

**Comment by johnscott999** [comment]
Also  for posterity, I had the same message when I had decorated my poco class id property with `System.ComponentModel.DataAnnotations.KeyAttribute` instead of `Dapper.Contrib.Extensions.KeyAttribute`. if you don't fully qualify the attribute this is very easy to miss.
