### ISSUE TITLE
How to page

### ISSUE THREAD

**Issue by iZhongCheng** [StackExchange/dapper-dot-net#527]
How to page ？
如何分页

**Comment by pianzide1117** [comment]
page with your sql
用sql呗

**Comment by mgravell** [comment]
Ultimately, that comes down to your flavor of SQL. If you are using any
recent version of SQL Server, then you would use OFFSET and FETCH, passing
in the numbers to use as parameters. What database are you using? I might
be able to do a more concrete example.

On 2 June 2016 at 05:00, 俞坤 <notifications@github.com> wrote:

> page with your sql
> 用sql呗
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/527#issuecomment-223189918>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AABDsNoNuCibMtZgzSjy2snHrFOThU-Pks5qHlVwgaJpZM4IsKFt>
> .
>



-- 
Regards,

Marc

**Comment by vgrund** [comment]
Offset and fetch can be used if the version of database is mssql 2012 or latest. How to Page if we are using mssql 2005?

**Comment by mgravell** [comment]
The ROW_NUMBER() / OVER(ORDER BY...) would be the first that leaps to kind,
but again: this is a TSQL question, not a dapper one.

**Comment by vgrund** [comment]
I have to agree.
