### ISSUE TITLE
how use in .net core rc2? 

### ISSUE THREAD

**Issue by zhfish** [StackExchange/dapper-dot-net#528]
mysql provider:
https://github.com/SapientGuardian/mysql-connector-net-netstandard
https://www.nuget.org/packages/SapientGuardian.MySql.Data/

i don't understand how to connect to mysql with dapper?

**Comment by mgravell** [comment]
Ultimately, dapper works on the connection object. So; spin up a
MySqlConnection instance (in the usual way), and use dapper's extension
methods *on the connection*. Once you have a connection instance, usage is
the same as for any other dapper example.

On 2 June 2016 at 11:40, zhfish <notifications@github.com> wrote:

> mysql provider:
> https://github.com/SapientGuardian/mysql-connector-net-netstandard
> https://www.nuget.org/packages/SapientGuardian.MySql.Data/
>
> i don't understand how to connect to mysql with dapper?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/528>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AABDsM1GqliLoEDkTF-9AIPoy0K7H7Zcks5qHrM3gaJpZM4IsbMD>
> .
>



-- 
Regards,

Marc

**Comment by NickCraver** [comment]
Closing this out due to no response, @zhfish if you're still having trouble ping back and we'll see what the issue is.
