### ISSUE TITLE
Dapper.EntityFramework.StrongName for .NET 4.0 has no strong name

### ISSUE THREAD

**Issue by cremor** [StackExchange/dapper-dot-net#537]
The NuGet package Dapper.EntityFramework.StrongName contains two assemblies. The one for .NET 4.5 is fine (has a strong name). But the one for .NET 4.0 has no strong name.

**Comment by mgravell** [comment]
Well that's just an embarrassing level of fail by us! I've checked and
1.50.0-rc2b is also impacted, but luckily I haven't uploaded that to nuget
yet. I'll fix it and upload 1.50.0-rc2b. That work?

On 15 June 2016 at 08:28, cremor <notifications@github.com> wrote:

> The NuGet package Dapper.EntityFramework.StrongName contains two
> assemblies. The one for .NET 4.5 is fine (has a strong name). But the one
> for .NET 4.0 has no strong name.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/StackExchange/dapper-dot-net/issues/537>, or mute the
> thread
> <https://github.com/notifications/unsubscribe/AABDsK6YretS_CtJhTA84KkiTAogs8ouks5qL6mugaJpZM4I2Ehg>
> .
>



-- 
Regards,

Marc

**Comment by mgravell** [comment]
k,
https://www.nuget.org/packages/Dapper.EntityFramework.StrongName/1.50.0-rc2b
has been uploaded. Note: the "prerelease" here is only because this set of
builds is also starting to support core-clr which isn't released; but since
you're targeting .net 4.0, the "prerelease" aspect does not apply and you
should be fine to use it.

On 15 June 2016 at 10:25, Marc Gravell <marc.gravell@gmail.com> wrote:

> Well that's just an embarrassing level of fail by us! I've checked and
> 1.50.0-rc2b is also impacted, but luckily I haven't uploaded that to nuget
> yet. I'll fix it and upload 1.50.0-rc2b. That work?
>
> On 15 June 2016 at 08:28, cremor <notifications@github.com> wrote:
>
>> The NuGet package Dapper.EntityFramework.StrongName contains two
>> assemblies. The one for .NET 4.5 is fine (has a strong name). But the one
>> for .NET 4.0 has no strong name.
>>
>> —
>> You are receiving this because you are subscribed to this thread.
>> Reply to this email directly, view it on GitHub
>> <https://github.com/StackExchange/dapper-dot-net/issues/537>, or mute
>> the thread
>> <https://github.com/notifications/unsubscribe/AABDsK6YretS_CtJhTA84KkiTAogs8ouks5qL6mugaJpZM4I2Ehg>
>> .
>>
>
>
>
> --
> Regards,
>
> Marc
>



-- 
Regards,

Marc

**Comment by mgravell** [comment]
(closing, but feel free to re-open if there's still a problem)
