### ISSUE TITLE
Can not resolve NETStandard.Library >= 1.5.0-rc2-24027 after adding Dapper to the project

### ISSUE THREAD

**Issue by teilin** [StackExchange/dapper-dot-net#542]
Hi,

At one of dotnet core library projects I have, I have error message that I get on build.

> The dependency NETStandard.Library >= 1.5.0-rc2-24027 could not be resolved

I am using NETStandard.Library with the same version in a couple of other projects as well. The other projects are dependencies to the project that I am getting this issue at.

After spending a lot of time trying to resolve this, I started a blank dotnet core project and buildin it up again to see where I hit this error. Looks like it is when I add the dependency to Dapper. If I remove Dapper, it works fine, but as soon as I add the Dapper dependency and start using it, I get the error.

I have tried **Dapper dot net 1.50.0-rc2b** and **Dapper dot net 1.50.0-rc2**. My project.json looks like the following:

```
{
  "version": "1.0.0-dev-*",
  "name": "XXX.Repositories.Test",
  "description": "XXX",
  "authors": [ "XXX" ],
  "dependencies": {
    "NetStandard.Library": "1.5.0-rc2-24027",
    "XXX.Buffering": "1.0.0-dev-72",
    "XXX.Domain": "1.0.1-dev-23",
    "System.Data.SqlClient": "4.1.0-rc2-24027",
    "Dapper": "1.50.0-rc2"
  },
  "frameworks": {
    "netstandard1.3": {}
  }
}
```

I have tried to clear the nuget cache and manually deleteing the project.lock.json file. Also deleted the bin and obj folder just in case. Can not see why this is not working.

Little edit: Started the project in Visual Studio and while it was restoring packages I get the same error there, but if I double click the error message, it is the Dapper dependency in the project.json that have the red line. This is a really small project that is stripped for everything, but I get the error here until I remove Dapper from dependencies. https://github.com/teilin/NetstandardLibraryError

Any ideas why I get this?

**Comment by teilin** [comment]
I see that there are a rc3 version Dapper available now. This version has fixed the issue that I pointed out. Tested out updating the reference in the test project I linked and it is working fine with the rc3 version. Thanks a lot. Just closing this issue.

**Comment by NickCraver** [comment]
\o/ Glad it works for you! 1.50 will land tomorrow night if no one finds any issues - we're overdue for a stable release.

**Comment by teilin** [comment]
The rc3 package is working, but if I use the latest stable (1.50), I get the same error while doing restore.

> Severity	Code	Description	Project	File	Line	Suppression State
> Error	NU1001	The dependency NETStandard.Library >= 1.5.0-rc2-24027 could not be resolved.

**Comment by teilin** [comment]
I see that this is not happening in the 1.50.1 version, so I am closing the issue now.
