### ISSUE TITLE
New Stable Release for Nuget?

### ISSUE THREAD

**Issue by markjerz** [StackExchange/dapper-dot-net#543]
Hi,

Just wondering whether it would be possible to push a new stable (as in nuget stable) release for dapper including all bug fixes un-related to .net core support?

Our downstream nuget package (with a dependency on dapper) now has to also be in pre-release state as it needs the bug fix (fix incorrect cast in QueryAsync<T> (@phnx47, #346)) introduced in 1.50-beta1 in order to function properly. 

Just throwing it out there! - not sure how many other packages there are that depend on dapper in a similar way (and appreciate your time is precious.)

**Comment by NickCraver** [comment]
I have pushed 1.50-rc3 for .NET Core RTM...if we find no issues by tomorrow night I'll bump it to 1.50 :)

**Comment by markjerz** [comment]
Awesome! Thanks
