### ISSUE TITLE
How use dapper dot net on asp net core?

### ISSUE THREAD

**Issue by yozawiratama** [StackExchange/dapper-dot-net#544]
Honestly i dont like EF, i really love dapper dot net. and now i working with asp net core with mac osx
How use dapper dot net on asp net core?

**Comment by NickCraver** [comment]
There's now very little difference between Core and .NET Core with Dapper usage - grab 1.50-rc3 which references the .NET Core RTM packages to get started - I'll bump it to 1.50 (no pre-release) if there are no issues found in the next few days.

**Comment by techbrij** [comment]
I like dapper dot net. Here is the sample with asp.net core, dapper dot net and postgresql.
[http://techbrij.com/asp-net-core-postgresql-dapper-crud](http://techbrij.com/asp-net-core-postgresql-dapper-crud)

**Comment by NickCraver** [comment]
Closing out to cleanup

**Comment by xiangxingze** [comment]
asp.net core+dapper+Respoistory  该怎么搭框架？特别是在 数据库 链接的时候没有思路

**Comment by bidianqing** [comment]
@xiangxingze  看一下这个项目 https://github.com/bidianqing/AspNetCoreUseDapper  Repository层可以酌情封装一些方法
