### ISSUE TITLE
.net core with Kestrel - Incomplete Chunked Encoding

### ISSUE THREAD

**Issue by CaseyHaralson** [StackExchange/dapper-dot-net#548]
I'm running in to a problem using .net core, mvc api, kestrel, and dapper. I think I have limited the problem to just dapper being referenced in the project.json. I have an api that returns a string and everything is good (when dapper isn't referenced). Then when I hit the same api after referencing dapper, I get the incomplete chunked encoding problems. It looks like the last chunk isn't being returned.

Btw, thanks for this repo!

**project.json:**
{
  "buildOptions": {
    "emitEntryPoint": true,
    "debugType": "portable"
  },
  "dependencies": {
    "Microsoft.NETCore.App": {
      "type": "platform",
      "version": "1.0.0-rc2-3002702"
    },
    "Microsoft.AspNetCore.Server.Kestrel": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.StaticFiles": "1.0.0-rc2-final",
    "Microsoft.AspNetCore.Mvc": "1.0.0-rc2-final",
    "Dapper": "1.50-rc3"
  },
  "frameworks": {
    "netcoreapp1.0": {
      "imports": [
        "dnxcore50"
      ]
    }
  }
}

**Startup.cs:**
ConfigureServices 
{
  services.AddMvc();
}
Configure
{
  app.UseDefaultFiles();
  app.UseStaticFiles();
  app.UseMvc();
}

**Program.cs:**
Main
{
  var host = new WebHostBuilder()
            .UseKestrel()
            .UseContentRoot(Directory.GetCurrentDirectory())
            .UseStartup<Startup>()
            .Build();
host.Run();
}

**Api TestController.cs:**
[Route("")]
[HttpGet]
public string GetValue()
{
  return "You got a test value!";
}

**Comment by NickCraver** [comment]
Dapper `1.50-rc3` (soon to be final) references the RTM libraries...mixing RC2 and RTM is always going to yield some unpredictable behavior. I'd either reference dapper `1.50-rc2b` (which is at RC2 level), or better: update all your package references and tooling to RTM, and see if the issue persists.

**Comment by CaseyHaralson** [comment]
That worked! I didn't realize the naming convention. Many thanks!
