### ISSUE TITLE
"Could not find stored procedure xxx" error if connecting to SQL Server database with non default port 1434

### ISSUE THREAD

**Issue by tuyennguyencanada** [StackExchange/dapper-dot-net#557]
I could call stored procedures successfully when connecting to SQL Server database with default port 1433. (I don't specify port number in connection string).

However when I connect to a different database using non default port 1434, I received error "Could not find stored procedure xxx"
The connection string I used is as followed:
"Data Source=sqlserver, 1434; Initial Catalog = mydb; Persist Security Info=True;User ID = usr; Password=pw"

I could execute a query like "Select * From customers" using the above connection string.

**Comment by DarekDan** [comment]
Which database schema do you default to? And could you post some code how you are trying to execute the SP?

**Comment by tuyennguyencanada** [comment]
Below is my method, I've tried with "dbo.usp_CustomerLogin" and "usp_CustomerLogin"
Connection string is : "Data Source=sqlserver, 1434; Initial Catalog = mydb; Persist Security Info=True;User ID = usr; Password=pw"
```
public WebResponse CustomerLogin(WebRequest request)
        {
            WebResponse response;
            using (IDbConnection db = new SqlConnection(connectionString))
            {
                try {
                    var parameters = new DynamicParameters();
                    Customer customer = (Customer)request.Data;
                    parameters.Add(@"Email", customer.Email);
                    parameters.Add(@"Password", customer.Password);
                    parameters.Add(@"LastIPAddress", customer.ClientIPAddress);
                    customer = db.Query<Customer>("**dbo.usp_CustomerLogin**", param: parameters, commandType: CommandType.StoredProcedure).FirstOrDefault();
                    response = new WebResponse(customer, string.IsNullOrEmpty(customer.Token)?"Incorrect email or password!":"Login successfully!");
                }
                catch (Exception ex)
                {
                    response = new WebResponse(HttpReponseCode.Failure,ex.Message,null);
                }
            }
           
```

**Comment by tuyennguyencanada** [comment]
This works for me, calling a query to get all user stored procedure
```
(1)
List<string> sp = db.Query<string>("SELECT routine_name FROM nw.information_schema.routines  WHERE routine_type = 'PROCEDURE'", param: parameters, commandType: CommandType.Text).ToList();
```
and this works for me (calling system stored procedure)
```
var who = db.Query("dbo.sp_who2", commandType: CommandType.StoredProcedure).FirstOrDefault();
```
but calling user created stored procedure fail, (1) return a list of stored procedure I've created and I could see "dbo.usp_CustomerLogin" is on the list.
```
customer = db.Query<Customer>("dbo.usp_CustomerLogin", param: parameters, commandType: CommandType.StoredProcedure).FirstOrDefault();
```
I've deleted the space before the port number but the issue still persists.

**Comment by DarekDan** [comment]
Check if the account you are logging in with has enough privileges to run the SP. What happens if you try executing the SP using standard `SqlCommand` instead of Dapper?

**Comment by tuyennguyencanada** [comment]
I've just tried with SqlCommand and have the same error, **looks like this issue is not related to Dapper**.

I'v also tried execute the query using "sa" account and it also failed.

I've decided to use the default port 1433 and everything is working fine. I will not spend more time in this issue. Thank you DarekDan for your help.

**Comment by DarekDan** [comment]
I know you closed it, and this might be a stupid question, but, in your sample code, what is the purpose of the two asterisks before and after your SP name?

**Comment by tuyennguyencanada** [comment]
I tried to **bold** the SP name using markdown but the <code> section ignore this format, hence you could see the two asterisks.
