### ISSUE TITLE
Version 1.50.1 is not compatible with Swashbuckle

### ISSUE THREAD

**Issue by xavierpena** [StackExchange/dapper-dot-net#564]
Version 1.50.1 (marked in NuGet as "latest stable") makes Swashbuckle crash. Project page: http://swagger.io/.

Version 1.50.0 works just fine.

Tested on a ASP.NET Core API project.

The so called "crash" is: when you reach the Swagger UI (via http://localhost:XXXXX/swagger/ui/index.html ) the UI doesn't load correctly.

I have no idea about how or why, specially I don't know how those apparently disconnected dll's can interact together, but I thought I would report the issue in case there is a deeper concern coming from this symptom.

**Comment by mgravell** [comment]
I'm not aware of anything specific that should impact this. In fact, the only difference between 1.50.0 and 1.50.1 is an internal implementation detail that probably isn't being hit. So; my most immediate thought would be "assembly load fail". So; questions:

- are you using the strong-named package (`Dapper.StrongName`)? or the non-strong-named package? (`Dapper`)
- if you are using the strong-named package, is there an assembly binding redirect (which should be added autoatically by nuget) to 1.50.1 ?
- but more generally, is there anything in the server logs, event logs, or yellow-screen-of-death text that would tell us what it is unhappy about?

**Comment by NickCraver** [comment]
Perhaps this was a strong-name/specific-version loading issue?

Closing since there's no update here, but feel free to ping for reopen
