### ISSUE TITLE
'IDbConnection' does not contain a definition for 'QueryMultiple' 

### ISSUE THREAD

**Issue by zaktecs** [StackExchange/dapper-dot-net#566]
Hi , I'm trying to use dapper 1.50 in my aspnet core 1 project, but I keep getting the following error when I try to return multiple results

'IDbConnection' does not contain a definition for 'QueryMultiple' and no extension method 'QueryMultiple' accepting a first argument of type 'IDbConnection' could be found (are you missing a using directive or an assembly reference?)   sims.Service..NETStandard,Version=v1.6  

============ Connectionstring
 public static string ConnectionString = @"";
        private SqlConnection _connection;

```
    private SqlConnection connection => _connection ?? (_connection = GetOpenConnection());

    static BizHelper()
    {

    }

    public static SqlConnection GetOpenConnection(bool mars = false)
    {
        var cs = ConnectionString;
        if (mars)
        {
            var scsb = new SqlConnectionStringBuilder(cs)
            {
                MultipleActiveResultSets = true
            };
            cs = scsb.ConnectionString;
        }
        var connection = new SqlConnection(cs);
        connection.Open();
        return connection;
    }
```

================= controller
 public IEnumerable<StudentDTO> GetAllStudentsPerSchool(long schoolId)
        {

```
        string sql = @"ProcGetAllStudentsPerSchool";
        using (IDbConnection cn = GetOpenConnection(true))
        {
            var cp = new DynamicParameters();
            cp.Add("@Id", dbType: DbType.Int32, direction: ParameterDirection.Input, value: schoolId);
            // cn.Open();
            var statt = cn.QueryMultiple<StudentDTO,ParentsGuardian>(sql, cp, commandType: CommandType.StoredProcedure);
            return statt;
        }


        //return StudentDTODtoList;
    }
```

Many thanks

**Comment by mgravell** [comment]
do you have `using Dapper;` at the start of the file?

**Comment by zaktecs** [comment]
Yes.  Please see below my reference

using Dapper;
using sims.Model;
using sims.Service.Abstract;
using sims.Services;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Threading.Tasks;
using System;
using System.Linq;

Many thanks
zak

**Comment by mgravell** [comment]
I don't mean to keep asking the same question, but that is in the same file as the code that is complaining, yes? I've just set up a new "ASP.NET Core Web Application (.NET Core)" from VS using the template, ran `install-package Dapper` in the Package Manager Console (it installed 1.50.1), and added the following to the files:

        using Dapper;

       ...

        public IActionResult About()
        {
            IDbConnection connection = GetConnection();
            using (var reader = connection.QueryMultiple("blah blah"))
            {
                var foo = reader.Read<int>();
                var s = reader.ReadSingle<string>();
            }
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        private IDbConnection GetConnection()
        { // don't need this to check whether it compiles
            throw new NotImplementedException();
        }

It compiles just fine. So my hunch is (one of):

- dapper is not installed (check the references)
- there is a missing `using` directive (check the specific file that is failing)

It is also possible that it is an **old version** of dapper that is installed. Prior to RTM, we had to expose the methods on `DbConnection`, not `IDbConnection` (because `IDbConnection` didn't exist in "core" until RTM). This has been changed for 1.50.0 and above, but if you are using one of the previous alpha builds, then indeed there is no extension method on `IDbConnection`.

**Comment by zaktecs** [comment]
Thanks Marc, I did install 1.50 from nuget. Do you mind if I ask you to send me your sample project. Many thanks. Zak

-----Original Message-----

**Comment by NickCraver** [comment]
@zaktecs is this still an issue on latest? Newest .NET Core bits totally reverted to the interfaces proper. Before it *really* only worked with `DbConnection` (a limitation of Core), that's no longer the case as the interfaces are back.

**Comment by zaktecs** [comment]
@NickCraver all is fine now. thanks for checking.

**Comment by zaktecs** [comment]
@NickCraver thanks for your support. much appreciated

**Comment by ceemafour** [comment]
I've just run into the same issue (Core 2.1.0, Dapper 1.50.5)

// usings
using Dapper;
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.SqlClient;
using System.Threading.Tasks;

`using (var connection = new SqlConnection(@"data source=source;initial catalog=catalog;MultipleActiveResultSets=True;"))
            {
                await connection.OpenAsync();
                result = await connection.QueryMultipleAsync<IEnumerable<User>>("GET_Users",
                                null,
                                commandType: CommandType.StoredProcedure);

            }`

I get compile error:

'SqlConnection' does not contain a definition for 'QueryMultipleAsync' and no extension method 'QueryMultipleAsync' accepting a first argument of type 'SqlConnection' could be found (are you missing a using directive or an assembly reference?)

**Comment by mgravell** [comment]
@ceemafour are you sure you aren't after simply `QueryAsync<T>`?

**Comment by ceemafour** [comment]
Hi @mgravell,
I’ve just started with Dapper and picked up the sample from the tutorial.

**Comment by mgravell** [comment]
Maybe but that's a specific scenario. What you show looks more like a
`QueryAsync<T>` usage. Can you link to the place you are seeing this
example?

**Comment by ceemafour** [comment]
http://dapper-tutorial.net/async#querymultipleasync

**Comment by mgravell** [comment]
OK, that's nothing to do with us or dapper. That's an independent site
(that is trying to sell you something), not affiliated with dapper **in any
way**.

The only relevant question is: how many result grids does your query
return? If one: you want `Query`/`QueryAsync`.

**Comment by ceemafour** [comment]
Thabks for pointing that out. 
My proc returns two result sets of hich I’m trying to read using QueryMultipleAsync.
