### ISSUE TITLE
QuerySingle does not work when there is data

### ISSUE THREAD

**Issue by kbilsted** [StackExchange/dapper-dot-net#584]
I get the error

```
System.MissingMethodException

Method not found: '!!0 Dapper.SqlMapper.QuerySingle(System.Data.IDbConnection, System.String, System.Object, System.Data.IDbTransaction, System.Nullable`1<Int32>, System.Nullable`1<System.Data.CommandType>)'.

   at My.Code.Service.Queue.GetSubscriptionBaseid.Execute(IDbTransaction transaction, Guid accountId)
```

My query is 

```
			var sql = @"SELECT Id
				FROM SubscriptionBaseTable
				WHERE AccountId = @accountId";

			var result = transaction.Connection.QuerySingle<Guid?>(sql, new {AccountId = accountId}, transaction);
```

it works when
  * Using `Query<Guid?>(..).FirstOrDefault()`
  * When there is no data i the table

**Comment by mgravell** [comment]
That sounds like a build error at your end, specifically that you are
somehow deploying an older version of dapper. Please check what version is
**deployed**.

**Comment by kbilsted** [comment]
Its during unit testing. It turned out that I was using dapper for setting up data for some integration tests. That version was 1.40.0 while the production code was using dapper 1.50.2 

sorry for wasting your time.
