### ISSUE TITLE
Problem with GetAll<> resulting on (Method not found: 'System.Collections.Generic.List`1<!!0>)

### ISSUE THREAD

**Issue by stanleyipc** [StackExchange/dapper-dot-net#590]
Hello friends,

Now I'm working with dapper and I just have good things to say about this amazing tool. But, a few days ago I'm trying to use the Dapper.Contrib library (CRUD is so good :dancers: ), but the problem appeared:

First, the considerations:
- Now I'm using PETAPOCO for generated the class (I have the same problem with class generetad from Entity Framework)
- Dapper Version: 1.12.0.0
- Dapper.Contrib Version: 1.50.0.0
- Microsoft Visual Studio Community 2015 Version 14.0.2542201 Update 3
- Target Framework: .NET Framework 4.5

**The Error:
_Message_:** Method not found: 'System.Collections.Generic.List`1<!!0> Dapper.SqlMapper.AsList(System.Collections.Generic.IEnumerable`1<!!0>)'.
![getall_error](https://cloud.githubusercontent.com/assets/20667839/18008808/07481b4e-6b80-11e6-9ef2-2f55f2c43069.jpg)

**The "admusuario" class:**
![admusuario_poco](https://cloud.githubusercontent.com/assets/20667839/18008827/18001180-6b80-11e6-966e-a848772160d4.jpg)

Thanks in advance.

:sos:

**Comment by NickCraver** [comment]
Are you *sure* you're targeting .Net 4.5? That looks like some core CLR goodness creeping in and a library issue relating to cross-platform.

**Comment by stanleyipc** [comment]
@NickCraver I have sure. Look:
![target](https://cloud.githubusercontent.com/assets/20667839/18287604/2940729c-744e-11e6-871b-7ce0d8ad7134.jpg)

Do you have any idea? I'll try change .NET targeting to lastest versions and see what'll happen

**Comment by stanleyipc** [comment]
@NickCraver Hey, I find the problem. I was looking step by step until I noticed that my Dapper version was 1.12 (very old), so I update for last version 1.50 and the problem was solved.
