### ISSUE TITLE
database dependency when running tests

### ISSUE THREAD

**Issue by mjashanks** [StackExchange/dapper-dot-net#594]
This is probably lack of understanding - but would appreciate some help! ....

I am trying to run the test suite via `dotnet test` . The tests run, provided you merge https://github.com/StackExchange/dapper-dot-net/pull/593

However, they fail, as they are looking for a local SQL Server database. Can i not run tests without setting up this dependency ?

I suspect it has something to do with the SkippableFact stuff - but I couldn't really get my head round what was going on here. 

(If it matters to you, I am working on adding configurable column mappings - in a pluggable, non-opinionated way ... https://github.com/mjashanks/dapper-dot-net/commits/master )

**Comment by mgravell** [comment]
There are some in-memory DBs, but ultimately the tests are more useful **to us as maintainers** as integration tests that use databases that are configured roughly as they would "for real" - especially when it comes to specific features. I'm open to options on ways to do this better, but... I can't say it is high on my list of priorities to remove the need to have database servers locally when developing dapper.

**Comment by mjashanks** [comment]
Ok then. No problem. I do have a SQL Server instance installed - so i can run tests against that just. Thanks for the info.
