### ISSUE TITLE
parameters with special characters (æøå)

### ISSUE THREAD

**Issue by dennismi** [StackExchange/dapper-dot-net#601]
the "smellsLikeOleDb" regex in version 1.42 (i know it is an old version - but cannot upgrade right now) does not take into account any special characters (æøå) in parameter names.

Well atleast as far as i can see that is the problem. I may have been fixed in later versions but as of now, we cannot upgrade right now - we have tried, and we need to make a focused effort to do it.

Am i wrong in my findings?

regards
Dennis

**Comment by mgravell** [comment]
You're not wrong; I don't know what DB/provider  you're using, but for SQL Server, it is [defined as](https://msdn.microsoft.com/en-us/library/ms175874.aspx):

> A letter as defined by the Unicode Standard 3.2. The Unicode definition of letters includes Latin characters from a through z, from A through Z, and also letter characters from other languages.

That means I can *probably* switch to `\p{L}` in the regex; will have a look

**Comment by mgravell** [comment]
It isn't just `smellsLikeOleDb` impacted - other re too; but fix looks simple - pushing in a moment
