### ISSUE TITLE
a key property can't be insert

### ISSUE THREAD

**Issue by qq1211178784** [StackExchange/dapper-dot-net#604]
public class User
{
   [Dapper.Contrib.Extensions.Key]
    string UserCode { get; set; }
    string Name { get; set; }
    int Age { get; set; }
}
I failed to insert an User (the User.UserCode is  generated random) because a property with [Dapper.Contrib.Extensions.Key] is ignored.this is unreasonable。
SO。。。
I think  a property with [DatabaseGenerated(DatabaseGeneratedOption.Identity)] should be ignore

**Comment by imyundong** [comment]
![20160918113034](https://cloud.githubusercontent.com/assets/9474811/18612703/591c01e0-7d93-11e6-96f3-f3184d3a04cc.png)

**Comment by qq1211178784** [comment]
So It was designed to work that way ,I changed to dapper method instead of Dapper.Contrib's INSERT method
