### ISSUE TITLE
Allow FormCollection to be passed into dapper as is

### ISSUE THREAD

**Issue by dbol55** [StackExchange/dapper-dot-net#608]
public IActionResult MyForm(FormCollection form)
{
       dapper.Query("INSERT INTO.....", form);
}

**Comment by mgravell** [comment]
FormCollection is an MVC UI component - we're not going to take a reference
to that. It would perhaps be possible to map the base type, but I wonder if
it isn't easier for you to populate a dictionary from the form. That will
already work.

**Comment by mkonstan** [comment]
Hi dbol55,

You can simply create a helper library to solve this. However be aware that FormCollection is multi value collection hence you must consider using direct pass through carefully. See simplistic implementation below. There is no reason to implement it in Dapper.

static class SqlMapperHelpers
{
	/// <summary>
	/// Executes a query, returning the data typed as per T
	/// </summary>
	/// <returns>A sequence of data of the supplied type; if a basic type (int, string, etc) is queried then the data from the first column in assumed, otherwise an instance is
	/// created per row, and a direct column-name===member-name mapping is assumed (case insensitive).
	/// </returns>
	public static IEnumerable<T> Query<T>(
		this IDbConnection cnn, string sql, NameValueCollection param, IDbTransaction transaction = null, bool buffered = true, int? commandTimeout = null, CommandType? commandType = null
	)
	{
		var p = new Dapper.DynamicParameters();
		// Gets the values associated with the specified key from the NameValueCollection combined into one comma-separated list.
		foreach (var o in param.AllKeys.Select(key => new { key, v = param.Get(key) }))
		{
			p.Add(o.key, o.key);
        }
		return cnn.Query<T>(sql, p, transaction, buffered, commandTimeout, commandType);
	}
	
	public static IEnumerable<dynamic> Query(
		this IDbConnection cnn, string sql, NameValueCollection param, IDbTransaction transaction = null, bool buffered = true, int? commandTimeout = null, CommandType? commandType = null
	)
	{
		return cnn.Query<dynamic>(sql, param, transaction, buffered, commandTimeout, commandType);
	}
}

**Comment by dbol55** [comment]
Dictionary is fair enough, altough it would be nice as is.
