### ISSUE TITLE
Transaction

### ISSUE THREAD

**Issue by dbol55** [StackExchange/dapper-dot-net#614]
Include transaction, so I dont have to manually add it to the extension method.

**Comment by mgravell** [comment]
Define "include transaction"? Note: at one point someone did some work to add the API surface as extension methods on the transaction, but it quickly becomes quite  a huge amount of work. Compare that to "pass it into the existing API" and the latter soon becomes tempting...

Of course, if you only use about 3 methods, you can add your own extension methods locally:

    static Whatever Foo(this ITransaction transaction, ...)
    {
        return tran.Connection.Foo(..., transaction: transaction);
    }

**Comment by dbol55** [comment]
I understand, I fixed it locally so I dont have to pass my transaction for every call.
