### ISSUE TITLE
Parameters not being replaced using SqlBuilder

### ISSUE THREAD

**Issue by matthewrk** [StackExchange/dapper-dot-net#622]
Using Dapper 1.50.2 and SqlBuilder 1.50.0 and the following code:

```
var builder = new SqlBuilder();
var template = builder.AddTemplate("SELECT * FROM Table /**where**/");

builder.Where("Name = @Name", new { Name = "Bob" });

Console.WriteLine(template.RawSql);
```

I get the following:

> SELECT * FROM Table WHERE Name = @Name

I'm not sure if I'm using it incorrectly but I expected that the parameter value would be replaced at that point? This works when using Dapper directly through its IDbConnection extension methods but not through SqlBuilder.

**Comment by matthewrk** [comment]
Ok, that leads me to the question why does the Where method take parameters? Am I supposed to be passing them back into the eventual Query method again via template.Parameters?

**Comment by mgravell** [comment]
That's a great question, one that I don't know the answer without looking.
Will try to look later.

**Comment by matthewrk** [comment]
So it looks like the intended use is to pass params objects into SqlBuilder.AddTemplate() and then additionally as and where required into the SqlBuilder methods such as Where(). Somewhere under the hood I assume its merging the objects which can then be accessed under template.Parameters which should be used on the eventual query method, e.g. Query<SomeType>(template.RawSql, template.Parameters). That's working for me and is nice and clean, it just works slightly differently to how I had initially thought.

Thanks for pointing me in the right direction 👍

**Comment by sakopov** [comment]
Could you share how you're adding parameters? The Parameters property on the template is always empty regardless whether i pass parameter using AddTemplate or any other method.
