### ISSUE TITLE
The text is too long to be displayed. (Options -> Query settings -> 60000)

### ISSUE THREAD

**Issue by iZhongCheng** [StackExchange/dapper-dot-net#626]
```C#
using (IDbConnection conn = new SqlConnection(strSqlconn))
{
    var sqlStr = "Update tableName set ids = @Ids";
    var param = new { Ids = new List<int> { 1, 2, 3, 4, 5  ... } };
    var row = conn.Execute(sqlStr, param); 
}
```

**Comment by NickCraver** [comment]
What error are you reporting here? I can't make out what your SQL is trying to do. It's trying to set *all* rows to a list of IDs?

**Comment by NickCraver** [comment]
Closing this out to cleanup since I can't make heads or tails of this and there's no update - if there's a problem we can help with please ping.
