### ISSUE TITLE
Should `fieldNameLookup`  use `StringComparer.OrdinalIgnoreCase` ?

### ISSUE THREAD

**Issue by John0King** [StackExchange/dapper-dot-net#628]
[SqlMapper.DapperTable](https://github.com/StackExchange/dapper-dot-net/blob/master/Dapper/SqlMapper.DapperTable.cs)   Should the `fieldNameLookup` in this class use `StringComparer.OrdinalIgnoreCase` ?
I can not imagine when we need two filed "A" and "a",because database and sql  is  IgnoreCased

**Comment by NickCraver** [comment]
SQL is not case insensitive. It *may* be case insensitive (and is with a fully default install). This is something set at the server collation level.

So yep, code is as intended.

**Comment by NickCraver** [comment]
Closing out to cleanup
