### ISSUE TITLE
Dapper actually does some connection management

### ISSUE THREAD

**Issue by adamkirkton** [StackExchange/dapper-dot-net#634]
Under the **Limitations and Caveats** section in the README.md it says:

> Dapper does not manage your connection's lifecycle, it assumes the connection it gets is open AND has no existing datareaders enumerating (unless MARS is enabled)

Which isn't completely true anymore. It's a small thing but it misled me as a new user of the library and can introduce some annoying and unnecessary code to open and close the connection all the time.

**Comment by mgravell** [comment]
True; fixed - thanks
