### ISSUE TITLE
ID of inserted row

### ISSUE THREAD

**Issue by pzaloznyi** [StackExchange/dapper-dot-net#650]
I didn't find any ability to return the ID of inserted row using Dapper ORM.
Stackoverflow shows only possible bypasses. Is there such feature or it will be developed in future?

**Comment by mgravell** [comment]
Which API are you using? If you are using the extension bits, IIRC it
assigns the Id on the object you pass in. In the raw dapper API (just the
dapper dll), you would need to "select scope_identity()" or similar after
the insert statement.

**Comment by pzaloznyi** [comment]
Sorry, forgot to mention. I'm using MySQL.

**Comment by pzaloznyi** [comment]
I found a resolution in Dapper.Contrib :) I'll just add it. Thank you guys.
