### ISSUE TITLE
Dapper support MongoDb

### ISSUE THREAD

**Issue by gayan85** [StackExchange/dapper-dot-net#671]
Does dapper support [mongoDb connector](http://mongodb.github.io/mongo-csharp-driver/?jmp=docs&_ga=1.149183798.1094993812.1483026245)?

**Comment by dbol55** [comment]
no

**Comment by mgravell** [comment]
dapper tries hard not to have to support most things - by sticking to the
core ado.net stack as far as possible. if the mongo connector is an ado.net
connection, it may work. If it doesn't work, please provide details (I
don't use mongo) and we can consider what would be involved in making it
happy.

**Comment by NickCraver** [comment]
Closing this out, as we cannot support the connector...it's just a totally different set of problems and really so far outside Dapper as to consider doing anything like this (and it just wouldn't make any sense). However, if you're using one of the ADO.NET adapters which make Mongo *seem* like an RDBMS, *it should work*. If it doesn't, please open an issue with details and we'll take a look.
