### ISSUE TITLE
Any upcomming support for multi mapping in QuerySingleAsync ?

### ISSUE THREAD

**Issue by Mech0z** [StackExchange/dapper-dot-net#674]
I do 

```
animals =
                        sqlConnection.QueryAsync<Animal, Gender, Breed, GenomeSelectionTest, Animal>(
                            sql,
                            (a, g, b, gst) =>
                            {
                                a.Gender = g;
                                a.Breed = b;
                                a.GenomeSelectionTest = gst;
                                return a;
                            },
                            new
                            {
                                AnimalNumber = animalNumber
                            });
```

But would like to change it to 

`sqlConnection.QuerySingleAsync<Animal, Gender, Breed, GenomeSelectionTest, Animal>(`

Is this support coming or am I supposed to use some other method for multimapping?

**Comment by NickCraver** [comment]
I don't see us adding that rather large count of overloads to the main library. Your current method will likely remain the proper one. There are just far too many combinations of `First`, `FirstOrDefault`, `Single`, `SingleOrDefault`, all of those with `Async` duplicates, and times `n` generic overloads. It's just too much code in play and creates a maintenance nightmare.

*Just* doing it today with `Query` and `QueryAsync` is a lot of code...we're talking about greatly increasing that. So my answer here would be: you're doing it right, stick with it.
