### ISSUE TITLE
Dapper isn't fetching parameters of a IDictionary<string, object>

### ISSUE THREAD

**Issue by johnnyasantoss** [StackExchange/dapper-dot-net#680]
I have a string with my query and I'm passing to `params` parameter a `IDictionary<string, object>`.

#### Query
```sql
SELECT Id, Name
FROM MyTable
WHERE (Id = @p1)
```

#### Test
```csharp
public MyEntity GetExact(int id)
{
    IDictionary<string, object> myParams = new Dictionary<string, object>
    {
        ["@p1"] = id
    };
    return myConnection.QueryFirstOrDefault<MyEntity>(myQuery, myParams);
}
```

#### Expected behavior

Use values from a dictionary to relate them to the parameters in a query string

#### Result

Dapper isn't fetching values from `IDicitionary<string, object>` nor `IEnumerable<KeyValuePair<string, object>>`

`Column '@p1' not found`.

Possibly related to #234 
PS: I've already tried pass the key without `@`

**Comment by NickCraver** [comment]
I'm not sure we support this, or should. Why is `IDictionary` needed here?  We have `DynamicParameters` built-in for this specific case of creating your own collection feeding in (if you can't just use an object already). 

Can you elaborate on why that scenario doesn't fit what you're trying to do?

**Comment by johnnyasantoss** [comment]
I'm generating my SQL queries at a library a part, so it does not have a reference to Dapper. This is just an enhancement for Dapper, `IDictionary` is way more often used than `DynamicParameters`.

It would be nice a implicit converter exists between this two types making easier to make a query, without having to convert or generate another instance of a type that's almost equal to a `IDictionary`.

**Comment by NickCraver** [comment]
The problem is that `IDictionary` has no type data, there's so much to go wrong here. We'd have to extrapolate data that doesn't often exist. I don't agree this should be an addition. You're free to create a dynamic object and pass it in, or use `DynamicParameters` which is used for this. I also don't understand how you're avoiding a reference to Dapper if you're calling the extension method...can you elaborate there?

**Comment by johnnyasantoss** [comment]
Ok. I've already made an extension method to do this conversion. 
I can't have a reference on my lib1 (the lib that generates my sql query) just to get my queries going on lib2 (web proj/ console app / whatever)
Thanks
