### ISSUE TITLE
Unable to compile Dapper.sln with VS 2015

### ISSUE THREAD

**Issue by nCubed** [StackExchange/dapper-dot-net#695]
With either pulling down a forked repo of dapper or a zip of the dapper repo, I am unable to compile the solution using VS 2015 Enterprise (update 3).

**Steps to Reproduce:**

1. Pull down zip file of project from dapper github repo
2. Extract zip
3. Open Dapper.sln with Visual Studio 2015
4. Build solution

_Upon building, the following error is thrown:_

> Error	CS0535	'FbAdapter' does not implement interface member 'ISqlAdapter.InsertAsync(IDbConnection, IDbTransaction, int?, string, string, string, IEnumerable<PropertyInfo>, object)'	Dapper.Contrib	C:\dapper-dot-net-master\Dapper.Contrib\SqlMapperExtensions.cs	869	

Is there anything outside of the O.O.B. Visual Studio that needs to be installed? Maybe a VS extension? Or?

**Comment by NickCraver** [comment]
Doh, that PR wasn't complete for 4.5 - fixed in latest. I realize there's race there, but I'm not 100% on firebase returns...in V2 all of these Insert methods will get a lot of generics and race-condition-less love.
